-- Expands every Beverages subcategory to 50+ items (per user request).
-- All names are original to this shop (not copied from any other brand's menu).
-- Run this once against an already-migrated database (after migration_v4_departments.sql).
USE pos_system;

SET @coffee = (SELECT id FROM categories WHERE name = 'Coffee');
SET @espresso = (SELECT id FROM categories WHERE name = 'Espresso');
SET @teas = (SELECT id FROM categories WHERE name = 'Teas');
SET @refreshers = (SELECT id FROM categories WHERE name = 'Refreshers');
SET @frozen = (SELECT id FROM categories WHERE name = 'Frozen');
SET @other_bev = (SELECT id FROM categories WHERE name = 'Other Beverages');

-- ==================== COFFEE (44 new -> 52 total) ====================
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@coffee, 'French Roast Coffee', 'Bold dark French roast', 2.85, 0.60, 'Blend'),
 (@coffee, 'Breakfast Blend Coffee', 'Smooth light morning blend', 2.75, 0.60, 'Blend'),
 (@coffee, 'Hazelnut Blend Coffee', 'Coffee with hazelnut notes', 2.95, 0.65, 'Blend'),
 (@coffee, 'Vanilla Blend Coffee', 'Coffee with vanilla notes', 2.95, 0.65, 'Blend'),
 (@coffee, 'Caramel Blend Coffee', 'Coffee with caramel notes', 2.95, 0.65, 'Blend'),
 (@coffee, 'Mocha Blend Coffee', 'Coffee with chocolate notes', 2.95, 0.65, 'Blend'),
 (@coffee, 'Pumpkin Blend Coffee', 'Seasonal pumpkin spice blend', 3.05, 0.70, 'Blend'),
 (@coffee, 'Peppermint Blend Coffee', 'Seasonal peppermint blend', 3.05, 0.70, 'Blend'),
 (@coffee, 'Toasted Almond Blend Coffee', 'Coffee with toasted almond notes', 2.95, 0.65, 'Blend'),
 (@coffee, 'Coconut Blend Coffee', 'Coffee with coconut notes', 2.95, 0.65, 'Blend'),
 (@coffee, 'Irish Cream Blend Coffee', 'Coffee with Irish cream notes', 2.95, 0.65, 'Blend'),
 (@coffee, 'Cinnamon Spice Blend Coffee', 'Coffee with warm cinnamon spice', 2.95, 0.65, 'Blend'),
 (@coffee, 'Vanilla Cold Brew', 'Cold brew with vanilla', 4.50, 1.10, 'Cold Brew'),
 (@coffee, 'Caramel Cold Brew', 'Cold brew with caramel', 4.50, 1.10, 'Cold Brew'),
 (@coffee, 'Mocha Cold Brew', 'Cold brew with chocolate', 4.50, 1.10, 'Cold Brew'),
 (@coffee, 'Sweet Cream Cold Brew', 'Cold brew with sweet cream', 4.50, 1.10, 'Cold Brew'),
 (@coffee, 'Toasted Coconut Cold Brew', 'Cold brew with toasted coconut', 4.65, 1.15, 'Cold Brew'),
 (@coffee, 'Salted Caramel Cold Brew', 'Cold brew with salted caramel', 4.65, 1.15, 'Cold Brew'),
 (@coffee, 'Iced Coffee Original', 'Classic iced coffee', 3.25, 0.75, 'Iced Coffee'),
 (@coffee, 'Iced Coffee Vanilla', 'Iced coffee with vanilla', 3.45, 0.80, 'Iced Coffee'),
 (@coffee, 'Iced Coffee Caramel', 'Iced coffee with caramel', 3.45, 0.80, 'Iced Coffee'),
 (@coffee, 'Iced Coffee Mocha', 'Iced coffee with chocolate', 3.45, 0.80, 'Iced Coffee'),
 (@coffee, 'Iced Coffee Hazelnut', 'Iced coffee with hazelnut', 3.45, 0.80, 'Iced Coffee'),
 (@coffee, 'Iced Coffee French Vanilla', 'Iced coffee with French vanilla', 3.55, 0.85, 'Iced Coffee'),
 (@coffee, 'Iced Coffee Toasted Almond', 'Iced coffee with toasted almond', 3.55, 0.85, 'Iced Coffee'),
 (@coffee, 'Iced Coffee Cinnamon', 'Iced coffee with cinnamon', 3.45, 0.80, 'Iced Coffee'),
 (@coffee, 'Vanilla Hot Coffee', 'Hot coffee with vanilla', 2.95, 0.65, 'Flavored Hot Coffee'),
 (@coffee, 'Caramel Hot Coffee', 'Hot coffee with caramel', 2.95, 0.65, 'Flavored Hot Coffee'),
 (@coffee, 'Hazelnut Hot Coffee', 'Hot coffee with hazelnut', 2.95, 0.65, 'Flavored Hot Coffee'),
 (@coffee, 'Mocha Hot Coffee', 'Hot coffee with chocolate', 2.95, 0.65, 'Flavored Hot Coffee'),
 (@coffee, 'French Vanilla Hot Coffee', 'Hot coffee with French vanilla', 3.05, 0.70, 'Flavored Hot Coffee'),
 (@coffee, 'Butter Pecan Hot Coffee', 'Hot coffee with butter pecan', 3.05, 0.70, 'Flavored Hot Coffee'),
 (@coffee, 'Toasted Marshmallow Hot Coffee', 'Hot coffee with toasted marshmallow', 3.05, 0.70, 'Flavored Hot Coffee'),
 (@coffee, 'Pumpkin Spice Hot Coffee', 'Seasonal pumpkin spice hot coffee', 3.15, 0.75, 'Flavored Hot Coffee'),
 (@coffee, 'Peppermint Mocha Hot Coffee', 'Seasonal peppermint mocha hot coffee', 3.15, 0.75, 'Flavored Hot Coffee'),
 (@coffee, 'Cinnamon Dolce Hot Coffee', 'Hot coffee with cinnamon dolce', 3.05, 0.70, 'Flavored Hot Coffee'),
 (@coffee, 'Decaf Vanilla Coffee', 'Decaf coffee with vanilla', 2.85, 0.60, 'Decaf & Light Roast'),
 (@coffee, 'Decaf Caramel Coffee', 'Decaf coffee with caramel', 2.85, 0.60, 'Decaf & Light Roast'),
 (@coffee, 'Decaf Hazelnut Coffee', 'Decaf coffee with hazelnut', 2.85, 0.60, 'Decaf & Light Roast'),
 (@coffee, 'Light Roast Original', 'Smooth light roast coffee', 2.75, 0.60, 'Decaf & Light Roast'),
 (@coffee, 'Light Roast Breakfast Blend', 'Light roast breakfast blend', 2.75, 0.60, 'Decaf & Light Roast'),
 (@coffee, 'Light Roast Hazelnut', 'Light roast with hazelnut', 2.85, 0.60, 'Decaf & Light Roast'),
 (@coffee, 'Light Roast Vanilla', 'Light roast with vanilla', 2.85, 0.60, 'Decaf & Light Roast'),
 (@coffee, 'Light Roast Caramel', 'Light roast with caramel', 2.85, 0.60, 'Decaf & Light Roast');

-- ==================== ESPRESSO (40 new -> 52 total) ====================
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@espresso, 'Flat White', 'Espresso with steamed micro-foam milk', 4.25, 1.20, 'Single Espresso'),
 (@espresso, 'Espresso Con Panna', 'Espresso topped with whipped cream', 3.75, 1.00, 'Single Espresso'),
 (@espresso, 'Ristretto', 'Short concentrated espresso shot', 2.75, 0.65, 'Single Espresso'),
 (@espresso, 'Ristretto Latte', 'Ristretto with steamed milk', 4.25, 1.20, 'Single Espresso'),
 (@espresso, 'Vanilla Latte', 'Latte with vanilla', 4.50, 1.30, 'Single Espresso'),
 (@espresso, 'Caramel Latte', 'Latte with caramel', 4.50, 1.30, 'Single Espresso'),
 (@espresso, 'Hazelnut Latte', 'Latte with hazelnut', 4.50, 1.30, 'Single Espresso'),
 (@espresso, 'Mocha Latte', 'Latte with chocolate', 4.65, 1.35, 'Single Espresso'),
 (@espresso, 'White Mocha Latte', 'Latte with white chocolate', 4.75, 1.40, 'Single Espresso'),
 (@espresso, 'Pumpkin Spice Latte', 'Seasonal pumpkin spice latte', 4.85, 1.45, 'Single Espresso'),
 (@espresso, 'Peppermint Mocha Latte', 'Seasonal peppermint mocha latte', 4.85, 1.45, 'Single Espresso'),
 (@espresso, 'Cinnamon Dolce Latte', 'Latte with cinnamon dolce', 4.65, 1.35, 'Single Espresso'),
 (@espresso, 'Doppio', 'Double shot of espresso', 3.25, 0.75, 'Double Espresso'),
 (@espresso, 'Caramel Espresso Macchiato', 'Espresso marked with caramel foam', 4.50, 1.25, 'Double Espresso'),
 (@espresso, 'Iced Americano', 'Espresso with cold water', 3.75, 0.80, 'Double Espresso'),
 (@espresso, 'Vanilla Iced Americano', 'Iced americano with vanilla', 3.95, 0.90, 'Double Espresso'),
 (@espresso, 'Caramel Iced Americano', 'Iced americano with caramel', 3.95, 0.90, 'Double Espresso'),
 (@espresso, 'Brown Sugar Oat Latte', 'Espresso with oat milk and brown sugar', 4.75, 1.35, 'Double Espresso'),
 (@espresso, 'Honey Almondmilk Latte', 'Espresso with almond milk and honey', 4.75, 1.35, 'Double Espresso'),
 (@espresso, 'Toasted Vanilla Shaken Espresso', 'Shaken espresso with toasted vanilla', 4.65, 1.30, 'Double Espresso'),
 (@espresso, 'Iced Chai Latte', 'Chai latte served iced', 4.50, 1.15, 'Alternative Beverages'),
 (@espresso, 'Dirty Chai Latte', 'Chai latte with a shot of espresso', 4.75, 1.30, 'Alternative Beverages'),
 (@espresso, 'London Fog Latte', 'Earl grey tea latte with vanilla', 4.25, 1.10, 'Alternative Beverages'),
 (@espresso, 'Golden Turmeric Latte', 'Turmeric spiced milk latte', 4.50, 1.20, 'Alternative Beverages'),
 (@espresso, 'Iced Matcha Green Tea Latte', 'Matcha latte served iced', 4.75, 1.50, 'Alternative Beverages'),
 (@espresso, 'Horchata Latte', 'Espresso with cinnamon horchata milk', 4.75, 1.30, 'Alternative Beverages'),
 (@espresso, 'Cafe De Olla', 'Spiced cinnamon coffee', 3.95, 0.90, 'Alternative Beverages'),
 (@espresso, 'Cubano', 'Sweetened espresso shot', 3.25, 0.75, 'Alternative Beverages'),
 (@espresso, 'Vietnamese Style Iced Coffee', 'Iced coffee with sweet condensed milk', 4.25, 1.00, 'Alternative Beverages'),
 (@espresso, 'Affogato', 'Espresso poured over ice cream', 4.95, 1.50, 'Alternative Beverages'),
 (@espresso, 'Pumpkin Cream Cold Brew Latte', 'Cold brew topped with pumpkin cream', 5.25, 1.50, 'Seasonal Espresso'),
 (@espresso, 'Peppermint Bark Latte', 'Latte with peppermint bark', 4.95, 1.45, 'Seasonal Espresso'),
 (@espresso, 'Gingerbread Latte', 'Latte with gingerbread spice', 4.85, 1.40, 'Seasonal Espresso'),
 (@espresso, 'Eggnog Latte', 'Latte with eggnog', 4.95, 1.45, 'Seasonal Espresso'),
 (@espresso, 'Maple Pecan Latte', 'Latte with maple and pecan', 4.85, 1.40, 'Seasonal Espresso'),
 (@espresso, 'Toasted Coconut Latte', 'Latte with toasted coconut', 4.75, 1.35, 'Seasonal Espresso'),
 (@espresso, 'Irish Cream Latte', 'Latte with Irish cream', 4.75, 1.35, 'Seasonal Espresso'),
 (@espresso, 'Butterscotch Latte', 'Latte with butterscotch', 4.75, 1.35, 'Seasonal Espresso'),
 (@espresso, 'Caramel Apple Latte', 'Latte with caramel apple', 4.85, 1.40, 'Seasonal Espresso'),
 (@espresso, 'S''mores Latte', 'Latte with chocolate and toasted marshmallow', 4.95, 1.45, 'Seasonal Espresso');

-- ==================== TEAS (42 new -> 52 total) ====================
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@teas, 'Unsweetened Iced Tea', 'Freshly brewed iced tea, unsweetened', 2.75, 0.50, 'Iced Tea'),
 (@teas, 'Peach Iced Tea', 'Iced tea with peach', 2.95, 0.55, 'Iced Tea'),
 (@teas, 'Raspberry Iced Tea', 'Iced tea with raspberry', 2.95, 0.55, 'Iced Tea'),
 (@teas, 'Mango Iced Tea', 'Iced tea with mango', 2.95, 0.55, 'Iced Tea'),
 (@teas, 'Lemon Iced Tea', 'Iced tea with lemon', 2.85, 0.55, 'Iced Tea'),
 (@teas, 'Mint Iced Tea', 'Iced tea with mint', 2.85, 0.55, 'Iced Tea'),
 (@teas, 'Large Half & Half', 'Large iced tea and lemonade mix', 3.25, 0.65, 'Iced Tea'),
 (@teas, 'Black Iced Tea', 'Classic black iced tea', 2.75, 0.50, 'Iced Tea'),
 (@teas, 'Unsweetened Green Iced Tea', 'Iced green tea, unsweetened', 2.85, 0.50, 'Iced Tea'),
 (@teas, 'Passionfruit Iced Tea', 'Iced tea with passionfruit', 2.95, 0.55, 'Iced Tea'),
 (@teas, 'Earl Grey Tea', 'Classic bergamot black tea', 2.85, 0.50, 'Hot Tea'),
 (@teas, 'English Breakfast Tea', 'Full-bodied black breakfast tea', 2.75, 0.50, 'Hot Tea'),
 (@teas, 'Jasmine Green Tea', 'Green tea with jasmine', 2.85, 0.50, 'Hot Tea'),
 (@teas, 'Ginger Spice Tea', 'Herbal tea with ginger', 2.85, 0.50, 'Hot Tea'),
 (@teas, 'Lemon Ginger Tea', 'Herbal tea with lemon and ginger', 2.85, 0.50, 'Hot Tea'),
 (@teas, 'Vanilla Rooibos Tea', 'Caffeine-free rooibos with vanilla', 2.95, 0.55, 'Hot Tea'),
 (@teas, 'Turmeric Wellness Tea', 'Herbal tea with turmeric', 2.95, 0.55, 'Hot Tea'),
 (@teas, 'Lavender Dreams Tea', 'Herbal tea with lavender', 2.95, 0.55, 'Hot Tea'),
 (@teas, 'Cinnamon Apple Tea', 'Herbal tea with cinnamon apple', 2.85, 0.50, 'Hot Tea'),
 (@teas, 'Blackberry Sage Tea', 'Herbal tea with blackberry sage', 2.95, 0.55, 'Hot Tea'),
 (@teas, 'Orange Spice Tea', 'Black tea with orange spice', 2.85, 0.50, 'Hot Tea'),
 (@teas, 'White Peony Tea', 'Delicate white tea', 3.05, 0.60, 'Hot Tea'),
 (@teas, 'Hot Chai Tea', 'Spiced chai tea, hot', 3.25, 0.75, 'Chai & Matcha'),
 (@teas, 'Iced Chai Tea', 'Spiced chai tea, iced', 3.25, 0.75, 'Chai & Matcha'),
 (@teas, 'Vanilla Chai Tea', 'Chai tea with vanilla', 3.45, 0.85, 'Chai & Matcha'),
 (@teas, 'Spiced Chai Tea', 'Extra spiced chai tea', 3.45, 0.85, 'Chai & Matcha'),
 (@teas, 'Hot Matcha Green Tea', 'Whisked matcha green tea, hot', 3.95, 1.00, 'Chai & Matcha'),
 (@teas, 'Iced Matcha Green Tea', 'Whisked matcha green tea, iced', 4.15, 1.05, 'Chai & Matcha'),
 (@teas, 'Honey Matcha Tea', 'Matcha tea with honey', 4.25, 1.10, 'Chai & Matcha'),
 (@teas, 'Coconut Matcha Tea', 'Matcha tea with coconut milk', 4.25, 1.10, 'Chai & Matcha'),
 (@teas, 'Iced Milk Tea', 'Classic milk tea, iced', 4.25, 1.10, 'Bubble & Specialty Tea'),
 (@teas, 'Taro Milk Tea', 'Milk tea with taro', 4.50, 1.20, 'Bubble & Specialty Tea'),
 (@teas, 'Thai Milk Tea', 'Spiced Thai-style milk tea', 4.50, 1.20, 'Bubble & Specialty Tea'),
 (@teas, 'Honey Lemon Tea', 'Black tea with honey and lemon', 3.25, 0.65, 'Bubble & Specialty Tea'),
 (@teas, 'Peach Green Tea', 'Green tea with peach', 3.25, 0.65, 'Bubble & Specialty Tea'),
 (@teas, 'Strawberry Green Tea', 'Green tea with strawberry', 3.25, 0.65, 'Bubble & Specialty Tea'),
 (@teas, 'Mango Black Tea', 'Black tea with mango', 3.25, 0.65, 'Bubble & Specialty Tea'),
 (@teas, 'Lychee Tea', 'Black tea with lychee', 3.25, 0.65, 'Bubble & Specialty Tea'),
 (@teas, 'Watermelon Tea', 'Iced tea with watermelon', 3.25, 0.65, 'Bubble & Specialty Tea'),
 (@teas, 'Blueberry Tea', 'Iced tea with blueberry', 3.25, 0.65, 'Bubble & Specialty Tea'),
 (@teas, 'Vanilla Milk Tea', 'Milk tea with vanilla', 4.25, 1.10, 'Bubble & Specialty Tea'),
 (@teas, 'Coconut Milk Tea', 'Milk tea with coconut', 4.25, 1.10, 'Bubble & Specialty Tea');

-- ==================== REFRESHERS (45 new -> 54 total) ====================
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@refreshers, 'Peach Citrus Refresher', 'Fruit-flavored refresher with peach citrus', 3.75, 0.90, 'Classic'),
 (@refreshers, 'Watermelon Refresher', 'Watermelon-flavored refresher', 3.75, 0.90, 'Classic'),
 (@refreshers, 'Blueberry Pomegranate Refresher', 'Fruit-flavored refresher with blueberry pomegranate', 3.85, 0.95, 'Classic'),
 (@refreshers, 'Kiwi Berry Refresher', 'Fruit-flavored refresher with kiwi berry', 3.85, 0.95, 'Classic'),
 (@refreshers, 'Passionfruit Refresher', 'Passionfruit-flavored refresher', 3.85, 0.95, 'Classic'),
 (@refreshers, 'Raspberry Lemonade Refresher', 'Refresher with raspberry lemonade', 3.85, 0.95, 'Classic'),
 (@refreshers, 'Green Apple Refresher', 'Green apple-flavored refresher', 3.75, 0.90, 'Classic'),
 (@refreshers, 'Lychee Rose Refresher', 'Fruit-flavored refresher with lychee rose', 3.95, 1.00, 'Classic'),
 (@refreshers, 'Peach Daydream Refresher', 'Creamy peach refresher', 4.25, 1.10, 'Daydream'),
 (@refreshers, 'Watermelon Daydream Refresher', 'Creamy watermelon refresher', 4.25, 1.10, 'Daydream'),
 (@refreshers, 'Blueberry Daydream Refresher', 'Creamy blueberry refresher', 4.25, 1.10, 'Daydream'),
 (@refreshers, 'Kiwi Daydream Refresher', 'Creamy kiwi refresher', 4.25, 1.10, 'Daydream'),
 (@refreshers, 'Passionfruit Daydream Refresher', 'Creamy passionfruit refresher', 4.35, 1.15, 'Daydream'),
 (@refreshers, 'Coconut Daydream Refresher', 'Creamy coconut refresher', 4.35, 1.15, 'Daydream'),
 (@refreshers, 'Lychee Daydream Refresher', 'Creamy lychee refresher', 4.35, 1.15, 'Daydream'),
 (@refreshers, 'Guava Daydream Refresher', 'Creamy guava refresher', 4.35, 1.15, 'Daydream'),
 (@refreshers, 'Citrus Energy Refresher', 'Energizing citrus refresher', 4.25, 1.05, 'Energy Refreshers'),
 (@refreshers, 'Berry Energy Refresher', 'Energizing mixed berry refresher', 4.25, 1.05, 'Energy Refreshers'),
 (@refreshers, 'Tropical Energy Refresher', 'Energizing tropical refresher', 4.25, 1.05, 'Energy Refreshers'),
 (@refreshers, 'Mint Energy Refresher', 'Energizing mint refresher', 4.25, 1.05, 'Energy Refreshers'),
 (@refreshers, 'Ginger Energy Refresher', 'Energizing ginger refresher', 4.25, 1.05, 'Energy Refreshers'),
 (@refreshers, 'Peach Energy Refresher', 'Energizing peach refresher', 4.25, 1.05, 'Energy Refreshers'),
 (@refreshers, 'Mango Energy Refresher', 'Energizing mango refresher', 4.25, 1.05, 'Energy Refreshers'),
 (@refreshers, 'Pineapple Energy Refresher', 'Energizing pineapple refresher', 4.25, 1.05, 'Energy Refreshers'),
 (@refreshers, 'Strawberry Splash', 'Sparkling strawberry fruit splash', 3.95, 0.95, 'Fruit Splash'),
 (@refreshers, 'Mango Splash', 'Sparkling mango fruit splash', 3.95, 0.95, 'Fruit Splash'),
 (@refreshers, 'Dragonfruit Splash', 'Sparkling dragonfruit fruit splash', 4.05, 1.00, 'Fruit Splash'),
 (@refreshers, 'Kiwi Splash', 'Sparkling kiwi fruit splash', 3.95, 0.95, 'Fruit Splash'),
 (@refreshers, 'Watermelon Splash', 'Sparkling watermelon fruit splash', 3.95, 0.95, 'Fruit Splash'),
 (@refreshers, 'Blueberry Splash', 'Sparkling blueberry fruit splash', 3.95, 0.95, 'Fruit Splash'),
 (@refreshers, 'Passionfruit Splash', 'Sparkling passionfruit fruit splash', 4.05, 1.00, 'Fruit Splash'),
 (@refreshers, 'Peach Splash', 'Sparkling peach fruit splash', 3.95, 0.95, 'Fruit Splash'),
 (@refreshers, 'Cherry Splash', 'Sparkling cherry fruit splash', 3.95, 0.95, 'Fruit Splash'),
 (@refreshers, 'Pineapple Splash', 'Sparkling pineapple fruit splash', 3.95, 0.95, 'Fruit Splash'),
 (@refreshers, 'Half & Half Refresher', 'Two refresher flavors combined', 3.85, 0.95, 'Mix It'),
 (@refreshers, 'Double Berry Mix Refresher', 'Mixed berry refresher combo', 3.95, 1.00, 'Mix It'),
 (@refreshers, 'Tropical Mix Refresher', 'Mixed tropical refresher combo', 3.95, 1.00, 'Mix It'),
 (@refreshers, 'Citrus Mix Refresher', 'Mixed citrus refresher combo', 3.85, 0.95, 'Mix It'),
 (@refreshers, 'Build Your Own Zero Sugar Refresher', 'Choose a zero-sugar flavor combination', 3.85, 0.95, 'Mix It'),
 (@refreshers, 'Sparkling Strawberry Refresher', 'Lightly sparkling strawberry refresher', 4.15, 1.05, 'Sparkling Refreshers'),
 (@refreshers, 'Sparkling Peach Refresher', 'Lightly sparkling peach refresher', 4.15, 1.05, 'Sparkling Refreshers'),
 (@refreshers, 'Sparkling Citrus Refresher', 'Lightly sparkling citrus refresher', 4.15, 1.05, 'Sparkling Refreshers'),
 (@refreshers, 'Sparkling Berry Refresher', 'Lightly sparkling mixed berry refresher', 4.15, 1.05, 'Sparkling Refreshers'),
 (@refreshers, 'Sparkling Mango Refresher', 'Lightly sparkling mango refresher', 4.15, 1.05, 'Sparkling Refreshers'),
 (@refreshers, 'Sparkling Watermelon Refresher', 'Lightly sparkling watermelon refresher', 4.15, 1.05, 'Sparkling Refreshers');

-- ==================== FROZEN (42 new -> 52 total) ====================
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@frozen, 'Watermelon Cooler', 'Blended watermelon frozen drink', 4.35, 1.05, 'Frozen Coolers'),
 (@frozen, 'Mango Cooler', 'Blended mango frozen drink', 4.35, 1.05, 'Frozen Coolers'),
 (@frozen, 'Peach Cooler', 'Blended peach frozen drink', 4.35, 1.05, 'Frozen Coolers'),
 (@frozen, 'Green Apple Cooler', 'Blended green apple frozen drink', 4.35, 1.05, 'Frozen Coolers'),
 (@frozen, 'Pina Colada Cooler', 'Blended pineapple coconut frozen drink', 4.45, 1.10, 'Frozen Coolers'),
 (@frozen, 'Kiwi Cooler', 'Blended kiwi frozen drink', 4.35, 1.05, 'Frozen Coolers'),
 (@frozen, 'Passionfruit Cooler', 'Blended passionfruit frozen drink', 4.45, 1.10, 'Frozen Coolers'),
 (@frozen, 'Sour Cherry Cooler', 'Blended sour cherry frozen drink', 4.35, 1.05, 'Frozen Coolers'),
 (@frozen, 'Vanilla Bean Frozen Coffee', 'Blended frozen coffee with vanilla bean', 4.85, 1.35, 'Frozen Coffee'),
 (@frozen, 'Hazelnut Frozen Coffee', 'Blended frozen coffee with hazelnut', 4.85, 1.35, 'Frozen Coffee'),
 (@frozen, 'Cookies and Cream Frozen Coffee', 'Blended frozen coffee with cookies and cream', 4.95, 1.40, 'Frozen Coffee'),
 (@frozen, 'White Chocolate Frozen Coffee', 'Blended frozen coffee with white chocolate', 4.95, 1.40, 'Frozen Coffee'),
 (@frozen, 'Toasted Coconut Frozen Coffee', 'Blended frozen coffee with toasted coconut', 4.85, 1.35, 'Frozen Coffee'),
 (@frozen, 'Salted Caramel Frozen Coffee', 'Blended frozen coffee with salted caramel', 4.95, 1.40, 'Frozen Coffee'),
 (@frozen, 'Butterscotch Frozen Coffee', 'Blended frozen coffee with butterscotch', 4.85, 1.35, 'Frozen Coffee'),
 (@frozen, 'Cinnamon Frozen Coffee', 'Blended frozen coffee with cinnamon', 4.85, 1.35, 'Frozen Coffee'),
 (@frozen, 'Frozen Hot Chocolate', 'Blended frozen hot chocolate', 4.75, 1.30, 'Frozen Specialty'),
 (@frozen, 'Frozen White Hot Chocolate', 'Blended frozen white hot chocolate', 4.85, 1.35, 'Frozen Specialty'),
 (@frozen, 'Frozen Caramel Macchiato', 'Blended frozen caramel macchiato', 4.95, 1.40, 'Frozen Specialty'),
 (@frozen, 'Frozen Mocha', 'Blended frozen mocha', 4.85, 1.35, 'Frozen Specialty'),
 (@frozen, 'Frozen Vanilla Latte', 'Blended frozen vanilla latte', 4.85, 1.35, 'Frozen Specialty'),
 (@frozen, 'Frozen Honey Latte', 'Blended frozen honey latte', 4.85, 1.35, 'Frozen Specialty'),
 (@frozen, 'Frozen Toffee Latte', 'Blended frozen toffee latte', 4.95, 1.40, 'Frozen Specialty'),
 (@frozen, 'Frozen Cinnamon Latte', 'Blended frozen cinnamon latte', 4.85, 1.35, 'Frozen Specialty'),
 (@frozen, 'Frozen Strawberry Lemonade', 'Blended frozen strawberry lemonade', 4.25, 1.00, 'Other Frozen'),
 (@frozen, 'Frozen Mango Lemonade', 'Blended frozen mango lemonade', 4.25, 1.00, 'Other Frozen'),
 (@frozen, 'Frozen Peach Tea', 'Blended frozen peach tea', 4.15, 0.95, 'Other Frozen'),
 (@frozen, 'Frozen Hibiscus Tea', 'Blended frozen hibiscus tea', 4.15, 0.95, 'Other Frozen'),
 (@frozen, 'Frozen Green Tea', 'Blended frozen green tea', 4.15, 0.95, 'Other Frozen'),
 (@frozen, 'Frozen Berry Hibiscus', 'Blended frozen berry hibiscus tea', 4.25, 1.00, 'Other Frozen'),
 (@frozen, 'Blueberry Frozen Blend', 'Blended blueberry frozen drink', 4.45, 1.10, 'Frozen Fruit Blends'),
 (@frozen, 'Raspberry Frozen Blend', 'Blended raspberry frozen drink', 4.45, 1.10, 'Frozen Fruit Blends'),
 (@frozen, 'Blackberry Frozen Blend', 'Blended blackberry frozen drink', 4.45, 1.10, 'Frozen Fruit Blends'),
 (@frozen, 'Tropical Frozen Blend', 'Blended tropical fruit frozen drink', 4.45, 1.10, 'Frozen Fruit Blends'),
 (@frozen, 'Citrus Frozen Blend', 'Blended citrus frozen drink', 4.35, 1.05, 'Frozen Fruit Blends'),
 (@frozen, 'Melon Frozen Blend', 'Blended melon frozen drink', 4.35, 1.05, 'Frozen Fruit Blends'),
 (@frozen, 'Grape Frozen Blend', 'Blended grape frozen drink', 4.35, 1.05, 'Frozen Fruit Blends'),
 (@frozen, 'Pomegranate Frozen Blend', 'Blended pomegranate frozen drink', 4.45, 1.10, 'Frozen Fruit Blends'),
 (@frozen, 'Apple Cinnamon Frozen Blend', 'Blended apple cinnamon frozen drink', 4.35, 1.05, 'Frozen Fruit Blends'),
 (@frozen, 'Coconut Cream Frozen Blend', 'Blended coconut cream frozen drink', 4.45, 1.10, 'Frozen Fruit Blends'),
 (@frozen, 'Banana Frozen Blend', 'Blended banana frozen drink', 4.35, 1.05, 'Frozen Fruit Blends'),
 (@frozen, 'Guava Frozen Blend', 'Blended guava frozen drink', 4.45, 1.10, 'Frozen Fruit Blends');

-- ==================== OTHER BEVERAGES (45 new -> 53 total) ====================
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@other_bev, 'Cola', 'Classic cola fountain drink', 2.25, 0.30, 'Coolers & Fountain'),
 (@other_bev, 'Diet Cola', 'Diet cola fountain drink', 2.25, 0.30, 'Coolers & Fountain'),
 (@other_bev, 'Lemon Lime Soda', 'Lemon lime fountain soda', 2.25, 0.30, 'Coolers & Fountain'),
 (@other_bev, 'Root Beer', 'Root beer fountain drink', 2.25, 0.30, 'Coolers & Fountain'),
 (@other_bev, 'Orange Soda', 'Orange fountain soda', 2.25, 0.30, 'Coolers & Fountain'),
 (@other_bev, 'Ginger Ale', 'Ginger ale fountain drink', 2.25, 0.30, 'Coolers & Fountain'),
 (@other_bev, 'Fruit Punch Soda', 'Fruit punch fountain drink', 2.25, 0.30, 'Coolers & Fountain'),
 (@other_bev, 'Grape Soda', 'Grape fountain soda', 2.25, 0.30, 'Coolers & Fountain'),
 (@other_bev, 'Citrus Splash Zero', 'Zero-sugar sparkling water', 2.95, 0.60, 'Zero Sugar'),
 (@other_bev, 'Berry Burst Zero', 'Zero-sugar sparkling water', 2.95, 0.60, 'Zero Sugar'),
 (@other_bev, 'Peach Fizz Zero', 'Zero-sugar sparkling water', 2.95, 0.60, 'Zero Sugar'),
 (@other_bev, 'Watermelon Zero', 'Zero-sugar sparkling water', 2.95, 0.60, 'Zero Sugar'),
 (@other_bev, 'Mixed Berry Zero', 'Zero-sugar sparkling water', 2.95, 0.60, 'Zero Sugar'),
 (@other_bev, 'Lime Mint Zero', 'Zero-sugar sparkling water', 2.95, 0.60, 'Zero Sugar'),
 (@other_bev, 'Box of Tea (12 cups)', 'Tea box for meetings and events', 21.99, 8.50, 'Bulk'),
 (@other_bev, 'Gallon of Lemonade', 'Bulk lemonade for events', 14.99, 5.00, 'Bulk'),
 (@other_bev, 'Gallon of Refresher', 'Bulk refresher for events', 17.99, 6.50, 'Bulk'),
 (@other_bev, 'Party Box of Coffee (24 cups)', 'Large coffee box for big events', 39.99, 16.00, 'Bulk'),
 (@other_bev, 'Airpot of Coffee', 'Insulated airpot of fresh coffee', 26.99, 10.00, 'Bulk'),
 (@other_bev, 'Box of Hot Chocolate (12 cups)', 'Hot chocolate box for events', 23.99, 9.50, 'Bulk'),
 (@other_bev, 'Bottled Water', 'Single-serve bottled water', 1.99, 0.40, 'Bottled & Juices'),
 (@other_bev, 'Sparkling Water', 'Single-serve sparkling water', 2.49, 0.50, 'Bottled & Juices'),
 (@other_bev, 'Orange Juice', 'Bottled orange juice', 2.99, 0.90, 'Bottled & Juices'),
 (@other_bev, 'Apple Juice', 'Bottled apple juice', 2.99, 0.90, 'Bottled & Juices'),
 (@other_bev, 'Cranberry Juice', 'Bottled cranberry juice', 2.99, 0.90, 'Bottled & Juices'),
 (@other_bev, 'Grapefruit Juice', 'Bottled grapefruit juice', 2.99, 0.90, 'Bottled & Juices'),
 (@other_bev, 'Pineapple Juice', 'Bottled pineapple juice', 2.99, 0.90, 'Bottled & Juices'),
 (@other_bev, 'Tomato Juice', 'Bottled tomato juice', 2.99, 0.90, 'Bottled & Juices'),
 (@other_bev, 'Bottled Lemonade', 'Bottled fresh lemonade', 3.25, 1.00, 'Bottled & Juices'),
 (@other_bev, 'Fruit Punch Juice', 'Bottled fruit punch juice', 2.99, 0.90, 'Bottled & Juices'),
 (@other_bev, 'Whole Milk', 'Single-serve whole milk', 1.99, 0.50, 'Milk & Extras'),
 (@other_bev, 'Chocolate Milk', 'Single-serve chocolate milk', 2.25, 0.55, 'Milk & Extras'),
 (@other_bev, 'Oat Milk Carton', 'Single-serve oat milk', 2.75, 0.90, 'Milk & Extras'),
 (@other_bev, 'Almond Milk Carton', 'Single-serve almond milk', 2.75, 0.90, 'Milk & Extras'),
 (@other_bev, 'Hot Chocolate', 'Rich hot chocolate', 3.25, 0.80, 'Milk & Extras'),
 (@other_bev, 'White Hot Chocolate', 'Rich white hot chocolate', 3.45, 0.90, 'Milk & Extras'),
 (@other_bev, 'Steamed Milk', 'Warm steamed milk', 2.75, 0.60, 'Milk & Extras'),
 (@other_bev, 'Vanilla Steamer', 'Steamed milk with vanilla', 3.25, 0.80, 'Milk & Extras'),
 (@other_bev, 'Caramel Steamer', 'Steamed milk with caramel', 3.25, 0.80, 'Milk & Extras'),
 (@other_bev, 'Honey Steamer', 'Steamed milk with honey', 3.25, 0.80, 'Milk & Extras'),
 (@other_bev, 'Kids Hot Chocolate', 'Small hot chocolate for kids', 2.25, 0.55, 'Kids Drinks'),
 (@other_bev, 'Kids Chocolate Milk', 'Small chocolate milk for kids', 1.99, 0.50, 'Kids Drinks'),
 (@other_bev, 'Kids Apple Juice', 'Small apple juice for kids', 1.75, 0.45, 'Kids Drinks'),
 (@other_bev, 'Kids Lemonade', 'Small lemonade for kids', 1.75, 0.45, 'Kids Drinks'),
 (@other_bev, 'Kids Fruit Punch', 'Small fruit punch for kids', 1.75, 0.45, 'Kids Drinks');
