package com.possystem.gui;

import com.possystem.util.I18n;
import com.possystem.util.UITheme;

import javax.swing.*;
import java.awt.*;

/**
 * A Help/FAQ dialog available in all 5 supported languages. Its language dropdown drives the
 * same global {@link I18n} language used by the rest of the POS, so picking a language here
 * also switches the main screen once the dialog is closed.
 */
public class HelpDialog extends JDialog {

    // English question/answer pairs, each followed by {bn, hi, es, fr} translations in the
    // same order. Index 0 of each row = the language-neutral lookup order used below.
    private static final String[][] TOPICS_EN = {
        {"How do I add an item to an order?",
         "Tap a department tab (Beverages, Bakery, etc.), then tap the item. Choose size, temperature, and any add-ons, then tap Item Done."},
        {"How does the Beverages checkout page work?",
         "Tap the Beverages tab, then pick a section on the right (Coffee, Espresso, Teas, Refreshers, Frozen, Other Beverages) to see drinks in that group. Tapping a drink opens its customize screen: choose a Size (each size adds its own price), Hot or Iced, and any Dairy/Sweetener, Flavor Swirl, or Add-On modifiers (each adds its own price too). Tap Item Done to add it to the cart on the left — Subtotal, Tax, and Total update automatically as you add items. Enter a Discount $ amount if needed, then press PAY and choose Credit Card, CASH (enter the amount the customer hands over on the keypad first), or GC Redeem to finish the sale."},
        {"How does the Featured checkout page work?",
         "Tap the Featured tab, then pick a section on the right (New Arrivals, Fan Favorites, Limited Time Offers, Value Bundles) to browse those drinks — customization, cart, and payment work exactly like Beverages. The News & Promos button at the bottom of that sidebar isn't a drink list — it opens a read-only board of this month's promotions; tap any other sidebar section to go back to ordering."},
        {"How does the Bakery checkout page work?",
         "Tap the Bakery tab, then pick a section on the right (Sweet Treats, Grab & Go, Bagels & Muffins, Donuts & Donut Holes) to browse cookies, pastries, cakes, and more — cart, discount, and payment work exactly like Beverages. Note: the customize screen still shows a Temperature row and drink-style modifiers (Dairy/Sweetener, Flavor Swirl, Add-On) for every item, including baked goods — these are safe to ignore for items like cookies or donuts; they won't affect the order unless you tap one on purpose."},
        {"How does the Sandwiches checkout page work?",
         "Tap the Sandwiches tab, then pick a section on the right (Breakfast Sandwiches, Specialty Sandwiches, Wraps & Bowls, Sides & Bites, Snacking) to browse those items — cart, discount, and payment work exactly like Beverages. Note: the customize screen still shows a Temperature row and drink-style modifiers (Dairy/Sweetener, Flavor Swirl, Add-On) for every item, including sandwiches — these are safe to ignore; they won't affect the order unless you tap one on purpose."},
        {"How does the Retail checkout page work?",
         "Tap the Retail tab, then pick a section on the right (Coffee & Tea, Mugs & Drinkware, Gift Sets & Holiday, Grab & Go Treats, Gift Cards & More) to browse those products — cart and CASH/Credit Card payment work exactly like Beverages. Important: GC Redeem is not yet wired up to finish a sale — after entering a gift card number it shows a confirmation message but does NOT complete the order, so always finish gift-card sales with Credit Card or CASH instead. Also, when selling a Gift Card item, leave the Size on the default (Small) and don't tap any modifier, since the customize screen doesn't yet lock a gift card to its printed face value."},
        {"How does the Local checkout page work?",
         "Tap the Local tab, then pick a section on the right (Local Items, Catering Menu, Charity, Deposits & Pup Cups) to browse those products — cart and CASH/Credit Card payment work exactly like Beverages. Important: for Charity Donation and Reusable Bag Deposit items, leave the Size on the default (Small) and don't tap any modifier — picking a larger size adds its price on top of the stated donation/deposit amount (e.g. a \"$5\" donation can silently become $6.00). Also note that tax is applied automatically to every item including donations and bag deposits; if a donation or deposit should be tax-free, use the Tax Exempt button on the Payments screen before finishing that sale."},
        {"How does the Functions checkout page work?",
         "Tap the Functions tab for manager/cashier tools instead of a menu — pick a group on the right (Manager, Daily Shift Functions, Reports, All Open Checks, Phone Orders, DT Orders, OTG Orders, Order Confirm Board, SUPPORT) to see real, working buttons for things like till/safe counts, price overrides, refunds, reports, and order queues; nothing here is added to the cart. Important: this build does not yet restrict any of these buttons by staff role — every signed-in user can currently reach sensitive actions like Menu Item Price Override, Transaction Return, Manual Credit Entry, and Close Application, so treat this tab as manager-only for now and avoid tapping Close Application unless you intend to shut down the terminal."},
        {"How does Menu Management work?",
         "Menu Management (left sidebar) is where you add or edit menu items, separate from the POS/Checkout tabs. Select an item and tap Edit Selected to change its Category, Name, Price, Cost, or Active status, or tap Add Item to create a new one. Important: when adding a new item, the Category list mixes department tabs (like \"Featured\" or \"Beverages\") together with real subcategories (like \"Coffee\" or \"New Arrivals\") with no distinction between them, and a department is picked by default — if you save an item under a department instead of a real subcategory, it will not appear anywhere in POS/Checkout and cannot be found. Always double-check that you've chosen an actual subcategory before saving. Also note there is no Delete button anywhere in the app — a wrongly-added item can only be deactivated (via Edit Selected or Functions > Menu Item Availability), never fully removed, so choose the category carefully the first time."},
        {"How does Inventory work?",
         "Inventory (left sidebar) tracks raw ingredient stock (like Espresso Beans or Bread), separate from Menu Management's menu items. Stock goes down automatically when a linked item is sold at checkout, and the sale is blocked with an \"Insufficient stock\" message if there isn't enough on hand. Select an ingredient and tap Adjust Stock to add or remove stock yourself for PURCHASE_IN, WASTE, or CORRECTION. Important: the app does not check that your typed amount matches the Reason you picked (e.g. you can type a negative number under PURCHASE_IN by mistake), and it does not stop you from adjusting stock below zero — always double-check the sign of the amount and the size of the adjustment before pressing OK, since there is no undo button and no way to view past adjustments from this screen."},
        {"How does Time Clock work?",
         "Time Clock (left sidebar) is self-service — tap Clock In when you start your shift and Clock Out when you finish; the button and status message always reflect whether you're currently clocked in. Managers and admins additionally see a \"Recent punches\" table of everyone's clock-ins below their own status. Important: this build does not let you or a manager fix a forgotten clock-out — if you forget to tap Clock Out, that entire shift will not be counted in Payroll at all, and the only way to close it is to tap Clock Out whenever you next remember, which will record whatever time it is at that moment. Always clock out before you leave, and tell a manager right away if you forget so they're aware that shift's hours may be missing from payroll."},
        {"How does Delivery Queue work?",
         "Delivery Queue (left sidebar) tracks delivery orders through a documented lifecycle — UNASSIGNED -> ASSIGNED -> PICKED_UP -> DELIVERED — starting the moment an order is checked out with order type DELIVERY. Select a row and use Assign to Driver... to name who's taking it, Mark Picked Up once they've left with it, and Mark Delivered once it's dropped off; check \"Show completed deliveries\" to see finished orders too. Important: this build does not enforce the order of those steps — Mark Delivered can be clicked on any row regardless of its current status, so an order can be marked DELIVERED with no driver ever assigned and no pickup ever confirmed. It also does not protect a completed delivery from being changed afterward — using Assign to Driver... on an already-PICKED_UP or already-DELIVERED order silently resets its status back to ASSIGNED with no warning, effectively un-completing it. Always double-check an order's current Status column before clicking any action button, and treat DELIVERED as provisional rather than final until this is fixed."},
        {"How does Recipes work?",
         "Recipes (left sidebar) shows numbered prep-instruction steps for any menu item, in a language you choose. Pick a Menu Item and a Language at the top; anyone can read the steps, but only managers and admins see Add Step, Edit Selected, and Delete Selected buttons to maintain them. Important: deleting a step does not renumber the ones after it, so a recipe can permanently show \"Step 1, Step 3\" with no Step 2 once something is removed — this is not a display error. Also, the Language box is free-text and accepts anything you type (e.g. \"ENG\" is treated as a completely different, separate language from \"en\", with no warning) — always double-check you've typed the exact same language code (en, bn, hi, es, fr) used elsewhere in the app, since a typo silently creates steps nobody will ever find again."},
        {"How does Reports work?",
         "Reports (left sidebar) is a real-time \"Today's Sales Summary\" — Orders Today, Total Sales, Tax Collected, and Discounts Given, plus a Top Sellers Today table, all recalculated from today's completed orders every time you open the page or press Refresh. Important: this page only ever shows today — there's no way to check yesterday or a date range from here; for longer-range reports (like 30-day item sales) use POS/Checkout > Functions > Reports instead. Also note: on the checkout screen, typing a Discount $ amount and then tapping Tab or clicking elsewhere (instead of pressing Enter) leaves the Subtotal/Tax/Total numbers on screen looking unchanged — the customer is still charged the correct discounted amount when you press PAY, but the displayed total can look wrong until then, so always press Enter right after typing a discount to see the true total before quoting a price to a customer."},
        {"How does Employees work?",
         "Employees (left sidebar) is the staff directory — a table of everyone's Name, Position, Phone, Email, Hourly Rate, and Active status. Tap Add Employee to create a new record, or select a row and tap Edit Selected to change it; Full Name is required, and Phone/Email/Hourly Rate are checked for valid formats before saving. Select a row and tap Create Login for Selected to give that employee a system account (username, temporary password, and Role of CASHIER/MANAGER/ADMIN) so they can sign in. Important: if you type an invalid Phone, Email, or Hourly Rate and press OK, the whole Add/Edit form closes and everything you typed is lost — you must start over from a blank form, so double-check every field before pressing OK. Also, Create Login for Selected does not check whether an employee already has a login — clicking it again with a different username silently creates a second, separate account for the same person, and there is no way from this screen to see or manage an employee's existing login. There is no Delete button for employees or logins anywhere in the app — uncheck Active on the Edit form instead of trying to remove someone."},
        {"How do I apply a discount?",
         "Enter the discount amount in the Discount $ box in the cart column before pressing PAY."},
        {"How do I take a delivery order?",
         "Change Order Type to DELIVERY and enter the delivery address when prompted."},
        {"How do I redeem a gift card?",
         "Press PAY, then tap GC Redeem and enter the gift card number."},
        {"How do I change the app language?",
         "Tap the language button next to the clock at the top of the screen and choose your language."},
        {"How do I register a loyalty customer?",
         "Tap + Loyalty Customer in the cart column and enter the customer's name and phone number."},
        {"How do I cancel an order?",
         "Tap Cancel Order in the cart column, or Cancel Saved/Stored Order on the Payments screen."},
        {"Who do I contact for more help?",
         "Use the SUPPORT section under the Functions tab to call or chat with support."},
    };

    private static final String[][] TOPICS_BN = {
        {"অর্ডারে কীভাবে আইটেম যোগ করব?",
         "একটি ডিপার্টমেন্ট ট্যাবে (পানীয়, বেকারি ইত্যাদি) ট্যাপ করুন, তারপর আইটেমে ট্যাপ করুন। সাইজ, তাপমাত্রা ও অ্যাড-অন বেছে নিয়ে আইটেম সম্পন্ন-এ ট্যাপ করুন।"},
        {"POS/Checkout: Beverages পেজ কীভাবে কাজ করে?",
         "Beverages ট্যাবে ট্যাপ করুন, তারপর ডানপাশের সেকশন (Coffee, Espresso, Teas, Refreshers, Frozen, Other Beverages) থেকে একটি বেছে নিয়ে সেই গ্রুপের আইটেম দেখুন। কোনো ড্রিংকে ট্যাপ করলে কাস্টমাইজ স্ক্রিন খুলবে: Size বেছে নিন (প্রতিটি সাইজের নিজস্ব দাম যোগ হয়), Hot বা Iced বেছে নিন, এবং যেকোনো Dairy/Sweetener, Flavor Swirl বা Add-On মডিফায়ার (প্রতিটিরও নিজস্ব দাম যোগ হয়)। আইটেম সম্পন্ন-এ ট্যাপ করলে সেটি বামপাশের কার্টে যোগ হবে — আইটেম যোগ করার সাথে সাথে Subtotal, Tax ও Total স্বয়ংক্রিয়ভাবে আপডেট হয়। প্রয়োজনে Discount $ পরিমাণ লিখুন, তারপর PAY চেপে Credit Card, CASH (আগে কীপ্যাডে গ্রাহকের দেওয়া টাকার পরিমাণ লিখতে হবে), অথবা GC Redeem বেছে নিয়ে বিক্রয় সম্পন্ন করুন।"},
        {"POS/Checkout: Featured পেজ কীভাবে কাজ করে?",
         "Featured ট্যাবে ট্যাপ করুন, তারপর ডানপাশের সেকশন (New Arrivals, Fan Favorites, Limited Time Offers, Value Bundles) থেকে বেছে নিয়ে সেসব ড্রিংক দেখুন — কাস্টমাইজেশন, কার্ট ও পেমেন্ট ঠিক Beverages-এর মতোই কাজ করে। সাইডবারের নিচে থাকা News & Promos বাটন কোনো ড্রিংকের তালিকা না — এটাতে ট্যাপ করলে এই মাসের প্রোমোশনের একটা তথ্যমূলক বোর্ড খোলে (শুধু দেখার জন্য); অর্ডারে ফিরতে সাইডবারের অন্য যেকোনো সেকশনে ট্যাপ করুন।"},
        {"POS/Checkout: Bakery পেজ কীভাবে কাজ করে?",
         "Bakery ট্যাবে ট্যাপ করুন, তারপর ডানপাশের সেকশন (Sweet Treats, Grab & Go, Bagels & Muffins, Donuts & Donut Holes) থেকে বেছে নিয়ে কুকি, পেস্ট্রি, কেক ইত্যাদি দেখুন — কার্ট, ছাড় ও পেমেন্ট ঠিক Beverages-এর মতোই কাজ করে। খেয়াল রাখুন: প্রতিটি আইটেমের কাস্টমাইজ স্ক্রিনে (বেকারি আইটেমসহ) এখনো Temperature ও পানীয়-স্টাইল মডিফায়ার (Dairy/Sweetener, Flavor Swirl, Add-On) দেখানো হয় — কুকি বা ডোনাটের মতো আইটেমের জন্য এগুলো উপেক্ষা করা নিরাপদ; ইচ্ছাকৃতভাবে না চাপলে এগুলো অর্ডারে প্রভাব ফেলবে না।"},
        {"POS/Checkout: Sandwiches পেজ কীভাবে কাজ করে?",
         "Sandwiches ট্যাবে ট্যাপ করুন, তারপর ডানপাশের সেকশন (Breakfast Sandwiches, Specialty Sandwiches, Wraps & Bowls, Sides & Bites, Snacking) থেকে বেছে নিয়ে সেসব আইটেম দেখুন — কার্ট, ছাড় ও পেমেন্ট ঠিক Beverages-এর মতোই কাজ করে। খেয়াল রাখুন: প্রতিটি আইটেমের (স্যান্ডউইচসহ) কাস্টমাইজ স্ক্রিনে এখনো Temperature ও পানীয়-স্টাইল মডিফায়ার (Dairy/Sweetener, Flavor Swirl, Add-On) দেখানো হয় — এগুলো উপেক্ষা করা নিরাপদ; ইচ্ছাকৃতভাবে না চাপলে এগুলো অর্ডারে প্রভাব ফেলবে না।"},
        {"POS/Checkout: Retail পেজ কীভাবে কাজ করে?",
         "Retail ট্যাবে ট্যাপ করুন, তারপর ডানপাশের সেকশন (Coffee & Tea, Mugs & Drinkware, Gift Sets & Holiday, Grab & Go Treats, Gift Cards & More) থেকে বেছে নিয়ে সেসব পণ্য দেখুন — কার্ট ও CASH/Credit Card পেমেন্ট ঠিক Beverages-এর মতোই কাজ করে। গুরুত্বপূর্ণ: GC Redeem এখনো অর্ডার সম্পন্ন করতে পারে না — গিফট কার্ড নম্বর দিলে একটা কনফার্মেশন মেসেজ দেখায় কিন্তু অর্ডার শেষ করে না, তাই গিফট কার্ড বিক্রির সময় সবসময় Credit Card বা CASH দিয়ে পেমেন্ট শেষ করুন। এছাড়া Gift Card আইটেম বিক্রির সময় Size ডিফল্টে (Small) রেখে দিন আর কোনো মডিফায়ারে ট্যাপ করবেন না, কারণ কাস্টমাইজ স্ক্রিন এখনো গিফট কার্ডকে তার লেখা মূল্যে আটকে রাখে না।"},
        {"POS/Checkout: Local পেজ কীভাবে কাজ করে?",
         "Local ট্যাবে ট্যাপ করুন, তারপর ডানপাশের সেকশন (Local Items, Catering Menu, Charity, Deposits & Pup Cups) থেকে বেছে নিয়ে সেসব পণ্য দেখুন — কার্ট ও CASH/Credit Card পেমেন্ট ঠিক Beverages-এর মতোই কাজ করে। গুরুত্বপূর্ণ: Charity Donation ও Reusable Bag Deposit আইটেমের ক্ষেত্রে Size ডিফল্টে (Small) রেখে দিন এবং কোনো মডিফায়ারে ট্যাপ করবেন না — বড় সাইজ বেছে নিলে সেই দাম লেখা ডোনেশন/ডিপোজিটের অংকের ওপর যোগ হয়ে যায় (যেমন একটা \"$5\" ডোনেশন নিঃশব্দে $6.00 হয়ে যেতে পারে)। এটাও খেয়াল রাখুন যে ডোনেশন ও ব্যাগ ডিপোজিটসহ প্রতিটি আইটেমের ওপর স্বয়ংক্রিয়ভাবে ট্যাক্স বসে; কোনো ডোনেশন বা ডিপোজিট ট্যাক্স-মুক্ত হওয়া উচিত হলে, সেই বিক্রয় শেষ করার আগে পেমেন্টস স্ক্রিনের Tax Exempt বাটন ব্যবহার করুন।"},
        {"POS/Checkout: Functions পেজ কীভাবে কাজ করে?",
         "Functions ট্যাবে মেনু নয়, বরং ম্যানেজার/ক্যাশিয়ার টুলস আছে — ডানপাশের গ্রুপ থেকে বেছে নিন (Manager, Daily Shift Functions, Reports, All Open Checks, Phone Orders, DT Orders, OTG Orders, Order Confirm Board, SUPPORT) যেখানে till/safe কাউন্ট, প্রাইস ওভাররাইড, রিফান্ড, রিপোর্ট ও অর্ডার কিউয়ের জন্য আসল, কার্যকরী বাটন আছে; এখানে কিছুই কার্টে যোগ হয় না। গুরুত্বপূর্ণ: এই বিল্ডে এখনো কোনো বাটন স্টাফের রোল অনুযায়ী সীমাবদ্ধ করা হয়নি — যেকোনো লগইন করা ইউজার এখন Menu Item Price Override, Transaction Return, Manual Credit Entry, ও Close Application-এর মতো স্পর্শকাতর অ্যাকশনে পৌঁছাতে পারে, তাই আপাতত এই ট্যাবটাকে ম্যানেজার-ওনলি হিসেবে বিবেচনা করুন এবং টার্মিনাল বন্ধ করার ইচ্ছা না থাকলে Close Application-এ ট্যাপ করবেন না।"},
        {"Menu Management কীভাবে কাজ করে?",
         "Menu Management (বাম সাইডবার) হলো মেনু আইটেম যোগ বা এডিট করার জায়গা, POS/Checkout ট্যাবগুলো থেকে আলাদা। একটি আইটেম বেছে নিয়ে Edit Selected-এ ট্যাপ করে তার Category, Name, Price, Cost বা Active স্ট্যাটাস পরিবর্তন করুন, অথবা নতুন আইটেমের জন্য Add Item-এ ট্যাপ করুন। গুরুত্বপূর্ণ: নতুন আইটেম যোগ করার সময় Category তালিকায় ডিপার্টমেন্ট ট্যাব (যেমন \"Featured\" বা \"Beverages\") ও আসল সাবক্যাটাগরি (যেমন \"Coffee\" বা \"New Arrivals\") একসাথে মিশে থাকে, কোনো পার্থক্য না দেখিয়েই, এবং ডিফল্ট হিসেবে একটা ডিপার্টমেন্ট বেছে নেওয়া থাকে — আসল সাবক্যাটাগরির বদলে ডিপার্টমেন্টের অধীনে আইটেম সেভ করলে সেটি POS/Checkout-এর কোথাও দেখা যাবে না এবং খুঁজে পাওয়া যাবে না। সেভ করার আগে সবসময় নিশ্চিত করুন যে আপনি একটা আসল সাবক্যাটাগরি বেছে নিয়েছেন। এটাও খেয়াল রাখুন যে অ্যাপে কোথাও Delete বাটন নেই — ভুলভাবে যোগ করা আইটেম শুধু ইনঅ্যাক্টিভ করা যায় (Edit Selected অথবা Functions > Menu Item Availability দিয়ে), সম্পূর্ণভাবে সরানো যায় না, তাই প্রথমবারেই ক্যাটাগরি সাবধানে বেছে নিন।"},
        {"Inventory কীভাবে কাজ করে?",
         "Inventory (বাম সাইডবার) কাঁচামালের স্টক ট্র্যাক করে (যেমন Espresso Beans বা Bread), Menu Management-এর মেনু আইটেম থেকে আলাদা। চেকআউটে কোনো লিংকড আইটেম বিক্রি হলে স্টক স্বয়ংক্রিয়ভাবে কমে যায়, আর পর্যাপ্ত স্টক না থাকলে \"Insufficient stock\" মেসেজ দিয়ে বিক্রয় আটকে দেওয়া হয়। একটি উপাদান বেছে নিয়ে Adjust Stock-এ ট্যাপ করে PURCHASE_IN, WASTE, বা CORRECTION-এর জন্য নিজে স্টক যোগ বা বিয়োগ করতে পারেন। গুরুত্বপূর্ণ: আপনি যে Reason বেছে নিয়েছেন তার সাথে টাইপ করা সংখ্যার সাইন মিলছে কিনা অ্যাপ চেক করে না (যেমন ভুলবশত PURCHASE_IN-এর নিচে নেগেটিভ সংখ্যা লিখতে পারেন), আর স্টক শূন্যের নিচে নামাতেও বাধা দেয় না — OK চাপার আগে সবসময় সংখ্যার সাইন ও পরিমাণ ভালোভাবে দেখে নিন, কারণ এখানে কোনো Undo বাটন নেই এবং এই স্ক্রিন থেকে আগের অ্যাডজাস্টমেন্টগুলো দেখারও কোনো উপায় নেই।"},
        {"Time Clock কীভাবে কাজ করে?",
         "Time Clock (বাম সাইডবার) সেলফ-সার্ভিস — শিফট শুরু করার সময় Clock In-এ ট্যাপ করুন আর শেষ করার সময় Clock Out-এ ট্যাপ করুন; বাটন ও স্ট্যাটাস মেসেজ সবসময় আপনি বর্তমানে ক্লক-ইন আছেন কিনা তা দেখায়। ম্যানেজার ও অ্যাডমিনরা নিজেদের স্ট্যাটাসের নিচে সবার ক্লক-ইনের একটা \"Recent punches\" টেবিলও দেখতে পান। গুরুত্বপূর্ণ: এই বিল্ডে আপনি বা কোনো ম্যানেজার ভুলে যাওয়া ক্লক-আউট ঠিক করতে পারবেন না — আপনি যদি Clock Out করতে ভুলে যান, তাহলে সেই পুরো শিফটটা Payroll-এ একদমই গণনা করা হবে না, আর সেটা বন্ধ করার একমাত্র উপায় হলো যখনই মনে পড়বে তখন Clock Out-এ ট্যাপ করা, যা সেই মুহূর্তের সময়টাই রেকর্ড করবে। বের হওয়ার আগে সবসময় ক্লক-আউট করুন, আর ভুলে গেলে সাথে সাথে একজন ম্যানেজারকে জানান যাতে তারা জানতে পারেন যে সেই শিফটের ঘণ্টাগুলো পেরোল থেকে বাদ পড়তে পারে।"},
        {"Delivery Queue কীভাবে কাজ করে?",
         "Delivery Queue (বাম সাইডবার) ডেলিভারি অর্ডারগুলোকে একটি নির্ধারিত ধাপক্রমে ট্র্যাক করে — UNASSIGNED -> ASSIGNED -> PICKED_UP -> DELIVERED — যা অর্ডার টাইপ DELIVERY দিয়ে চেকআউট করার সাথে সাথে শুরু হয়। একটি সারি বেছে নিয়ে Assign to Driver...-এ কে নিয়ে যাচ্ছে তা লিখুন, ড্রাইভার রওনা হলে Mark Picked Up চাপুন, আর ডেলিভারি হয়ে গেলে Mark Delivered চাপুন; সম্পন্ন হওয়া অর্ডারগুলোও দেখতে \"Show completed deliveries\" চেক করুন। গুরুত্বপূর্ণ: এই বিল্ডে এই ধাপগুলোর ক্রম বাধ্যতামূলক নয় — বর্তমান স্ট্যাটাস যাই হোক না কেন যেকোনো সারিতে Mark Delivered চাপা যায়, ফলে কোনো ড্রাইভার নিয়োগ বা পিকআপ নিশ্চিত না করেই একটি অর্ডার DELIVERED হিসেবে চিহ্নিত হতে পারে। এটি একটি সম্পন্ন ডেলিভারিকে পরে পরিবর্তিত হওয়া থেকেও রক্ষা করে না — ইতিমধ্যে PICKED_UP বা DELIVERED হওয়া অর্ডারে Assign to Driver... ব্যবহার করলে কোনো সতর্কতা ছাড়াই স্ট্যাটাস নিঃশব্দে ASSIGNED-এ ফিরে যায়, যা কার্যত সেটিকে অসম্পন্ন করে দেয়। যেকোনো অ্যাকশন বাটনে চাপার আগে সবসময় অর্ডারের বর্তমান Status কলাম ভালোভাবে দেখে নিন, আর এটি ঠিক না হওয়া পর্যন্ত DELIVERED-কে চূড়ান্ত না ভেবে সাময়িক হিসেবে বিবেচনা করুন।"},
        {"Recipes কীভাবে কাজ করে?",
         "Recipes (বাম সাইডবার) যেকোনো মেনু আইটেমের জন্য আপনার বেছে নেওয়া ভাষায় নম্বরযুক্ত প্রস্তুতির ধাপ দেখায়। উপরে একটি Menu Item ও একটি Language বেছে নিন; যে কেউ ধাপগুলো পড়তে পারে, কিন্তু শুধু ম্যানেজার ও অ্যাডমিনরা সেগুলো রক্ষণাবেক্ষণের জন্য Add Step, Edit Selected, ও Delete Selected বাটন দেখতে পান। গুরুত্বপূর্ণ: কোনো ধাপ ডিলিট করলে তার পরের ধাপগুলো পুনরায় নম্বরায়িত হয় না, তাই কিছু সরানোর পর একটি রেসিপি স্থায়ীভাবে \"Step 1, Step 3\" দেখাতে পারে, Step 2 ছাড়াই — এটি কোনো ডিসপ্লে ত্রুটি না। এছাড়া, Language বক্সটি ফ্রি-টেক্সট এবং আপনি যা টাইপ করেন তাই গ্রহণ করে (যেমন \"ENG\" কে \"en\" থেকে সম্পূর্ণ আলাদা একটি ভাষা হিসেবে গণ্য করা হয়, কোনো সতর্কতা ছাড়াই) — সবসময় নিশ্চিত করুন যে আপনি অ্যাপের অন্য জায়গায় ব্যবহৃত একই ভাষা কোড (en, bn, hi, es, fr) টাইপ করেছেন, কারণ একটি টাইপো নিঃশব্দে এমন ধাপ তৈরি করে যা আর কখনো খুঁজে পাওয়া যাবে না।"},
        {"Reports কীভাবে কাজ করে?",
         "Reports (বাম সাইডবার) একটি রিয়েল-টাইম \"Today's Sales Summary\" — Orders Today, Total Sales, Tax Collected, ও Discounts Given, সাথে একটি Top Sellers Today টেবিল, যা আপনি পেজটি খুললে বা Refresh চাপলে আজকের সম্পন্ন অর্ডার থেকে পুনরায় হিসাব হয়। গুরুত্বপূর্ণ: এই পেজ শুধু আজকের তথ্যই দেখায় — এখান থেকে গতকাল বা কোনো তারিখ-পরিসর দেখার উপায় নেই; দীর্ঘমেয়াদি রিপোর্টের জন্য (যেমন ৩০-দিনের আইটেম বিক্রয়) POS/Checkout > Functions > Reports ব্যবহার করুন। এটাও খেয়াল রাখুন: চেকআউট স্ক্রিনে Discount $ পরিমাণ লিখে Tab চাপলে বা অন্য কোথাও ক্লিক করলে (Enter না চেপে) স্ক্রিনের Subtotal/Tax/Total সংখ্যাগুলো অপরিবর্তিত দেখায় — PAY চাপলে গ্রাহককে সঠিক ছাড়যুক্ত পরিমাণই চার্জ করা হয়, কিন্তু ততক্ষণ পর্যন্ত স্ক্রিনে ভুল সংখ্যা দেখাতে পারে, তাই গ্রাহককে দাম বলার আগে ছাড় লেখার সাথে সাথেই Enter চেপে আসল টোটাল দেখে নিন।"},
        {"Employees কীভাবে কাজ করে?",
         "Employees (বাম সাইডবার) হলো স্টাফ ডিরেক্টরি — সবার Name, Position, Phone, Email, Hourly Rate, ও Active স্ট্যাটাসের একটি টেবিল। নতুন রেকর্ড তৈরি করতে Add Employee চাপুন, অথবা একটি সারি বেছে নিয়ে Edit Selected চাপুন; Full Name আবশ্যক, আর Phone/Email/Hourly Rate সেভ করার আগে সঠিক ফরম্যাটের জন্য যাচাই করা হয়। একটি সারি বেছে নিয়ে Create Login for Selected চাপলে সেই কর্মচারীর জন্য একটি সিস্টেম অ্যাকাউন্ট (ইউজারনেম, সাময়িক পাসওয়ার্ড, ও CASHIER/MANAGER/ADMIN রোল) তৈরি হয় যাতে তিনি লগইন করতে পারেন। গুরুত্বপূর্ণ: ভুল Phone, Email, বা Hourly Rate লিখে OK চাপলে পুরো Add/Edit ফর্মটি বন্ধ হয়ে যায় এবং আপনার টাইপ করা সব তথ্য হারিয়ে যায় — আপনাকে খালি ফর্ম থেকে আবার শুরু করতে হয়, তাই OK চাপার আগে প্রতিটি ফিল্ড ভালোভাবে দেখে নিন। এছাড়া, Create Login for Selected কোনো কর্মচারীর আগে থেকেই লগইন আছে কিনা তা যাচাই করে না — ভিন্ন ইউজারনেম দিয়ে আবার চাপলে একই ব্যক্তির জন্য নিঃশব্দে দ্বিতীয় একটি আলাদা অ্যাকাউন্ট তৈরি হয়ে যায়, আর এই স্ক্রিন থেকে কোনো কর্মচারীর বিদ্যমান লগইন দেখা বা পরিচালনা করার কোনো উপায় নেই। কর্মচারী বা লগইনের জন্য অ্যাপে কোথাও কোনো Delete বাটন নেই — কাউকে সরানোর চেষ্টা না করে Edit ফর্মে Active আনচেক করুন।"},
        {"ছাড় কীভাবে প্রয়োগ করব?",
         "পেমেন্ট চাপার আগে কার্ট কলামের ছাড় $ বক্সে ছাড়ের পরিমাণ লিখুন।"},
        {"ডেলিভারি অর্ডার কীভাবে নেব?",
         "অর্ডার টাইপ পরিবর্তন করে DELIVERY করুন এবং জিজ্ঞাসা করলে ডেলিভারি ঠিকানা লিখুন।"},
        {"গিফট কার্ড কীভাবে রিডিম করব?",
         "পেমেন্ট চাপুন, তারপর গিফট কার্ড রিডিম-এ ট্যাপ করে গিফট কার্ড নম্বর লিখুন।"},
        {"অ্যাপের ভাষা কীভাবে পরিবর্তন করব?",
         "স্ক্রিনের উপরে ঘড়ির পাশে ভাষা বাটনে ট্যাপ করে আপনার ভাষা বেছে নিন।"},
        {"লয়্যালটি কাস্টমার কীভাবে যোগ করব?",
         "কার্ট কলামে + লয়্যালটি কাস্টমার-এ ট্যাপ করে গ্রাহকের নাম ও ফোন নম্বর দিন।"},
        {"অর্ডার কীভাবে বাতিল করব?",
         "কার্ট কলামে অর্ডার বাতিল, অথবা পেমেন্টস স্ক্রিনে সংরক্ষিত অর্ডার বাতিল-এ ট্যাপ করুন।"},
        {"আরও সাহায্যের জন্য কার সাথে যোগাযোগ করব?",
         "ফাংশন ট্যাবের সাপোর্ট বিভাগ ব্যবহার করে সাপোর্টে কল বা চ্যাট করুন।"},
    };

    private static final String[][] TOPICS_HI = {
        {"ऑर्डर में आइटम कैसे जोड़ें?",
         "किसी डिपार्टमेंट टैब (पेय, बेकरी आदि) पर टैप करें, फिर आइटम पर टैप करें। आकार, तापमान और ऐड-ऑन चुनें, फिर आइटम पूर्ण पर टैप करें।"},
        {"POS/Checkout: Beverages पेज कैसे काम करता है?",
         "Beverages टैब पर टैप करें, फिर दाईं ओर के सेक्शन (Coffee, Espresso, Teas, Refreshers, Frozen, Other Beverages) में से कोई एक चुनकर उस समूह की ड्रिंक्स देखें। किसी ड्रिंक पर टैप करने से कस्टमाइज़ स्क्रीन खुलती है: Size चुनें (हर आकार की अपनी कीमत जुड़ती है), Hot या Iced चुनें, और कोई भी Dairy/Sweetener, Flavor Swirl या Add-On मॉडिफायर (इनकी भी अपनी कीमत जुड़ती है)। आइटम पूर्ण पर टैप करने से यह बाईं ओर कार्ट में जुड़ जाता है — आइटम जोड़ते ही Subtotal, Tax और Total अपने आप अपडेट हो जाते हैं। ज़रूरत हो तो Discount $ राशि दर्ज करें, फिर भुगतान दबाकर Credit Card, CASH (पहले कीपैड पर ग्राहक द्वारा दी गई राशि दर्ज करें), या GC Redeem चुनकर बिक्री पूरी करें।"},
        {"POS/Checkout: Featured पेज कैसे काम करता है?",
         "Featured टैब पर टैप करें, फिर दाईं ओर के सेक्शन (New Arrivals, Fan Favorites, Limited Time Offers, Value Bundles) में से चुनकर वे ड्रिंक्स देखें — कस्टमाइज़ेशन, कार्ट और भुगतान ठीक Beverages की तरह ही काम करते हैं। साइडबार के नीचे मौजूद News & Promos बटन कोई ड्रिंक सूची नहीं है — इस पर टैप करने से इस महीने के प्रमोशन का एक सूचनात्मक बोर्ड खुलता है (सिर्फ़ देखने के लिए); ऑर्डर पर वापस जाने के लिए साइडबार के किसी अन्य सेक्शन पर टैप करें।"},
        {"POS/Checkout: Bakery पेज कैसे काम करता है?",
         "Bakery टैब पर टैप करें, फिर दाईं ओर के सेक्शन (Sweet Treats, Grab & Go, Bagels & Muffins, Donuts & Donut Holes) में से चुनकर कुकीज़, पेस्ट्री, केक आदि देखें — कार्ट, छूट और भुगतान ठीक Beverages की तरह ही काम करते हैं। ध्यान दें: हर आइटम (बेकरी आइटम सहित) की कस्टमाइज़ स्क्रीन पर अभी भी Temperature और पेय-शैली के मॉडिफायर (Dairy/Sweetener, Flavor Swirl, Add-On) दिखते हैं — कुकी या डोनट जैसी चीज़ों के लिए इन्हें नज़रअंदाज़ करना सुरक्षित है; जान-बूझकर टैप न करने पर ये ऑर्डर को प्रभावित नहीं करेंगे।"},
        {"POS/Checkout: Sandwiches पेज कैसे काम करता है?",
         "Sandwiches टैब पर टैप करें, फिर दाईं ओर के सेक्शन (Breakfast Sandwiches, Specialty Sandwiches, Wraps & Bowls, Sides & Bites, Snacking) में से चुनकर वे आइटम देखें — कार्ट, छूट और भुगतान ठीक Beverages की तरह ही काम करते हैं। ध्यान दें: हर आइटम (सैंडविच सहित) की कस्टमाइज़ स्क्रीन पर अभी भी Temperature और पेय-शैली के मॉडिफायर (Dairy/Sweetener, Flavor Swirl, Add-On) दिखते हैं — इन्हें नज़रअंदाज़ करना सुरक्षित है; जान-बूझकर टैप न करने पर ये ऑर्डर को प्रभावित नहीं करेंगे।"},
        {"POS/Checkout: Retail पेज कैसे काम करता है?",
         "Retail टैब पर टैप करें, फिर दाईं ओर के सेक्शन (Coffee & Tea, Mugs & Drinkware, Gift Sets & Holiday, Grab & Go Treats, Gift Cards & More) में से चुनकर वे उत्पाद देखें — कार्ट और CASH/Credit Card भुगतान ठीक Beverages की तरह ही काम करते हैं। महत्वपूर्ण: GC Redeem अभी तक बिक्री पूरी नहीं करता — गिफ्ट कार्ड नंबर डालने पर एक पुष्टिकरण संदेश दिखाता है लेकिन ऑर्डर पूरा नहीं करता, इसलिए गिफ्ट कार्ड बेचते समय हमेशा Credit Card या CASH से भुगतान पूरा करें। साथ ही, Gift Card आइटम बेचते समय Size को डिफ़ॉल्ट (Small) पर रहने दें और किसी मॉडिफायर पर टैप न करें, क्योंकि कस्टमाइज़ स्क्रीन अभी तक गिफ्ट कार्ड को उसके छपे हुए मूल्य पर लॉक नहीं करती।"},
        {"POS/Checkout: Local पेज कैसे काम करता है?",
         "Local टैब पर टैप करें, फिर दाईं ओर के सेक्शन (Local Items, Catering Menu, Charity, Deposits & Pup Cups) में से चुनकर वे उत्पाद देखें — कार्ट और CASH/Credit Card भुगतान ठीक Beverages की तरह ही काम करते हैं। महत्वपूर्ण: Charity Donation और Reusable Bag Deposit आइटम के लिए Size को डिफ़ॉल्ट (Small) पर रहने दें और किसी मॉडिफायर पर टैप न करें — बड़ा आकार चुनने से वह कीमत बताई गई दान/डिपॉज़िट राशि पर जुड़ जाती है (जैसे एक \"$5\" दान चुपचाप $6.00 हो सकता है)। यह भी ध्यान रखें कि दान और बैग डिपॉज़िट सहित हर आइटम पर स्वचालित रूप से टैक्स लगता है; अगर कोई दान या डिपॉज़िट टैक्स-मुक्त होना चाहिए, तो उस बिक्री को पूरा करने से पहले भुगतान स्क्रीन पर Tax Exempt बटन का उपयोग करें।"},
        {"POS/Checkout: Functions पेज कैसे काम करता है?",
         "Functions टैब पर मेनू नहीं, बल्कि मैनेजर/कैशियर टूल्स हैं — दाईं ओर के समूह में से चुनें (Manager, Daily Shift Functions, Reports, All Open Checks, Phone Orders, DT Orders, OTG Orders, Order Confirm Board, SUPPORT) जहाँ टिल/सेफ काउंट, प्राइस ओवरराइड, रिफंड, रिपोर्ट और ऑर्डर कतारों के लिए असली, काम करने वाले बटन हैं; यहाँ कुछ भी कार्ट में नहीं जुड़ता। महत्वपूर्ण: इस बिल्ड में अभी किसी भी बटन को स्टाफ की भूमिका के अनुसार सीमित नहीं किया गया है — कोई भी साइन-इन किया हुआ उपयोगकर्ता अभी Menu Item Price Override, Transaction Return, Manual Credit Entry, और Close Application जैसी संवेदनशील कार्रवाइयों तक पहुँच सकता है, इसलिए फ़िलहाल इस टैब को केवल-मैनेजर मानें और टर्मिनल बंद करने का इरादा न हो तो Close Application पर टैप न करें।"},
        {"Menu Management कैसे काम करता है?",
         "Menu Management (बाईं साइडबार) मेनू आइटम जोड़ने या संपादित करने की जगह है, जो POS/Checkout टैब से अलग है। कोई आइटम चुनकर Edit Selected पर टैप करें ताकि उसकी Category, Name, Price, Cost या Active स्थिति बदल सकें, या नया आइटम बनाने के लिए Add Item पर टैप करें। महत्वपूर्ण: नया आइटम जोड़ते समय Category सूची में डिपार्टमेंट टैब (जैसे \"Featured\" या \"Beverages\") और असली उप-श्रेणियाँ (जैसे \"Coffee\" या \"New Arrivals\") बिना किसी भेद के एक साथ मिली होती हैं, और डिफ़ॉल्ट रूप से एक डिपार्टमेंट चुना रहता है — अगर आप किसी आइटम को असली उप-श्रेणी की बजाय डिपार्टमेंट के अंतर्गत सेव करते हैं, तो वह POS/Checkout में कहीं नहीं दिखेगा और खोजा नहीं जा सकेगा। सेव करने से पहले हमेशा जाँच लें कि आपने असली उप-श्रेणी चुनी है। यह भी ध्यान दें कि ऐप में कहीं भी Delete बटन नहीं है — गलती से जोड़ा गया आइटम केवल निष्क्रिय (Edit Selected या Functions > Menu Item Availability से) किया जा सकता है, पूरी तरह हटाया नहीं जा सकता, इसलिए पहली बार में ही श्रेणी सावधानी से चुनें।"},
        {"Inventory कैसे काम करता है?",
         "Inventory (बाईं साइडबार) कच्चे माल के स्टॉक को ट्रैक करता है (जैसे Espresso Beans या Bread), जो Menu Management के मेनू आइटम से अलग है। चेकआउट पर जुड़ा हुआ आइटम बिकने पर स्टॉक अपने आप कम हो जाता है, और पर्याप्त स्टॉक न होने पर \"Insufficient stock\" संदेश के साथ बिक्री रोक दी जाती है। कोई सामग्री चुनकर Adjust Stock पर टैप करें और PURCHASE_IN, WASTE, या CORRECTION के लिए खुद स्टॉक जोड़ें या घटाएं। महत्वपूर्ण: ऐप यह जांच नहीं करता कि आपके द्वारा टाइप की गई राशि का चिन्ह आपके चुने गए Reason से मेल खाता है या नहीं (जैसे गलती से PURCHASE_IN के तहत ऋणात्मक संख्या टाइप हो सकती है), और यह स्टॉक को शून्य से नीचे जाने से भी नहीं रोकता — OK दबाने से पहले हमेशा राशि के चिन्ह और आकार को ध्यान से जांचें, क्योंकि यहाँ कोई Undo बटन नहीं है और इस स्क्रीन से पिछले समायोजन देखने का कोई तरीका नहीं है।"},
        {"Time Clock कैसे काम करता है?",
         "Time Clock (बाईं साइडबार) सेल्फ-सर्विस है — अपनी शिफ्ट शुरू करते समय Clock In पर टैप करें और खत्म करते समय Clock Out पर; बटन और स्थिति संदेश हमेशा दिखाते हैं कि आप वर्तमान में क्लॉक-इन हैं या नहीं। मैनेजर और एडमिन अपनी स्थिति के नीचे सभी के क्लॉक-इन की एक \"Recent punches\" तालिका भी देखते हैं। महत्वपूर्ण: यह बिल्ड आपको या किसी मैनेजर को भूली हुई क्लॉक-आउट ठीक करने नहीं देता — अगर आप Clock Out करना भूल जाते हैं, तो वह पूरी शिफ्ट Payroll में बिल्कुल भी नहीं गिनी जाएगी, और इसे बंद करने का एकमात्र तरीका है जब भी आपको याद आए तब Clock Out पर टैप करना, जो उस समय का समय रिकॉर्ड करेगा। जाने से पहले हमेशा क्लॉक-आउट करें, और भूल जाने पर तुरंत किसी मैनेजर को बताएं ताकि उन्हें पता हो कि उस शिफ्ट के घंटे पेरोल से छूट सकते हैं।"},
        {"Delivery Queue कैसे काम करता है?",
         "Delivery Queue (बाईं साइडबार) डिलीवरी ऑर्डर को एक तय जीवनचक्र में ट्रैक करता है — UNASSIGNED -> ASSIGNED -> PICKED_UP -> DELIVERED — जो ऑर्डर टाइप DELIVERY के साथ चेकआउट होते ही शुरू होता है। कोई पंक्ति चुनकर Assign to Driver... से बताएं कि इसे कौन ले जा रहा है, ड्राइवर के निकलते ही Mark Picked Up दबाएं, और डिलीवर होने पर Mark Delivered दबाएं; पूरे हो चुके ऑर्डर देखने के लिए \"Show completed deliveries\" चेक करें। महत्वपूर्ण: यह बिल्ड इन चरणों के क्रम को लागू नहीं करता — वर्तमान स्थिति चाहे जो हो, किसी भी पंक्ति पर Mark Delivered दबाया जा सकता है, जिससे बिना किसी ड्राइवर को सौंपे या पिकअप की पुष्टि किए ऑर्डर DELIVERED के रूप में चिह्नित हो सकता है। यह किसी पूर्ण हो चुकी डिलीवरी को बाद में बदलने से भी नहीं रोकता — पहले से PICKED_UP या DELIVERED हो चुके ऑर्डर पर Assign to Driver... का उपयोग करने से बिना किसी चेतावनी के स्थिति चुपचाप वापस ASSIGNED हो जाती है, जो असल में उसे अधूरा कर देती है। किसी भी एक्शन बटन को दबाने से पहले हमेशा ऑर्डर के मौजूदा Status कॉलम की जांच करें, और जब तक यह ठीक न हो जाए, DELIVERED को अंतिम नहीं बल्कि अस्थायी मानें।"},
        {"Recipes कैसे काम करता है?",
         "Recipes (बाईं साइडबार) किसी भी मेनू आइटम के लिए आपकी चुनी हुई भाषा में क्रमांकित तैयारी चरण दिखाता है। ऊपर एक Menu Item और एक Language चुनें; कोई भी चरण पढ़ सकता है, लेकिन केवल मैनेजर और एडमिन को उन्हें बनाए रखने के लिए Add Step, Edit Selected, और Delete Selected बटन दिखते हैं। महत्वपूर्ण: कोई चरण हटाने से उसके बाद वाले चरणों की पुनः क्रमांकन नहीं होती, इसलिए कुछ हटाने के बाद कोई रेसिपी स्थायी रूप से \"Step 1, Step 3\" दिखा सकती है, बिना Step 2 के — यह कोई डिस्प्ले त्रुटि नहीं है। साथ ही, Language बॉक्स फ्री-टेक्स्ट है और आप जो भी टाइप करें उसे स्वीकार कर लेता है (जैसे \"ENG\" को \"en\" से पूरी तरह अलग भाषा माना जाता है, बिना किसी चेतावनी के) — हमेशा सुनिश्चित करें कि आपने ऐप में कहीं और उपयोग किया गया वही भाषा कोड (en, bn, hi, es, fr) टाइप किया है, क्योंकि एक टाइपो चुपचाप ऐसे चरण बना देता है जो फिर कभी नहीं मिलेंगे।"},
        {"Reports कैसे काम करता है?",
         "Reports (बाईं साइडबार) एक रीयल-टाइम \"Today's Sales Summary\" है — Orders Today, Total Sales, Tax Collected, और Discounts Given, साथ ही एक Top Sellers Today तालिका, जो आपके पेज खोलने या Refresh दबाने पर आज के पूरे हुए ऑर्डर से फिर से गणना होती है। महत्वपूर्ण: यह पेज केवल आज का डेटा ही दिखाता है — यहां से कल या किसी दिनांक-सीमा को देखने का कोई तरीका नहीं है; लंबी अवधि की रिपोर्ट (जैसे 30-दिन की आइटम बिक्री) के लिए POS/Checkout > Functions > Reports का उपयोग करें। यह भी ध्यान दें: चेकआउट स्क्रीन पर Discount $ राशि टाइप करके Tab दबाने या कहीं और क्लिक करने पर (Enter दबाए बिना) स्क्रीन पर Subtotal/Tax/Total संख्याएं अपरिवर्तित दिखती हैं — PAY दबाने पर ग्राहक से सही छूट वाली राशि ही ली जाती है, लेकिन तब तक स्क्रीन पर गलत संख्या दिख सकती है, इसलिए ग्राहक को कीमत बताने से पहले छूट टाइप करते ही Enter दबाकर असली टोटल देख लें।"},
        {"Employees कैसे काम करता है?",
         "Employees (बाईं साइडबार) स्टाफ डायरेक्टरी है — हर किसी के Name, Position, Phone, Email, Hourly Rate, और Active स्थिति की एक तालिका। नया रिकॉर्ड बनाने के लिए Add Employee दबाएं, या कोई पंक्ति चुनकर Edit Selected दबाएं; Full Name आवश्यक है, और Phone/Email/Hourly Rate को सेव करने से पहले सही फॉर्मेट के लिए जांचा जाता है। कोई पंक्ति चुनकर Create Login for Selected दबाने पर उस कर्मचारी के लिए एक सिस्टम खाता (यूज़रनेम, अस्थायी पासवर्ड, और CASHIER/MANAGER/ADMIN भूमिका) बनता है ताकि वे साइन इन कर सकें। महत्वपूर्ण: यदि आप गलत Phone, Email, या Hourly Rate टाइप करके OK दबाते हैं, तो पूरा Add/Edit फॉर्म बंद हो जाता है और आपकी टाइप की गई सारी जानकारी खो जाती है — आपको खाली फॉर्म से फिर से शुरू करना होगा, इसलिए OK दबाने से पहले हर फील्ड को ध्यान से जांच लें। साथ ही, Create Login for Selected यह जांच नहीं करता कि किसी कर्मचारी का पहले से कोई लॉगिन है या नहीं — अलग यूज़रनेम के साथ दोबारा दबाने पर उसी व्यक्ति के लिए चुपचाप एक दूसरा, अलग खाता बन जाता है, और इस स्क्रीन से किसी कर्मचारी का मौजूदा लॉगिन देखने या प्रबंधित करने का कोई तरीका नहीं है। कर्मचारियों या लॉगिन के लिए ऐप में कहीं भी कोई Delete बटन नहीं है — किसी को हटाने की कोशिश करने के बजाय Edit फॉर्म में Active अनचेक करें।"},
        {"छूट कैसे लागू करें?",
         "भुगतान दबाने से पहले कार्ट कॉलम के छूट $ बॉक्स में छूट की राशि दर्ज करें।"},
        {"डिलीवरी ऑर्डर कैसे लें?",
         "ऑर्डर प्रकार को DELIVERY में बदलें और पूछे जाने पर डिलीवरी पता दर्ज करें।"},
        {"गिफ्ट कार्ड कैसे रिडीम करें?",
         "भुगतान दबाएं, फिर गिफ्ट कार्ड रिडीम पर टैप करें और गिफ्ट कार्ड नंबर दर्ज करें।"},
        {"ऐप की भाषा कैसे बदलें?",
         "स्क्रीन के ऊपर घड़ी के बगल में भाषा बटन पर टैप करें और अपनी भाषा चुनें।"},
        {"लॉयल्टी ग्राहक कैसे पंजीकृत करें?",
         "कार्ट कॉलम में + लॉयल्टी ग्राहक पर टैप करें और ग्राहक का नाम व फ़ोन नंबर दर्ज करें।"},
        {"ऑर्डर कैसे रद्द करें?",
         "कार्ट कॉलम में ऑर्डर रद्द करें, या भुगतान स्क्रीन पर सहेजा गया ऑर्डर रद्द करें पर टैप करें।"},
        {"अधिक सहायता के लिए किससे संपर्क करें?",
         "फ़ंक्शन टैब में सहायता केंद्र अनुभाग का उपयोग करके सहायता को कॉल या चैट करें।"},
    };

    private static final String[][] TOPICS_ES = {
        {"¿Cómo agrego un artículo a un pedido?",
         "Toca una pestaña de departamento (Bebidas, Panadería, etc.), luego toca el artículo. Elige tamaño, temperatura y extras, y luego toca Artículo listo."},
        {"¿Cómo funciona la página de pago de Bebidas?",
         "Toca la pestaña Bebidas, luego elige una sección a la derecha (Café, Espresso, Tés, Refrescos, Congelados, Otras Bebidas) para ver las bebidas de ese grupo. Al tocar una bebida se abre la pantalla de personalización: elige un Tamaño (cada tamaño agrega su propio precio), Caliente o Helado, y cualquier modificador de Lácteos/Endulzante, Toque de Sabor o Extra (cada uno también agrega su propio precio). Toca Artículo listo para agregarlo al carrito de la izquierda — el Subtotal, Impuesto y Total se actualizan automáticamente al agregar artículos. Ingresa un monto de Descuento $ si es necesario, luego presiona PAGAR y elige Tarjeta de Crédito, EFECTIVO (ingresa primero en el teclado el monto que entrega el cliente), o Canjear Tarjeta de Regalo para completar la venta."},
        {"¿Cómo funciona la página de pago de Featured (Destacados)?",
         "Toca la pestaña Featured, luego elige una sección a la derecha (New Arrivals, Fan Favorites, Limited Time Offers, Value Bundles) para ver esas bebidas — la personalización, el carrito y el pago funcionan igual que en Bebidas. El botón News & Promos al final de esa barra lateral no es una lista de bebidas — abre un panel de solo lectura con las promociones del mes; toca cualquier otra sección de la barra lateral para volver a pedir."},
        {"¿Cómo funciona la página de pago de Panadería (Bakery)?",
         "Toca la pestaña Bakery, luego elige una sección a la derecha (Sweet Treats, Grab & Go, Bagels & Muffins, Donuts & Donut Holes) para ver galletas, pastelería, pasteles y más — el carrito, el descuento y el pago funcionan igual que en Bebidas. Nota: la pantalla de personalización todavía muestra una fila de Temperatura y modificadores de estilo bebida (Lácteos/Endulzante, Toque de Sabor, Extra) para cada artículo, incluidos los de panadería — es seguro ignorarlos en artículos como galletas o donas; no afectarán el pedido a menos que los toques a propósito."},
        {"¿Cómo funciona la página de pago de Sandwiches?",
         "Toca la pestaña Sandwiches, luego elige una sección a la derecha (Breakfast Sandwiches, Specialty Sandwiches, Wraps & Bowls, Sides & Bites, Snacking) para ver esos artículos — el carrito, el descuento y el pago funcionan igual que en Bebidas. Nota: la pantalla de personalización todavía muestra una fila de Temperatura y modificadores de estilo bebida (Lácteos/Endulzante, Toque de Sabor, Extra) para cada artículo, incluidos los sándwiches — es seguro ignorarlos; no afectarán el pedido a menos que los toques a propósito."},
        {"¿Cómo funciona la página de pago de Retail (Tienda)?",
         "Toca la pestaña Retail, luego elige una sección a la derecha (Coffee & Tea, Mugs & Drinkware, Gift Sets & Holiday, Grab & Go Treats, Gift Cards & More) para ver esos productos — el carrito y el pago con CASH/Tarjeta de Crédito funcionan igual que en Bebidas. Importante: GC Redeem todavía no completa la venta — al ingresar un número de tarjeta de regalo muestra un mensaje de confirmación pero NO finaliza el pedido, así que siempre termina las ventas de tarjetas de regalo con Tarjeta de Crédito o EFECTIVO. Además, al vender un artículo de Gift Card, deja el Tamaño en el valor predeterminado (Small) y no toques ningún modificador, ya que la pantalla de personalización todavía no fija la tarjeta de regalo a su valor impreso."},
        {"¿Cómo funciona la página de pago de Local?",
         "Toca la pestaña Local, luego elige una sección a la derecha (Local Items, Catering Menu, Charity, Deposits & Pup Cups) para ver esos productos — el carrito y el pago con CASH/Tarjeta de Crédito funcionan igual que en Bebidas. Importante: para los artículos de Charity Donation y Reusable Bag Deposit, deja el Tamaño en el valor predeterminado (Small) y no toques ningún modificador — elegir un tamaño más grande suma su precio al monto indicado de la donación/depósito (por ejemplo, una donación de \"$5\" puede convertirse silenciosamente en $6.00). Ten en cuenta también que el impuesto se aplica automáticamente a todos los artículos, incluidas las donaciones y los depósitos de bolsas; si una donación o depósito debería estar exento de impuestos, usa el botón Tax Exempt en la pantalla de pagos antes de finalizar esa venta."},
        {"¿Cómo funciona la página de pago de Functions?",
         "La pestaña Functions no tiene un menú, sino herramientas de gerente/cajero — elige un grupo a la derecha (Manager, Daily Shift Functions, Reports, All Open Checks, Phone Orders, DT Orders, OTG Orders, Order Confirm Board, SUPPORT) para ver botones reales y funcionales para conteo de caja/caja fuerte, anulación de precios, reembolsos, informes y colas de pedidos; nada aquí se agrega al carrito. Importante: esta versión todavía no restringe ninguno de estos botones según el rol del personal — cualquier usuario que haya iniciado sesión puede acceder a acciones sensibles como Menu Item Price Override, Transaction Return, Manual Credit Entry y Close Application, así que por ahora trata esta pestaña como exclusiva para gerentes y evita tocar Close Application a menos que quieras apagar la terminal."},
        {"¿Cómo funciona Menu Management?",
         "Menu Management (barra lateral izquierda) es donde agregas o editas artículos del menú, separado de las pestañas de POS/Checkout. Selecciona un artículo y toca Edit Selected para cambiar su Categoría, Nombre, Precio, Costo o estado Activo, o toca Add Item para crear uno nuevo. Importante: al agregar un artículo nuevo, la lista de Categoría mezcla pestañas de departamento (como \"Featured\" o \"Beverages\") con subcategorías reales (como \"Coffee\" o \"New Arrivals\") sin ninguna distinción, y un departamento queda seleccionado por defecto — si guardas un artículo bajo un departamento en lugar de una subcategoría real, no aparecerá en ninguna parte de POS/Checkout y no podrá encontrarse. Verifica siempre que hayas elegido una subcategoría real antes de guardar. Ten en cuenta también que no existe un botón Delete en ninguna parte de la aplicación — un artículo agregado por error solo puede desactivarse (con Edit Selected o Functions > Menu Item Availability), nunca eliminarse por completo, así que elige la categoría con cuidado desde el principio."},
        {"¿Cómo funciona Inventory?",
         "Inventory (barra lateral izquierda) rastrea el stock de ingredientes crudos (como Espresso Beans o Bread), separado de los artículos del menú de Menu Management. El stock baja automáticamente cuando se vende un artículo vinculado en el pago, y la venta se bloquea con un mensaje de \"Insufficient stock\" si no hay suficiente disponible. Selecciona un ingrediente y toca Adjust Stock para agregar o quitar stock tú mismo por PURCHASE_IN, WASTE o CORRECTION. Importante: la aplicación no verifica que el monto que escribes coincida con el Reason que elegiste (por ejemplo, podrías escribir un número negativo por error bajo PURCHASE_IN), y tampoco impide que el stock baje de cero — siempre verifica el signo y el tamaño del ajuste antes de presionar OK, ya que no hay botón Deshacer ni forma de ver ajustes anteriores desde esta pantalla."},
        {"¿Cómo funciona Time Clock?",
         "Time Clock (barra lateral izquierda) es de autoservicio — toca Clock In cuando empiezas tu turno y Clock Out cuando terminas; el botón y el mensaje de estado siempre reflejan si actualmente tienes el turno marcado. Los gerentes y administradores además ven una tabla de \"Recent punches\" con las entradas de todos debajo de su propio estado. Importante: esta versión no te permite a ti ni a un gerente corregir un Clock Out olvidado — si olvidas tocar Clock Out, ese turno completo no se contará en absoluto en Payroll, y la única forma de cerrarlo es tocar Clock Out cuando lo recuerdes, lo cual registrará la hora exacta de ese momento. Siempre marca tu salida antes de irte, y avisa de inmediato a un gerente si lo olvidas, para que sepan que las horas de ese turno podrían faltar en la nómina."},
        {"¿Cómo funciona Delivery Queue?",
         "Delivery Queue (barra lateral izquierda) rastrea los pedidos de entrega a través de un ciclo de vida documentado — UNASSIGNED -> ASSIGNED -> PICKED_UP -> DELIVERED — que comienza en el momento en que un pedido se paga con el tipo de orden DELIVERY. Selecciona una fila y usa Assign to Driver... para indicar quién lo llevará, Mark Picked Up una vez que haya salido con él, y Mark Delivered una vez entregado; marca \"Show completed deliveries\" para ver también los pedidos terminados. Importante: esta versión no impone el orden de esos pasos — se puede presionar Mark Delivered en cualquier fila sin importar su estado actual, por lo que un pedido puede marcarse como DELIVERED sin que se haya asignado nunca un conductor ni confirmado la recogida. Tampoco protege una entrega ya completada de ser modificada después — usar Assign to Driver... en un pedido ya en PICKED_UP o DELIVERED restablece silenciosamente su estado a ASSIGNED sin ninguna advertencia, deshaciendo en la práctica su finalización. Verifica siempre la columna Status actual del pedido antes de presionar cualquier botón de acción, y trata DELIVERED como provisional, no definitivo, hasta que esto se corrija."},
        {"¿Cómo funciona Recipes?",
         "Recipes (barra lateral izquierda) muestra pasos de preparación numerados para cualquier artículo del menú, en el idioma que elijas. Elige un Menu Item y un Language arriba; cualquiera puede leer los pasos, pero solo los gerentes y administradores ven los botones Add Step, Edit Selected y Delete Selected para mantenerlos. Importante: eliminar un paso no vuelve a numerar los que quedan después, así que una receta puede mostrar permanentemente \"Step 1, Step 3\" sin el Step 2 tras eliminar algo — esto no es un error de visualización. Además, el campo Language es de texto libre y acepta lo que escribas (por ejemplo, \"ENG\" se trata como un idioma completamente distinto de \"en\", sin ninguna advertencia) — verifica siempre que hayas escrito el mismo código de idioma (en, bn, hi, es, fr) que se usa en el resto de la aplicación, ya que un error de tipeo crea silenciosamente pasos que nadie volverá a encontrar."},
        {"¿Cómo funciona Reports?",
         "Reports (barra lateral izquierda) es un \"Resumen de ventas de hoy\" en tiempo real — Orders Today (pedidos de hoy), Total Sales, Tax Collected y Discounts Given, además de una tabla Top Sellers Today, todo recalculado a partir de los pedidos completados hoy cada vez que abres la página o presionas Refresh. Importante: esta página solo muestra el día de hoy — no hay forma de consultar el de ayer o un rango de fechas desde aquí; para informes de mayor alcance (como ventas de artículos de 30 días) usa POS/Checkout > Functions > Reports. Ten en cuenta también: en la pantalla de pago, escribir un monto en Discount $ y luego presionar Tab o hacer clic en otro lugar (en vez de Enter) deja los números de Subtotal/Tax/Total en pantalla sin cambios — al presionar PAGAR se cobra correctamente el monto con descuento, pero hasta ese momento la pantalla puede mostrar un total incorrecto, así que presiona Enter justo después de escribir un descuento para ver el total real antes de decirle el precio al cliente."},
        {"¿Cómo funciona Employees?",
         "Employees (barra lateral izquierda) es el directorio de personal — una tabla con Name, Position, Phone, Email, Hourly Rate y el estado Active de cada persona. Toca Add Employee para crear un registro nuevo, o selecciona una fila y toca Edit Selected para modificarla; el Full Name es obligatorio, y Phone/Email/Hourly Rate se verifican para asegurar un formato válido antes de guardar. Selecciona una fila y toca Create Login for Selected para crear una cuenta del sistema para ese empleado (usuario, contraseña temporal y un Role de CASHIER/MANAGER/ADMIN) para que pueda iniciar sesión. Importante: si escribes un Phone, Email u Hourly Rate inválido y presionas OK, todo el formulario de Add/Edit se cierra y se pierde todo lo que escribiste — debes empezar de nuevo desde un formulario vacío, así que revisa bien cada campo antes de presionar OK. Además, Create Login for Selected no verifica si un empleado ya tiene una cuenta — si vuelves a presionarlo con un usuario distinto, se crea en silencio una segunda cuenta separada para la misma persona, y esta pantalla no ofrece forma de ver o gestionar el inicio de sesión existente de un empleado. No existe un botón Delete para empleados ni para cuentas en ninguna parte de la aplicación — desmarca Active en el formulario de edición en lugar de intentar eliminar a alguien."},
        {"¿Cómo aplico un descuento?",
         "Ingresa el monto del descuento en el cuadro Descuento $ de la columna del carrito antes de presionar PAGAR."},
        {"¿Cómo tomo un pedido a domicilio?",
         "Cambia el Tipo de pedido a DELIVERY e ingresa la dirección de entrega cuando se te solicite."},
        {"¿Cómo canjeo una tarjeta de regalo?",
         "Presiona PAGAR, luego toca Canjear tarjeta de regalo e ingresa el número de la tarjeta."},
        {"¿Cómo cambio el idioma de la aplicación?",
         "Toca el botón de idioma junto al reloj en la parte superior de la pantalla y elige tu idioma."},
        {"¿Cómo registro a un cliente de lealtad?",
         "Toca + Cliente de lealtad en la columna del carrito e ingresa el nombre y teléfono del cliente."},
        {"¿Cómo cancelo un pedido?",
         "Toca Cancelar pedido en la columna del carrito, o Cancelar pedido guardado en la pantalla de pagos."},
        {"¿A quién contacto para más ayuda?",
         "Usa la sección SOPORTE en la pestaña Funciones para llamar o chatear con soporte."},
    };

    private static final String[][] TOPICS_FR = {
        {"Comment ajouter un article à une commande ?",
         "Appuyez sur un onglet de département (Boissons, Boulangerie, etc.), puis sur l'article. Choisissez la taille, la température et les suppléments, puis appuyez sur Article terminé."},
        {"Comment fonctionne la page de paiement Boissons ?",
         "Appuyez sur l'onglet Boissons, puis choisissez une section à droite (Café, Espresso, Thés, Rafraîchissements, Surgelés, Autres Boissons) pour voir les boissons de ce groupe. Toucher une boisson ouvre l'écran de personnalisation : choisissez une Taille (chaque taille ajoute son propre prix), Chaud ou Glacé, et tout modificateur Lait/Sucre, Arôme ou Supplément (chacun ajoute aussi son propre prix). Appuyez sur Article terminé pour l'ajouter au panier à gauche — le Sous-total, la Taxe et le Total se mettent à jour automatiquement à chaque ajout. Saisissez un montant de Remise $ si nécessaire, puis appuyez sur PAYER et choisissez Carte de crédit, ESPÈCES (saisissez d'abord au clavier le montant remis par le client), ou Échanger carte-cadeau pour finaliser la vente."},
        {"Comment fonctionne la page de paiement Featured (Vedettes) ?",
         "Appuyez sur l'onglet Featured, puis choisissez une section à droite (New Arrivals, Fan Favorites, Limited Time Offers, Value Bundles) pour voir ces boissons — la personnalisation, le panier et le paiement fonctionnent exactement comme pour Boissons. Le bouton News & Promos en bas de cette barre latérale n'est pas une liste de boissons — il ouvre un panneau de lecture seule des promotions du mois ; touchez n'importe quelle autre section de la barre latérale pour revenir à la commande."},
        {"Comment fonctionne la page de paiement Bakery (Boulangerie) ?",
         "Appuyez sur l'onglet Bakery, puis choisissez une section à droite (Sweet Treats, Grab & Go, Bagels & Muffins, Donuts & Donut Holes) pour voir cookies, pâtisseries, gâteaux, etc. — le panier, la remise et le paiement fonctionnent exactement comme pour Boissons. Remarque : l'écran de personnalisation affiche encore une ligne Température et des modificateurs de style boisson (Lait/Sucre, Arôme, Supplément) pour chaque article, y compris les articles de boulangerie — il est sans risque de les ignorer pour des articles comme les cookies ou les donuts ; ils n'affecteront pas la commande sauf si vous les touchez volontairement."},
        {"Comment fonctionne la page de paiement Sandwiches ?",
         "Appuyez sur l'onglet Sandwiches, puis choisissez une section à droite (Breakfast Sandwiches, Specialty Sandwiches, Wraps & Bowls, Sides & Bites, Snacking) pour voir ces articles — le panier, la remise et le paiement fonctionnent exactement comme pour Boissons. Remarque : l'écran de personnalisation affiche encore une ligne Température et des modificateurs de style boisson (Lait/Sucre, Arôme, Supplément) pour chaque article, y compris les sandwichs — il est sans risque de les ignorer ; ils n'affecteront pas la commande sauf si vous les touchez volontairement."},
        {"Comment fonctionne la page de paiement Retail (Boutique) ?",
         "Appuyez sur l'onglet Retail, puis choisissez une section à droite (Coffee & Tea, Mugs & Drinkware, Gift Sets & Holiday, Grab & Go Treats, Gift Cards & More) pour voir ces produits — le panier et le paiement CASH/Carte de crédit fonctionnent exactement comme pour Boissons. Important : GC Redeem ne finalise pas encore la vente — après avoir saisi un numéro de carte-cadeau, un message de confirmation s'affiche mais la commande n'est PAS terminée ; terminez donc toujours les ventes de cartes-cadeaux avec Carte de crédit ou ESPÈCES. De plus, lors de la vente d'un article Gift Card, laissez la Taille sur la valeur par défaut (Small) et ne touchez aucun modificateur, car l'écran de personnalisation ne verrouille pas encore la carte-cadeau à sa valeur imprimée."},
        {"Comment fonctionne la page de paiement Local ?",
         "Appuyez sur l'onglet Local, puis choisissez une section à droite (Local Items, Catering Menu, Charity, Deposits & Pup Cups) pour voir ces produits — le panier et le paiement CASH/Carte de crédit fonctionnent exactement comme pour Boissons. Important : pour les articles Charity Donation et Reusable Bag Deposit, laissez la Taille sur la valeur par défaut (Small) et ne touchez aucun modificateur — choisir une taille plus grande ajoute son prix au montant indiqué du don/dépôt (par exemple, un don de « 5 $ » peut silencieusement devenir 6,00 $). Notez aussi que la taxe est appliquée automatiquement à chaque article, y compris les dons et les dépôts de sac ; si un don ou un dépôt doit être exonéré de taxe, utilisez le bouton Tax Exempt sur l'écran des paiements avant de finaliser cette vente."},
        {"Comment fonctionne la page de paiement Functions ?",
         "L'onglet Functions ne contient pas de menu, mais des outils de gérant/caissier — choisissez un groupe à droite (Manager, Daily Shift Functions, Reports, All Open Checks, Phone Orders, DT Orders, OTG Orders, Order Confirm Board, SUPPORT) pour voir des boutons réels et fonctionnels pour le comptage de caisse/coffre, la modification de prix, les remboursements, les rapports et les files d'attente de commandes ; rien ici ne s'ajoute au panier. Important : cette version ne restreint encore aucun de ces boutons selon le rôle du personnel — tout utilisateur connecté peut actuellement accéder à des actions sensibles comme Menu Item Price Override, Transaction Return, Manual Credit Entry et Close Application ; considérez donc pour l'instant cet onglet comme réservé aux gérants et évitez de toucher Close Application sauf si vous voulez éteindre le terminal."},
        {"Comment fonctionne Menu Management ?",
         "Menu Management (barre latérale gauche) est l'endroit où vous ajoutez ou modifiez des articles du menu, séparé des onglets POS/Checkout. Sélectionnez un article et appuyez sur Edit Selected pour changer sa Catégorie, son Nom, son Prix, son Coût ou son statut Actif, ou appuyez sur Add Item pour en créer un nouveau. Important : lors de l'ajout d'un nouvel article, la liste des Catégories mélange les onglets de département (comme « Featured » ou « Beverages ») avec les vraies sous-catégories (comme « Coffee » ou « New Arrivals ») sans aucune distinction, et un département est sélectionné par défaut — si vous enregistrez un article sous un département au lieu d'une vraie sous-catégorie, il n'apparaîtra nulle part dans POS/Checkout et ne pourra pas être retrouvé. Vérifiez toujours que vous avez choisi une vraie sous-catégorie avant d'enregistrer. Notez aussi qu'il n'existe aucun bouton Delete dans l'application — un article ajouté par erreur ne peut être que désactivé (via Edit Selected ou Functions > Menu Item Availability), jamais complètement supprimé, choisissez donc la catégorie avec soin dès le départ."},
        {"Comment fonctionne Inventory ?",
         "Inventory (barre latérale gauche) suit le stock des ingrédients bruts (comme Espresso Beans ou Bread), séparé des articles du menu de Menu Management. Le stock diminue automatiquement lorsqu'un article lié est vendu au paiement, et la vente est bloquée avec un message \"Insufficient stock\" s'il n'y en a pas assez disponible. Sélectionnez un ingrédient et appuyez sur Adjust Stock pour ajouter ou retirer du stock vous-même pour PURCHASE_IN, WASTE ou CORRECTION. Important : l'application ne vérifie pas que le montant saisi correspond au Reason choisi (par exemple, vous pourriez taper un nombre négatif par erreur sous PURCHASE_IN), et elle n'empêche pas non plus le stock de descendre sous zéro — vérifiez toujours le signe et l'ampleur de l'ajustement avant d'appuyer sur OK, car il n'y a pas de bouton Annuler ni de moyen de consulter les ajustements précédents depuis cet écran."},
        {"Comment fonctionne Time Clock ?",
         "Time Clock (barre latérale gauche) est en libre-service — appuyez sur Clock In au début de votre service et sur Clock Out à la fin ; le bouton et le message d'état reflètent toujours si vous êtes actuellement pointé. Les gérants et administrateurs voient en plus un tableau \"Recent punches\" avec les pointages de tout le monde sous leur propre statut. Important : cette version ne vous permet pas, ni à un gérant, de corriger un Clock Out oublié — si vous oubliez d'appuyer sur Clock Out, ce service entier ne sera pas du tout comptabilisé dans Payroll, et la seule façon de le clôturer est d'appuyer sur Clock Out dès que vous vous en souvenez, ce qui enregistrera l'heure exacte de ce moment-là. Pointez toujours votre sortie avant de partir, et prévenez immédiatement un gérant si vous l'oubliez, afin qu'il sache que les heures de ce service pourraient manquer à la paie."},
        {"Comment fonctionne Delivery Queue ?",
         "Delivery Queue (barre latérale gauche) suit les commandes de livraison selon un cycle de vie documenté — UNASSIGNED -> ASSIGNED -> PICKED_UP -> DELIVERED — qui commence dès qu'une commande est payée avec le type DELIVERY. Sélectionnez une ligne et utilisez Assign to Driver... pour indiquer qui la prend en charge, Mark Picked Up une fois qu'elle est partie avec le livreur, et Mark Delivered une fois livrée ; cochez \"Show completed deliveries\" pour voir aussi les commandes terminées. Important : cette version n'impose pas l'ordre de ces étapes — Mark Delivered peut être cliqué sur n'importe quelle ligne quel que soit son statut actuel, si bien qu'une commande peut être marquée DELIVERED sans qu'aucun livreur n'ait jamais été assigné ni aucun retrait confirmé. Elle ne protège pas non plus une livraison terminée d'être modifiée ensuite — utiliser Assign to Driver... sur une commande déjà PICKED_UP ou DELIVERED réinitialise silencieusement son statut à ASSIGNED sans aucun avertissement, annulant en pratique sa finalisation. Vérifiez toujours la colonne Status actuelle de la commande avant de cliquer sur un bouton d'action, et considérez DELIVERED comme provisoire plutôt que définitif tant que cela n'est pas corrigé."},
        {"Comment fonctionne Recipes ?",
         "Recipes (barre latérale gauche) affiche des étapes de préparation numérotées pour n'importe quel article du menu, dans la langue de votre choix. Choisissez un Menu Item et une Language en haut ; tout le monde peut lire les étapes, mais seuls les gérants et administrateurs voient les boutons Add Step, Edit Selected et Delete Selected pour les gérer. Important : supprimer une étape ne renumérote pas celles qui suivent, donc une recette peut afficher en permanence « Step 1, Step 3 » sans Step 2 après une suppression — ce n'est pas une erreur d'affichage. De plus, le champ Language est en texte libre et accepte tout ce que vous tapez (par exemple, « ENG » est traité comme une langue totalement différente de « en », sans aucun avertissement) — vérifiez toujours que vous avez tapé le même code de langue (en, bn, hi, es, fr) utilisé ailleurs dans l'application, car une faute de frappe crée silencieusement des étapes que personne ne retrouvera jamais."},
        {"Comment fonctionne Reports ?",
         "Reports (barre latérale gauche) est un « résumé des ventes du jour » en temps réel — Orders Today, Total Sales, Tax Collected et Discounts Given, ainsi qu'un tableau Top Sellers Today, tous recalculés à partir des commandes du jour terminées à chaque ouverture de la page ou clic sur Refresh. Important : cette page n'affiche que le jour même — il n'y a aucun moyen de consulter hier ou une plage de dates depuis ici ; pour des rapports plus larges (comme les ventes d'articles sur 30 jours), utilisez POS/Checkout > Functions > Reports. Notez aussi : sur l'écran de paiement, taper un montant dans Discount $ puis appuyer sur Tab ou cliquer ailleurs (au lieu d'Entrée) laisse les nombres Subtotal/Tax/Total inchangés à l'écran — en appuyant sur PAYER, le client est bien facturé du montant réduit correct, mais l'écran peut afficher un total erroné jusque-là ; appuyez donc sur Entrée juste après avoir saisi une remise pour voir le vrai total avant d'annoncer un prix au client."},
        {"Comment fonctionne Employees ?",
         "Employees (barre latérale gauche) est l'annuaire du personnel — un tableau des Name, Position, Phone, Email, Hourly Rate et du statut Active de chacun. Appuyez sur Add Employee pour créer une nouvelle fiche, ou sélectionnez une ligne et appuyez sur Edit Selected pour la modifier ; le Full Name est obligatoire, et Phone/Email/Hourly Rate sont vérifiés pour un format valide avant l'enregistrement. Sélectionnez une ligne et appuyez sur Create Login for Selected pour créer un compte système pour cet employé (nom d'utilisateur, mot de passe temporaire et un Role CASHIER/MANAGER/ADMIN) afin qu'il puisse se connecter. Important : si vous saisissez un Phone, Email ou Hourly Rate invalide et appuyez sur OK, tout le formulaire Add/Edit se ferme et tout ce que vous avez tapé est perdu — vous devez recommencer depuis un formulaire vide, alors vérifiez bien chaque champ avant d'appuyer sur OK. De plus, Create Login for Selected ne vérifie pas si un employé possède déjà un compte — appuyer à nouveau dessus avec un nom d'utilisateur différent crée silencieusement un second compte distinct pour la même personne, et cet écran n'offre aucun moyen de voir ou de gérer le compte existant d'un employé. Il n'existe aucun bouton Delete pour les employés ou les comptes nulle part dans l'application — décochez Active dans le formulaire d'édition plutôt que d'essayer de supprimer quelqu'un."},
        {"Comment appliquer une remise ?",
         "Saisissez le montant de la remise dans la case Remise $ de la colonne du panier avant d'appuyer sur PAYER."},
        {"Comment prendre une commande en livraison ?",
         "Changez le Type de commande en DELIVERY et saisissez l'adresse de livraison lorsque demandé."},
        {"Comment échanger une carte-cadeau ?",
         "Appuyez sur PAYER, puis sur Échanger carte-cadeau et saisissez le numéro de la carte."},
        {"Comment changer la langue de l'application ?",
         "Appuyez sur le bouton de langue à côté de l'horloge en haut de l'écran et choisissez votre langue."},
        {"Comment enregistrer un client fidélité ?",
         "Appuyez sur + Client fidélité dans la colonne du panier et saisissez le nom et le téléphone du client."},
        {"Comment annuler une commande ?",
         "Appuyez sur Annuler la commande dans la colonne du panier, ou Annuler la commande enregistrée sur l'écran des paiements."},
        {"Qui contacter pour plus d'aide ?",
         "Utilisez la section ASSISTANCE de l'onglet Fonctions pour appeler ou discuter avec l'assistance."},
    };

    private final JPanel topicsPanel = new JPanel();
    private final JLabel titleLabel = new JLabel();
    private final JLabel pickerLabel = new JLabel();
    private final JButton closeBtn = new JButton();

    public HelpDialog(Frame owner) {
        super(owner, true);
        setLayout(new BorderLayout());
        setSize(620, 560);
        setLocationRelativeTo(owner);

        JPanel header = new JPanel(new BorderLayout());
        header.setBackground(UITheme.HEADER_BG);
        header.setBorder(BorderFactory.createEmptyBorder(14, 18, 14, 18));
        titleLabel.setForeground(Color.WHITE);
        titleLabel.setFont(titleLabel.getFont().deriveFont(Font.BOLD, 18f));
        header.add(titleLabel, BorderLayout.WEST);

        JPanel pickerRow = new JPanel(new FlowLayout(FlowLayout.RIGHT, 8, 0));
        pickerRow.setOpaque(false);
        pickerLabel.setForeground(Color.LIGHT_GRAY);
        JComboBox<I18n.Lang> langBox = new JComboBox<>(I18n.Lang.values());
        langBox.setSelectedItem(I18n.current());
        langBox.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                    boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof I18n.Lang) setText(((I18n.Lang) value).nativeName);
                return this;
            }
        });
        langBox.addActionListener(e -> {
            I18n.Lang selected = (I18n.Lang) langBox.getSelectedItem();
            I18n.setLanguage(selected);
            refreshText();
        });
        pickerRow.add(pickerLabel);
        pickerRow.add(langBox);
        header.add(pickerRow, BorderLayout.EAST);

        add(header, BorderLayout.NORTH);

        topicsPanel.setLayout(new BoxLayout(topicsPanel, BoxLayout.Y_AXIS));
        topicsPanel.setBackground(Color.WHITE);
        topicsPanel.setBorder(BorderFactory.createEmptyBorder(16, 18, 16, 18));
        JScrollPane scroll = new JScrollPane(topicsPanel);
        scroll.setBorder(null);
        add(scroll, BorderLayout.CENTER);

        JPanel footer = new JPanel(new FlowLayout(FlowLayout.RIGHT, 12, 10));
        closeBtn.addActionListener(e -> dispose());
        footer.add(closeBtn);
        add(footer, BorderLayout.SOUTH);

        refreshText();
    }

    private String[][] topicsForCurrentLanguage() {
        switch (I18n.current()) {
            case BN: return TOPICS_BN;
            case HI: return TOPICS_HI;
            case ES: return TOPICS_ES;
            case FR: return TOPICS_FR;
            default: return TOPICS_EN;
        }
    }

    private void refreshText() {
        setTitle(I18n.t("Help & Support"));
        titleLabel.setText(I18n.t("Help & Support"));
        pickerLabel.setText(I18n.t("Select language:"));
        closeBtn.setText(I18n.t("Close"));

        topicsPanel.removeAll();
        String[][] topics = topicsForCurrentLanguage();
        for (String[] qa : topics) {
            JLabel q = new JLabel("<html><b>" + qa[0] + "</b></html>");
            q.setAlignmentX(Component.LEFT_ALIGNMENT);
            q.setForeground(UITheme.SECTION_HEADER_COLOR);
            q.setBorder(BorderFactory.createEmptyBorder(10, 0, 4, 0));
            JLabel a = new JLabel("<html><div style='width:520px'>" + qa[1] + "</div></html>");
            a.setAlignmentX(Component.LEFT_ALIGNMENT);
            topicsPanel.add(q);
            topicsPanel.add(a);
        }
        topicsPanel.revalidate();
        topicsPanel.repaint();
    }
}
