-- Expands all five Sandwiches sub-tabs (Breakfast Sandwiches, Specialty Sandwiches,
-- Wraps & Bowls, Sides & Bites, Snacking) to 100+ items each. All item names are
-- original to this shop.
USE pos_system;

SET @dept_sandwiches = (SELECT id FROM categories WHERE name = 'Sandwiches' AND parent_id IS NULL);
SET @sub_breakfast = (SELECT id FROM categories WHERE name = 'Breakfast Sandwiches' AND parent_id = @dept_sandwiches);
SET @sub_specialty = (SELECT id FROM categories WHERE name = 'Specialty Sandwiches' AND parent_id = @dept_sandwiches);
SET @sub_wraps = (SELECT id FROM categories WHERE name = 'Wraps & Bowls' AND parent_id = @dept_sandwiches);
SET @sub_sides = (SELECT id FROM categories WHERE name = 'Sides & Bites' AND parent_id = @dept_sandwiches);
SET @sub_snacking = (SELECT id FROM categories WHERE name = 'Snacking' AND parent_id = @dept_sandwiches);

-- ---- Breakfast Sandwiches (+92) ----
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@sub_breakfast, 'Bacon Egg and Cheddar on English Muffin', 'Bacon, egg and cheddar cheese on a toasted english muffin', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Cheddar on Croissant', 'Bacon, egg and cheddar cheese on a toasted croissant', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Cheddar on Biscuit', 'Bacon, egg and cheddar cheese on a toasted biscuit', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Cheddar on Plain Bagel', 'Bacon, egg and cheddar cheese on a toasted plain bagel', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Cheddar on Flatbread', 'Bacon, egg and cheddar cheese on a toasted flatbread', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Cheddar on Ciabatta Roll', 'Bacon, egg and cheddar cheese on a toasted ciabatta roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Cheddar on Sourdough Toast', 'Bacon, egg and cheddar cheese on a toasted sourdough toast', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Cheddar on Multigrain Roll', 'Bacon, egg and cheddar cheese on a toasted multigrain roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Cheddar on Brioche Bun', 'Bacon, egg and cheddar cheese on a toasted brioche bun', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Cheddar on Kaiser Roll', 'Bacon, egg and cheddar cheese on a toasted kaiser roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and American on English Muffin', 'Bacon, egg and american cheese on a toasted english muffin', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and American on Croissant', 'Bacon, egg and american cheese on a toasted croissant', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and American on Biscuit', 'Bacon, egg and american cheese on a toasted biscuit', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and American on Plain Bagel', 'Bacon, egg and american cheese on a toasted plain bagel', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and American on Flatbread', 'Bacon, egg and american cheese on a toasted flatbread', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and American on Ciabatta Roll', 'Bacon, egg and american cheese on a toasted ciabatta roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and American on Sourdough Toast', 'Bacon, egg and american cheese on a toasted sourdough toast', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and American on Multigrain Roll', 'Bacon, egg and american cheese on a toasted multigrain roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and American on Brioche Bun', 'Bacon, egg and american cheese on a toasted brioche bun', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and American on Kaiser Roll', 'Bacon, egg and american cheese on a toasted kaiser roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Swiss on English Muffin', 'Bacon, egg and swiss cheese on a toasted english muffin', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Swiss on Croissant', 'Bacon, egg and swiss cheese on a toasted croissant', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Swiss on Biscuit', 'Bacon, egg and swiss cheese on a toasted biscuit', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Swiss on Plain Bagel', 'Bacon, egg and swiss cheese on a toasted plain bagel', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Swiss on Flatbread', 'Bacon, egg and swiss cheese on a toasted flatbread', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Swiss on Ciabatta Roll', 'Bacon, egg and swiss cheese on a toasted ciabatta roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Swiss on Sourdough Toast', 'Bacon, egg and swiss cheese on a toasted sourdough toast', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Swiss on Multigrain Roll', 'Bacon, egg and swiss cheese on a toasted multigrain roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Swiss on Brioche Bun', 'Bacon, egg and swiss cheese on a toasted brioche bun', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Swiss on Kaiser Roll', 'Bacon, egg and swiss cheese on a toasted kaiser roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Pepper Jack on English Muffin', 'Bacon, egg and pepper jack cheese on a toasted english muffin', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Pepper Jack on Croissant', 'Bacon, egg and pepper jack cheese on a toasted croissant', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Pepper Jack on Biscuit', 'Bacon, egg and pepper jack cheese on a toasted biscuit', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Pepper Jack on Plain Bagel', 'Bacon, egg and pepper jack cheese on a toasted plain bagel', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Pepper Jack on Flatbread', 'Bacon, egg and pepper jack cheese on a toasted flatbread', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Pepper Jack on Ciabatta Roll', 'Bacon, egg and pepper jack cheese on a toasted ciabatta roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Pepper Jack on Sourdough Toast', 'Bacon, egg and pepper jack cheese on a toasted sourdough toast', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Pepper Jack on Multigrain Roll', 'Bacon, egg and pepper jack cheese on a toasted multigrain roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Pepper Jack on Brioche Bun', 'Bacon, egg and pepper jack cheese on a toasted brioche bun', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Pepper Jack on Kaiser Roll', 'Bacon, egg and pepper jack cheese on a toasted kaiser roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Provolone on English Muffin', 'Bacon, egg and provolone cheese on a toasted english muffin', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Provolone on Croissant', 'Bacon, egg and provolone cheese on a toasted croissant', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Provolone on Biscuit', 'Bacon, egg and provolone cheese on a toasted biscuit', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Provolone on Plain Bagel', 'Bacon, egg and provolone cheese on a toasted plain bagel', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Provolone on Flatbread', 'Bacon, egg and provolone cheese on a toasted flatbread', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Provolone on Ciabatta Roll', 'Bacon, egg and provolone cheese on a toasted ciabatta roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Provolone on Sourdough Toast', 'Bacon, egg and provolone cheese on a toasted sourdough toast', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Provolone on Multigrain Roll', 'Bacon, egg and provolone cheese on a toasted multigrain roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Provolone on Brioche Bun', 'Bacon, egg and provolone cheese on a toasted brioche bun', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Bacon Egg and Provolone on Kaiser Roll', 'Bacon, egg and provolone cheese on a toasted kaiser roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Cheddar on English Muffin', 'Sausage, egg and cheddar cheese on a toasted english muffin', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Cheddar on Croissant', 'Sausage, egg and cheddar cheese on a toasted croissant', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Cheddar on Biscuit', 'Sausage, egg and cheddar cheese on a toasted biscuit', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Cheddar on Plain Bagel', 'Sausage, egg and cheddar cheese on a toasted plain bagel', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Cheddar on Flatbread', 'Sausage, egg and cheddar cheese on a toasted flatbread', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Cheddar on Ciabatta Roll', 'Sausage, egg and cheddar cheese on a toasted ciabatta roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Cheddar on Sourdough Toast', 'Sausage, egg and cheddar cheese on a toasted sourdough toast', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Cheddar on Multigrain Roll', 'Sausage, egg and cheddar cheese on a toasted multigrain roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Cheddar on Brioche Bun', 'Sausage, egg and cheddar cheese on a toasted brioche bun', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Cheddar on Kaiser Roll', 'Sausage, egg and cheddar cheese on a toasted kaiser roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and American on English Muffin', 'Sausage, egg and american cheese on a toasted english muffin', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and American on Croissant', 'Sausage, egg and american cheese on a toasted croissant', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and American on Biscuit', 'Sausage, egg and american cheese on a toasted biscuit', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and American on Plain Bagel', 'Sausage, egg and american cheese on a toasted plain bagel', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and American on Flatbread', 'Sausage, egg and american cheese on a toasted flatbread', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and American on Ciabatta Roll', 'Sausage, egg and american cheese on a toasted ciabatta roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and American on Sourdough Toast', 'Sausage, egg and american cheese on a toasted sourdough toast', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and American on Multigrain Roll', 'Sausage, egg and american cheese on a toasted multigrain roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and American on Brioche Bun', 'Sausage, egg and american cheese on a toasted brioche bun', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and American on Kaiser Roll', 'Sausage, egg and american cheese on a toasted kaiser roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Swiss on English Muffin', 'Sausage, egg and swiss cheese on a toasted english muffin', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Swiss on Croissant', 'Sausage, egg and swiss cheese on a toasted croissant', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Swiss on Biscuit', 'Sausage, egg and swiss cheese on a toasted biscuit', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Swiss on Plain Bagel', 'Sausage, egg and swiss cheese on a toasted plain bagel', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Swiss on Flatbread', 'Sausage, egg and swiss cheese on a toasted flatbread', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Swiss on Ciabatta Roll', 'Sausage, egg and swiss cheese on a toasted ciabatta roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Swiss on Sourdough Toast', 'Sausage, egg and swiss cheese on a toasted sourdough toast', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Swiss on Multigrain Roll', 'Sausage, egg and swiss cheese on a toasted multigrain roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Swiss on Brioche Bun', 'Sausage, egg and swiss cheese on a toasted brioche bun', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Swiss on Kaiser Roll', 'Sausage, egg and swiss cheese on a toasted kaiser roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Pepper Jack on English Muffin', 'Sausage, egg and pepper jack cheese on a toasted english muffin', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Pepper Jack on Croissant', 'Sausage, egg and pepper jack cheese on a toasted croissant', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Pepper Jack on Biscuit', 'Sausage, egg and pepper jack cheese on a toasted biscuit', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Pepper Jack on Plain Bagel', 'Sausage, egg and pepper jack cheese on a toasted plain bagel', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Pepper Jack on Flatbread', 'Sausage, egg and pepper jack cheese on a toasted flatbread', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Pepper Jack on Ciabatta Roll', 'Sausage, egg and pepper jack cheese on a toasted ciabatta roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Pepper Jack on Sourdough Toast', 'Sausage, egg and pepper jack cheese on a toasted sourdough toast', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Pepper Jack on Multigrain Roll', 'Sausage, egg and pepper jack cheese on a toasted multigrain roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Pepper Jack on Brioche Bun', 'Sausage, egg and pepper jack cheese on a toasted brioche bun', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Pepper Jack on Kaiser Roll', 'Sausage, egg and pepper jack cheese on a toasted kaiser roll', 6.09, 2.70, 'Specialty Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Provolone on English Muffin', 'Sausage, egg and provolone cheese on a toasted english muffin', 6.09, 2.70, 'Classic Breakfast'),
 (@sub_breakfast, 'Sausage Egg and Provolone on Croissant', 'Sausage, egg and provolone cheese on a toasted croissant', 6.09, 2.70, 'Classic Breakfast');

-- ---- Specialty Sandwiches (+86) ----
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@sub_specialty, 'Turkey and Swiss on White Bread', 'Turkey with swiss cheese on white bread', 7.59, 3.80, 'Deli Sandwiches'),
 (@sub_specialty, 'Turkey and Cheddar on Wheat Bread', 'Turkey with cheddar cheese on wheat bread', 7.59, 3.80, 'Deli Sandwiches'),
 (@sub_specialty, 'Turkey and Provolone on Rye Bread', 'Turkey with provolone cheese on rye bread', 7.59, 3.80, 'Deli Sandwiches'),
 (@sub_specialty, 'Turkey and American on Sourdough', 'Turkey with american cheese on sourdough', 7.59, 3.80, 'Deli Sandwiches'),
 (@sub_specialty, 'Turkey and Swiss on Ciabatta', 'Turkey with swiss cheese on ciabatta', 7.59, 3.80, 'Deli Sandwiches'),
 (@sub_specialty, 'Turkey and Cheddar on Multigrain', 'Turkey with cheddar cheese on multigrain', 7.59, 3.80, 'Deli Sandwiches'),
 (@sub_specialty, 'Turkey and Provolone on Kaiser Roll', 'Turkey with provolone cheese on kaiser roll', 7.59, 3.80, 'Deli Sandwiches'),
 (@sub_specialty, 'Turkey and American on Hoagie Roll', 'Turkey with american cheese on hoagie roll', 7.59, 3.80, 'Deli Sandwiches'),
 (@sub_specialty, 'Ham and Swiss on White Bread', 'Ham with swiss cheese on white bread', 7.49, 3.70, 'Deli Sandwiches'),
 (@sub_specialty, 'Ham and Cheddar on Wheat Bread', 'Ham with cheddar cheese on wheat bread', 7.49, 3.70, 'Deli Sandwiches'),
 (@sub_specialty, 'Ham and Provolone on Rye Bread', 'Ham with provolone cheese on rye bread', 7.49, 3.70, 'Deli Sandwiches'),
 (@sub_specialty, 'Ham and American on Sourdough', 'Ham with american cheese on sourdough', 7.49, 3.70, 'Deli Sandwiches'),
 (@sub_specialty, 'Ham and Swiss on Ciabatta', 'Ham with swiss cheese on ciabatta', 7.49, 3.70, 'Deli Sandwiches'),
 (@sub_specialty, 'Ham and Cheddar on Multigrain', 'Ham with cheddar cheese on multigrain', 7.49, 3.70, 'Deli Sandwiches'),
 (@sub_specialty, 'Ham and Provolone on Kaiser Roll', 'Ham with provolone cheese on kaiser roll', 7.49, 3.70, 'Deli Sandwiches'),
 (@sub_specialty, 'Ham and American on Hoagie Roll', 'Ham with american cheese on hoagie roll', 7.49, 3.70, 'Deli Sandwiches'),
 (@sub_specialty, 'Roast Beef and Swiss on White Bread', 'Roast Beef with swiss cheese on white bread', 7.89, 4.10, 'Deli Sandwiches'),
 (@sub_specialty, 'Roast Beef and Cheddar on Wheat Bread', 'Roast Beef with cheddar cheese on wheat bread', 7.89, 4.10, 'Deli Sandwiches'),
 (@sub_specialty, 'Roast Beef and Provolone on Rye Bread', 'Roast Beef with provolone cheese on rye bread', 7.89, 4.10, 'Deli Sandwiches'),
 (@sub_specialty, 'Roast Beef and American on Sourdough', 'Roast Beef with american cheese on sourdough', 7.89, 4.10, 'Deli Sandwiches'),
 (@sub_specialty, 'Roast Beef and Swiss on Ciabatta', 'Roast Beef with swiss cheese on ciabatta', 7.89, 4.10, 'Deli Sandwiches'),
 (@sub_specialty, 'Roast Beef and Cheddar on Multigrain', 'Roast Beef with cheddar cheese on multigrain', 7.89, 4.10, 'Deli Sandwiches'),
 (@sub_specialty, 'Roast Beef and Provolone on Kaiser Roll', 'Roast Beef with provolone cheese on kaiser roll', 7.89, 4.10, 'Deli Sandwiches'),
 (@sub_specialty, 'Roast Beef and American on Hoagie Roll', 'Roast Beef with american cheese on hoagie roll', 7.89, 4.10, 'Deli Sandwiches'),
 (@sub_specialty, 'Chicken Salad and Swiss on White Bread', 'Chicken Salad with swiss cheese on white bread', 7.69, 3.90, 'Deli Sandwiches'),
 (@sub_specialty, 'Chicken Salad and Cheddar on Wheat Bread', 'Chicken Salad with cheddar cheese on wheat bread', 7.69, 3.90, 'Deli Sandwiches'),
 (@sub_specialty, 'Chicken Salad and Provolone on Rye Bread', 'Chicken Salad with provolone cheese on rye bread', 7.69, 3.90, 'Deli Sandwiches'),
 (@sub_specialty, 'Chicken Salad and American on Sourdough', 'Chicken Salad with american cheese on sourdough', 7.69, 3.90, 'Deli Sandwiches'),
 (@sub_specialty, 'Chicken Salad and Swiss on Ciabatta', 'Chicken Salad with swiss cheese on ciabatta', 7.69, 3.90, 'Deli Sandwiches'),
 (@sub_specialty, 'Chicken Salad and Cheddar on Multigrain', 'Chicken Salad with cheddar cheese on multigrain', 7.69, 3.90, 'Deli Sandwiches'),
 (@sub_specialty, 'Turkey and Cheddar Melt', 'Grilled turkey and cheddar cheese melt on fresh bread', 7.69, 3.50, 'Grilled & Melts'),
 (@sub_specialty, 'Turkey and American Melt', 'Grilled turkey and american cheese melt on fresh bread', 7.69, 3.50, 'Grilled & Melts'),
 (@sub_specialty, 'Turkey and Swiss Melt', 'Grilled turkey and swiss cheese melt on fresh bread', 7.69, 3.50, 'Grilled & Melts'),
 (@sub_specialty, 'Turkey and Pepper Jack Melt', 'Grilled turkey and pepper jack cheese melt on fresh bread', 7.69, 3.50, 'Grilled & Melts'),
 (@sub_specialty, 'Turkey and Provolone Melt', 'Grilled turkey and provolone cheese melt on fresh bread', 7.69, 3.50, 'Grilled & Melts'),
 (@sub_specialty, 'Ham and Cheddar Melt', 'Grilled ham and cheddar cheese melt on fresh bread', 7.59, 3.40, 'Grilled & Melts'),
 (@sub_specialty, 'Ham and American Melt', 'Grilled ham and american cheese melt on fresh bread', 7.59, 3.40, 'Grilled & Melts'),
 (@sub_specialty, 'Ham and Swiss Melt', 'Grilled ham and swiss cheese melt on fresh bread', 7.59, 3.40, 'Grilled & Melts'),
 (@sub_specialty, 'Ham and Pepper Jack Melt', 'Grilled ham and pepper jack cheese melt on fresh bread', 7.59, 3.40, 'Grilled & Melts'),
 (@sub_specialty, 'Ham and Provolone Melt', 'Grilled ham and provolone cheese melt on fresh bread', 7.59, 3.40, 'Grilled & Melts'),
 (@sub_specialty, 'Steak and Cheddar Melt', 'Grilled steak and cheddar cheese melt on fresh bread', 8.29, 4.10, 'Grilled & Melts'),
 (@sub_specialty, 'Steak and American Melt', 'Grilled steak and american cheese melt on fresh bread', 8.29, 4.10, 'Grilled & Melts'),
 (@sub_specialty, 'Steak and Swiss Melt', 'Grilled steak and swiss cheese melt on fresh bread', 8.29, 4.10, 'Grilled & Melts'),
 (@sub_specialty, 'Steak and Pepper Jack Melt', 'Grilled steak and pepper jack cheese melt on fresh bread', 8.29, 4.10, 'Grilled & Melts'),
 (@sub_specialty, 'Steak and Provolone Melt', 'Grilled steak and provolone cheese melt on fresh bread', 8.29, 4.10, 'Grilled & Melts'),
 (@sub_specialty, 'Chicken and Cheddar Melt', 'Grilled chicken and cheddar cheese melt on fresh bread', 7.99, 3.80, 'Grilled & Melts'),
 (@sub_specialty, 'Chicken and American Melt', 'Grilled chicken and american cheese melt on fresh bread', 7.99, 3.80, 'Grilled & Melts'),
 (@sub_specialty, 'Chicken and Swiss Melt', 'Grilled chicken and swiss cheese melt on fresh bread', 7.99, 3.80, 'Grilled & Melts'),
 (@sub_specialty, 'Chicken and Pepper Jack Melt', 'Grilled chicken and pepper jack cheese melt on fresh bread', 7.99, 3.80, 'Grilled & Melts'),
 (@sub_specialty, 'Chicken and Provolone Melt', 'Grilled chicken and provolone cheese melt on fresh bread', 7.99, 3.80, 'Grilled & Melts'),
 (@sub_specialty, 'Bacon and Cheddar Melt', 'Grilled bacon and cheddar cheese melt on fresh bread', 7.39, 3.20, 'Grilled & Melts'),
 (@sub_specialty, 'Bacon and American Melt', 'Grilled bacon and american cheese melt on fresh bread', 7.39, 3.20, 'Grilled & Melts'),
 (@sub_specialty, 'Bacon and Swiss Melt', 'Grilled bacon and swiss cheese melt on fresh bread', 7.39, 3.20, 'Grilled & Melts'),
 (@sub_specialty, 'Bacon and Pepper Jack Melt', 'Grilled bacon and pepper jack cheese melt on fresh bread', 7.39, 3.20, 'Grilled & Melts'),
 (@sub_specialty, 'Bacon and Provolone Melt', 'Grilled bacon and provolone cheese melt on fresh bread', 7.39, 3.20, 'Grilled & Melts'),
 (@sub_specialty, 'Tuna and Cheddar Melt', 'Grilled tuna and cheddar cheese melt on fresh bread', 7.79, 3.60, 'Grilled & Melts'),
 (@sub_specialty, 'Tuna and American Melt', 'Grilled tuna and american cheese melt on fresh bread', 7.79, 3.60, 'Grilled & Melts'),
 (@sub_specialty, 'Tuna and Swiss Melt', 'Grilled tuna and swiss cheese melt on fresh bread', 7.79, 3.60, 'Grilled & Melts'),
 (@sub_specialty, 'Tuna and Pepper Jack Melt', 'Grilled tuna and pepper jack cheese melt on fresh bread', 7.79, 3.60, 'Grilled & Melts'),
 (@sub_specialty, 'Tuna and Provolone Melt', 'Grilled tuna and provolone cheese melt on fresh bread', 7.79, 3.60, 'Grilled & Melts'),
 (@sub_specialty, 'Chicken Pesto Panini', 'Chicken Pesto pressed panini-style on ciabatta', 9.39, 4.40, 'Paninis'),
 (@sub_specialty, 'Caprese Panini', 'Caprese pressed panini-style on ciabatta', 8.89, 3.90, 'Paninis'),
 (@sub_specialty, 'Turkey Club Panini', 'Turkey Club pressed panini-style on ciabatta', 9.19, 4.20, 'Paninis'),
 (@sub_specialty, 'Steak and Cheese Panini', 'Steak and Cheese pressed panini-style on ciabatta', 9.49, 4.50, 'Paninis'),
 (@sub_specialty, 'Ham and Brie Panini', 'Ham and Brie pressed panini-style on ciabatta', 9.39, 4.40, 'Paninis'),
 (@sub_specialty, 'Veggie and Mozzarella Panini', 'Veggie and Mozzarella pressed panini-style on ciabatta', 8.79, 3.80, 'Paninis'),
 (@sub_specialty, 'BBQ Chicken Panini', 'BBQ Chicken pressed panini-style on ciabatta', 9.19, 4.20, 'Paninis'),
 (@sub_specialty, 'Buffalo Chicken Panini', 'Buffalo Chicken pressed panini-style on ciabatta', 9.19, 4.20, 'Paninis'),
 (@sub_specialty, 'Meatball Panini', 'Meatball pressed panini-style on ciabatta', 9.09, 4.10, 'Paninis'),
 (@sub_specialty, 'Roast Beef and Cheddar Panini', 'Roast Beef and Cheddar pressed panini-style on ciabatta', 9.39, 4.40, 'Paninis'),
 (@sub_specialty, 'Southwest Chicken Panini', 'Southwest Chicken pressed panini-style on ciabatta', 9.19, 4.20, 'Paninis'),
 (@sub_specialty, 'Spinach Artichoke Panini', 'Spinach Artichoke pressed panini-style on ciabatta', 8.69, 3.70, 'Paninis'),
 (@sub_specialty, 'Chicken Pesto Panini on Sourdough', 'Chicken Pesto pressed panini-style on sourdough', 9.39, 4.40, 'Paninis'),
 (@sub_specialty, 'Caprese Panini on Multigrain', 'Caprese pressed panini-style on multigrain', 8.89, 3.90, 'Paninis'),
 (@sub_specialty, 'Turkey Club Panini on Rye', 'Turkey Club pressed panini-style on rye', 9.19, 4.20, 'Paninis'),
 (@sub_specialty, 'Steak and Cheese Panini on Focaccia', 'Steak and Cheese pressed panini-style on focaccia', 9.49, 4.50, 'Paninis'),
 (@sub_specialty, 'Ham and Brie Panini on Sourdough', 'Ham and Brie pressed panini-style on sourdough', 9.39, 4.40, 'Paninis'),
 (@sub_specialty, 'Veggie and Mozzarella Panini on Multigrain', 'Veggie and Mozzarella pressed panini-style on multigrain', 8.79, 3.80, 'Paninis'),
 (@sub_specialty, 'BBQ Chicken Panini on Rye', 'BBQ Chicken pressed panini-style on rye', 9.19, 4.20, 'Paninis'),
 (@sub_specialty, 'Buffalo Chicken Panini on Focaccia', 'Buffalo Chicken pressed panini-style on focaccia', 9.19, 4.20, 'Paninis'),
 (@sub_specialty, 'Meatball Panini on Sourdough', 'Meatball pressed panini-style on sourdough', 9.09, 4.10, 'Paninis'),
 (@sub_specialty, 'Roast Beef and Cheddar Panini on Multigrain', 'Roast Beef and Cheddar pressed panini-style on multigrain', 9.39, 4.40, 'Paninis'),
 (@sub_specialty, 'Southwest Chicken Panini on Rye', 'Southwest Chicken pressed panini-style on rye', 9.19, 4.20, 'Paninis'),
 (@sub_specialty, 'Spinach Artichoke Panini on Focaccia', 'Spinach Artichoke pressed panini-style on focaccia', 8.69, 3.70, 'Paninis'),
 (@sub_specialty, 'Toasted Chicken Pesto Panini on Sourdough', 'Toasted chicken pesto panini on sourdough', 9.39, 4.40, 'Paninis'),
 (@sub_specialty, 'Pressed Chicken Pesto Panini on Sourdough', 'Pressed chicken pesto panini on sourdough', 9.39, 4.40, 'Paninis');

-- ---- Wraps & Bowls (+90) ----
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@sub_wraps, 'Chicken Caesar Tortilla Wrap', 'Chicken Caesar wrapped in a tortilla wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Chicken Caesar Spinach Wrap', 'Chicken Caesar wrapped in a spinach wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Chicken Caesar Whole Wheat Wrap', 'Chicken Caesar wrapped in a whole wheat wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Buffalo Chicken Tortilla Wrap', 'Buffalo Chicken wrapped in a tortilla wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Buffalo Chicken Spinach Wrap', 'Buffalo Chicken wrapped in a spinach wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Buffalo Chicken Whole Wheat Wrap', 'Buffalo Chicken wrapped in a whole wheat wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Southwest Chicken Tortilla Wrap', 'Southwest Chicken wrapped in a tortilla wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Southwest Chicken Spinach Wrap', 'Southwest Chicken wrapped in a spinach wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Southwest Chicken Whole Wheat Wrap', 'Southwest Chicken wrapped in a whole wheat wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Turkey Bacon Tortilla Wrap', 'Turkey Bacon wrapped in a tortilla wrap', 7.49, 3.50, 'Wraps'),
 (@sub_wraps, 'Turkey Bacon Spinach Wrap', 'Turkey Bacon wrapped in a spinach wrap', 7.49, 3.50, 'Wraps'),
 (@sub_wraps, 'Turkey Bacon Whole Wheat Wrap', 'Turkey Bacon wrapped in a whole wheat wrap', 7.49, 3.50, 'Wraps'),
 (@sub_wraps, 'Steak and Cheese Wrap', 'Steak and Cheese wrapped in a wrap', 7.99, 4.00, 'Wraps'),
 (@sub_wraps, 'Steak and Cheese Tortilla Wrap', 'Steak and Cheese wrapped in a tortilla wrap', 7.99, 4.00, 'Wraps'),
 (@sub_wraps, 'Steak and Cheese Spinach Wrap', 'Steak and Cheese wrapped in a spinach wrap', 7.99, 4.00, 'Wraps'),
 (@sub_wraps, 'Steak and Cheese Whole Wheat Wrap', 'Steak and Cheese wrapped in a whole wheat wrap', 7.99, 4.00, 'Wraps'),
 (@sub_wraps, 'BBQ Chicken Wrap', 'BBQ Chicken wrapped in a wrap', 7.69, 3.70, 'Wraps'),
 (@sub_wraps, 'BBQ Chicken Tortilla Wrap', 'BBQ Chicken wrapped in a tortilla wrap', 7.69, 3.70, 'Wraps'),
 (@sub_wraps, 'BBQ Chicken Spinach Wrap', 'BBQ Chicken wrapped in a spinach wrap', 7.69, 3.70, 'Wraps'),
 (@sub_wraps, 'BBQ Chicken Whole Wheat Wrap', 'BBQ Chicken wrapped in a whole wheat wrap', 7.69, 3.70, 'Wraps'),
 (@sub_wraps, 'Chicken Bacon Ranch Wrap', 'Chicken Bacon Ranch wrapped in a wrap', 7.79, 3.80, 'Wraps'),
 (@sub_wraps, 'Chicken Bacon Ranch Tortilla Wrap', 'Chicken Bacon Ranch wrapped in a tortilla wrap', 7.79, 3.80, 'Wraps'),
 (@sub_wraps, 'Chicken Bacon Ranch Spinach Wrap', 'Chicken Bacon Ranch wrapped in a spinach wrap', 7.79, 3.80, 'Wraps'),
 (@sub_wraps, 'Chicken Bacon Ranch Whole Wheat Wrap', 'Chicken Bacon Ranch wrapped in a whole wheat wrap', 7.79, 3.80, 'Wraps'),
 (@sub_wraps, 'Veggie and Hummus Wrap', 'Veggie and Hummus wrapped in a wrap', 6.99, 3.00, 'Wraps'),
 (@sub_wraps, 'Veggie and Hummus Tortilla Wrap', 'Veggie and Hummus wrapped in a tortilla wrap', 6.99, 3.00, 'Wraps'),
 (@sub_wraps, 'Veggie and Hummus Spinach Wrap', 'Veggie and Hummus wrapped in a spinach wrap', 6.99, 3.00, 'Wraps'),
 (@sub_wraps, 'Veggie and Hummus Whole Wheat Wrap', 'Veggie and Hummus wrapped in a whole wheat wrap', 6.99, 3.00, 'Wraps'),
 (@sub_wraps, 'Falafel Wrap', 'Falafel wrapped in a wrap', 7.09, 3.10, 'Wraps'),
 (@sub_wraps, 'Falafel Tortilla Wrap', 'Falafel wrapped in a tortilla wrap', 7.09, 3.10, 'Wraps'),
 (@sub_wraps, 'Falafel Spinach Wrap', 'Falafel wrapped in a spinach wrap', 7.09, 3.10, 'Wraps'),
 (@sub_wraps, 'Falafel Whole Wheat Wrap', 'Falafel wrapped in a whole wheat wrap', 7.09, 3.10, 'Wraps'),
 (@sub_wraps, 'Mediterranean Veggie Wrap', 'Mediterranean Veggie wrapped in a wrap', 7.09, 3.10, 'Wraps'),
 (@sub_wraps, 'Mediterranean Veggie Tortilla Wrap', 'Mediterranean Veggie wrapped in a tortilla wrap', 7.09, 3.10, 'Wraps'),
 (@sub_wraps, 'Mediterranean Veggie Spinach Wrap', 'Mediterranean Veggie wrapped in a spinach wrap', 7.09, 3.10, 'Wraps'),
 (@sub_wraps, 'Mediterranean Veggie Whole Wheat Wrap', 'Mediterranean Veggie wrapped in a whole wheat wrap', 7.09, 3.10, 'Wraps'),
 (@sub_wraps, 'Ham and Swiss Wrap', 'Ham and Swiss wrapped in a wrap', 7.49, 3.50, 'Wraps'),
 (@sub_wraps, 'Ham and Swiss Tortilla Wrap', 'Ham and Swiss wrapped in a tortilla wrap', 7.49, 3.50, 'Wraps'),
 (@sub_wraps, 'Ham and Swiss Spinach Wrap', 'Ham and Swiss wrapped in a spinach wrap', 7.49, 3.50, 'Wraps'),
 (@sub_wraps, 'Ham and Swiss Whole Wheat Wrap', 'Ham and Swiss wrapped in a whole wheat wrap', 7.49, 3.50, 'Wraps'),
 (@sub_wraps, 'Tuna Salad Wrap', 'Tuna Salad wrapped in a wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Tuna Salad Tortilla Wrap', 'Tuna Salad wrapped in a tortilla wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Tuna Salad Spinach Wrap', 'Tuna Salad wrapped in a spinach wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Tuna Salad Whole Wheat Wrap', 'Tuna Salad wrapped in a whole wheat wrap', 7.59, 3.60, 'Wraps'),
 (@sub_wraps, 'Egg Salad Wrap', 'Egg Salad wrapped in a wrap', 7.09, 3.10, 'Wraps'),
 (@sub_wraps, 'Egg Salad Tortilla Wrap', 'Egg Salad wrapped in a tortilla wrap', 7.09, 3.10, 'Wraps'),
 (@sub_wraps, 'Egg White Veggie Rice Bowl', 'Egg White Veggie served over a rice bowl', 7.19, 3.20, 'Bowls'),
 (@sub_wraps, 'Egg White Veggie Quinoa Bowl', 'Egg White Veggie served over a quinoa bowl', 7.19, 3.20, 'Bowls'),
 (@sub_wraps, 'Egg White Veggie Power Bowl', 'Egg White Veggie served over a power bowl', 7.19, 3.20, 'Bowls'),
 (@sub_wraps, 'Egg White Veggie Grain Bowl', 'Egg White Veggie served over a grain bowl', 7.19, 3.20, 'Bowls'),
 (@sub_wraps, 'Protein Power Rice Bowl', 'Protein Power served over a rice bowl', 7.79, 3.80, 'Bowls'),
 (@sub_wraps, 'Protein Power Quinoa Bowl', 'Protein Power served over a quinoa bowl', 7.79, 3.80, 'Bowls'),
 (@sub_wraps, 'Protein Power Power Bowl', 'Protein Power served over a power bowl', 7.79, 3.80, 'Bowls'),
 (@sub_wraps, 'Protein Power Grain Bowl', 'Protein Power served over a grain bowl', 7.79, 3.80, 'Bowls'),
 (@sub_wraps, 'Breakfast Burrito Rice Bowl', 'Breakfast Burrito served over a rice bowl', 7.29, 3.30, 'Bowls'),
 (@sub_wraps, 'Breakfast Burrito Quinoa Bowl', 'Breakfast Burrito served over a quinoa bowl', 7.29, 3.30, 'Bowls'),
 (@sub_wraps, 'Breakfast Burrito Power Bowl', 'Breakfast Burrito served over a power bowl', 7.29, 3.30, 'Bowls'),
 (@sub_wraps, 'Breakfast Burrito Grain Bowl', 'Breakfast Burrito served over a grain bowl', 7.29, 3.30, 'Bowls'),
 (@sub_wraps, 'Steak and Egg Rice Bowl', 'Steak and Egg served over a rice bowl', 8.09, 4.10, 'Bowls'),
 (@sub_wraps, 'Steak and Egg Quinoa Bowl', 'Steak and Egg served over a quinoa bowl', 8.09, 4.10, 'Bowls'),
 (@sub_wraps, 'Steak and Egg Power Bowl', 'Steak and Egg served over a power bowl', 8.09, 4.10, 'Bowls'),
 (@sub_wraps, 'Steak and Egg Grain Bowl', 'Steak and Egg served over a grain bowl', 8.09, 4.10, 'Bowls'),
 (@sub_wraps, 'Grilled Chicken and Rice Rice Bowl', 'Grilled Chicken and Rice served over a rice bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'Grilled Chicken and Rice Quinoa Bowl', 'Grilled Chicken and Rice served over a quinoa bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'Grilled Chicken and Rice Power Bowl', 'Grilled Chicken and Rice served over a power bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'Grilled Chicken and Rice Grain Bowl', 'Grilled Chicken and Rice served over a grain bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'Quinoa Veggie Rice Bowl', 'Quinoa Veggie served over a rice bowl', 7.29, 3.30, 'Bowls'),
 (@sub_wraps, 'Quinoa Veggie Quinoa Bowl', 'Quinoa Veggie served over a quinoa bowl', 7.29, 3.30, 'Bowls'),
 (@sub_wraps, 'Quinoa Veggie Power Bowl', 'Quinoa Veggie served over a power bowl', 7.29, 3.30, 'Bowls'),
 (@sub_wraps, 'Quinoa Veggie Grain Bowl', 'Quinoa Veggie served over a grain bowl', 7.29, 3.30, 'Bowls'),
 (@sub_wraps, 'Southwest Steak Rice Bowl', 'Southwest Steak served over a rice bowl', 7.99, 4.00, 'Bowls'),
 (@sub_wraps, 'Southwest Steak Quinoa Bowl', 'Southwest Steak served over a quinoa bowl', 7.99, 4.00, 'Bowls'),
 (@sub_wraps, 'Southwest Steak Power Bowl', 'Southwest Steak served over a power bowl', 7.99, 4.00, 'Bowls'),
 (@sub_wraps, 'Southwest Steak Grain Bowl', 'Southwest Steak served over a grain bowl', 7.99, 4.00, 'Bowls'),
 (@sub_wraps, 'Buffalo Chicken Rice Bowl', 'Buffalo Chicken served over a rice bowl', 7.69, 3.70, 'Bowls'),
 (@sub_wraps, 'Buffalo Chicken Quinoa Bowl', 'Buffalo Chicken served over a quinoa bowl', 7.69, 3.70, 'Bowls'),
 (@sub_wraps, 'Buffalo Chicken Power Bowl', 'Buffalo Chicken served over a power bowl', 7.69, 3.70, 'Bowls'),
 (@sub_wraps, 'Buffalo Chicken Grain Bowl', 'Buffalo Chicken served over a grain bowl', 7.69, 3.70, 'Bowls'),
 (@sub_wraps, 'Mediterranean Chicken Rice Bowl', 'Mediterranean Chicken served over a rice bowl', 7.69, 3.70, 'Bowls'),
 (@sub_wraps, 'Mediterranean Chicken Quinoa Bowl', 'Mediterranean Chicken served over a quinoa bowl', 7.69, 3.70, 'Bowls'),
 (@sub_wraps, 'Mediterranean Chicken Power Bowl', 'Mediterranean Chicken served over a power bowl', 7.69, 3.70, 'Bowls'),
 (@sub_wraps, 'Mediterranean Chicken Grain Bowl', 'Mediterranean Chicken served over a grain bowl', 7.69, 3.70, 'Bowls'),
 (@sub_wraps, 'Teriyaki Chicken Rice Bowl', 'Teriyaki Chicken served over a rice bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'Teriyaki Chicken Quinoa Bowl', 'Teriyaki Chicken served over a quinoa bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'Teriyaki Chicken Power Bowl', 'Teriyaki Chicken served over a power bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'Teriyaki Chicken Grain Bowl', 'Teriyaki Chicken served over a grain bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'BBQ Chicken Rice Bowl', 'BBQ Chicken served over a rice bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'BBQ Chicken Quinoa Bowl', 'BBQ Chicken served over a quinoa bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'BBQ Chicken Power Bowl', 'BBQ Chicken served over a power bowl', 7.59, 3.60, 'Bowls'),
 (@sub_wraps, 'BBQ Chicken Grain Bowl', 'BBQ Chicken served over a grain bowl', 7.59, 3.60, 'Bowls');

-- ---- Sides & Bites (+94) ----
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@sub_sides, 'Garlic Herb Hash Browns', 'Crispy garlic herb seasoned hash browns', 3.44, 0.95, 'Hash Browns'),
 (@sub_sides, 'Bacon Hash Browns', 'Crispy bacon seasoned hash browns', 3.59, 1.00, 'Hash Browns'),
 (@sub_sides, 'Ranch Hash Browns', 'Crispy ranch seasoned hash browns', 2.99, 0.80, 'Hash Browns'),
 (@sub_sides, 'Buffalo Hash Browns', 'Crispy buffalo seasoned hash browns', 3.14, 0.85, 'Hash Browns'),
 (@sub_sides, 'BBQ Hash Browns', 'Crispy bbq seasoned hash browns', 3.29, 0.90, 'Hash Browns'),
 (@sub_sides, 'Southwest Hash Browns', 'Crispy southwest seasoned hash browns', 3.44, 0.95, 'Hash Browns'),
 (@sub_sides, 'Everything Seasoned Hash Browns', 'Crispy everything seasoned seasoned hash browns', 3.59, 1.00, 'Hash Browns'),
 (@sub_sides, 'Jalapeno Hash Browns', 'Crispy jalapeno seasoned hash browns', 2.99, 0.80, 'Hash Browns'),
 (@sub_sides, 'Chili Cheese Hash Browns', 'Crispy chili cheese seasoned hash browns', 3.14, 0.85, 'Hash Browns'),
 (@sub_sides, 'Loaded Hash Browns (6-pack)', 'Crispy loaded seasoned hash browns', 3.29, 0.90, 'Hash Browns'),
 (@sub_sides, 'Cheesy Hash Browns (6-pack)', 'Crispy cheesy seasoned hash browns', 3.44, 0.95, 'Hash Browns'),
 (@sub_sides, 'Spicy Hash Browns (6-pack)', 'Crispy spicy seasoned hash browns', 3.59, 1.00, 'Hash Browns'),
 (@sub_sides, 'Garlic Herb Hash Browns (6-pack)', 'Crispy garlic herb seasoned hash browns', 2.99, 0.80, 'Hash Browns'),
 (@sub_sides, 'Bacon Hash Browns (6-pack)', 'Crispy bacon seasoned hash browns', 3.14, 0.85, 'Hash Browns'),
 (@sub_sides, 'Ranch Hash Browns (6-pack)', 'Crispy ranch seasoned hash browns', 3.29, 0.90, 'Hash Browns'),
 (@sub_sides, 'Buffalo Hash Browns (6-pack)', 'Crispy buffalo seasoned hash browns', 3.44, 0.95, 'Hash Browns'),
 (@sub_sides, 'BBQ Hash Browns (6-pack)', 'Crispy bbq seasoned hash browns', 3.59, 1.00, 'Hash Browns'),
 (@sub_sides, 'Southwest Hash Browns (6-pack)', 'Crispy southwest seasoned hash browns', 2.99, 0.80, 'Hash Browns'),
 (@sub_sides, 'Everything Seasoned Hash Browns (6-pack)', 'Crispy everything seasoned seasoned hash browns', 3.14, 0.85, 'Hash Browns'),
 (@sub_sides, 'Jalapeno Hash Browns (6-pack)', 'Crispy jalapeno seasoned hash browns', 3.29, 0.90, 'Hash Browns'),
 (@sub_sides, 'Chili Cheese Hash Browns (6-pack)', 'Crispy chili cheese seasoned hash browns', 3.44, 0.95, 'Hash Browns'),
 (@sub_sides, 'Loaded Hash Browns (10-pack)', 'Crispy loaded seasoned hash browns', 3.59, 1.00, 'Hash Browns'),
 (@sub_sides, 'Cheesy Hash Browns (10-pack)', 'Crispy cheesy seasoned hash browns', 2.99, 0.80, 'Hash Browns'),
 (@sub_sides, 'Spicy Hash Browns (10-pack)', 'Crispy spicy seasoned hash browns', 3.14, 0.85, 'Hash Browns'),
 (@sub_sides, 'Egg and Cheese Bites (5-pack)', 'Bite-sized baked egg and cheese bites', 3.29, 1.00, 'Bites'),
 (@sub_sides, 'Bacon and Cheese Bites (5-pack)', 'Bite-sized baked bacon and cheese bites', 3.39, 1.05, 'Bites'),
 (@sub_sides, 'Veggie and Cheese Bites (5-pack)', 'Bite-sized baked veggie and cheese bites', 3.49, 1.10, 'Bites'),
 (@sub_sides, 'Sausage and Cheese Bites (5-pack)', 'Bite-sized baked sausage and cheese bites', 3.59, 1.15, 'Bites'),
 (@sub_sides, 'Ham and Cheese Bites (5-pack)', 'Bite-sized baked ham and cheese bites', 3.69, 1.20, 'Bites'),
 (@sub_sides, 'Spinach and Feta Bites (5-pack)', 'Bite-sized baked spinach and feta bites', 3.79, 1.25, 'Bites'),
 (@sub_sides, 'Broccoli and Cheddar Bites (5-pack)', 'Bite-sized baked broccoli and cheddar bites', 3.29, 1.00, 'Bites'),
 (@sub_sides, 'Buffalo Chicken Bites (5-pack)', 'Bite-sized baked buffalo chicken bites', 3.39, 1.05, 'Bites'),
 (@sub_sides, 'BBQ Chicken Bites (5-pack)', 'Bite-sized baked bbq chicken bites', 3.49, 1.10, 'Bites'),
 (@sub_sides, 'Pepperoni and Cheese Bites (5-pack)', 'Bite-sized baked pepperoni and cheese bites', 3.59, 1.15, 'Bites'),
 (@sub_sides, 'Jalapeno and Cheese Bites (5-pack)', 'Bite-sized baked jalapeno and cheese bites', 3.69, 1.20, 'Bites'),
 (@sub_sides, 'Three Cheese Bites (5-pack)', 'Bite-sized baked three cheese bites', 3.79, 1.25, 'Bites'),
 (@sub_sides, 'Egg and Cheese Bites (8-pack)', 'Bite-sized baked egg and cheese bites', 3.29, 1.00, 'Bites'),
 (@sub_sides, 'Bacon and Cheese Bites (8-pack)', 'Bite-sized baked bacon and cheese bites', 3.39, 1.05, 'Bites'),
 (@sub_sides, 'Veggie and Cheese Bites (8-pack)', 'Bite-sized baked veggie and cheese bites', 3.49, 1.10, 'Bites'),
 (@sub_sides, 'Sausage and Cheese Bites (8-pack)', 'Bite-sized baked sausage and cheese bites', 3.59, 1.15, 'Bites'),
 (@sub_sides, 'Ham and Cheese Bites (8-pack)', 'Bite-sized baked ham and cheese bites', 3.69, 1.20, 'Bites'),
 (@sub_sides, 'Spinach and Feta Bites (8-pack)', 'Bite-sized baked spinach and feta bites', 3.79, 1.25, 'Bites'),
 (@sub_sides, 'Broccoli and Cheddar Bites (8-pack)', 'Bite-sized baked broccoli and cheddar bites', 3.29, 1.00, 'Bites'),
 (@sub_sides, 'Buffalo Chicken Bites (8-pack)', 'Bite-sized baked buffalo chicken bites', 3.39, 1.05, 'Bites'),
 (@sub_sides, 'BBQ Chicken Bites (8-pack)', 'Bite-sized baked bbq chicken bites', 3.49, 1.10, 'Bites'),
 (@sub_sides, 'Pepperoni and Cheese Bites (8-pack)', 'Bite-sized baked pepperoni and cheese bites', 3.59, 1.15, 'Bites'),
 (@sub_sides, 'Jalapeno and Cheese Bites (8-pack)', 'Bite-sized baked jalapeno and cheese bites', 3.69, 1.20, 'Bites'),
 (@sub_sides, 'Three Cheese Bites (8-pack)', 'Bite-sized baked three cheese bites', 3.79, 1.25, 'Bites'),
 (@sub_sides, 'Side of Ham', 'A portion of ham', 3.74, 1.85, 'Sides'),
 (@sub_sides, 'Side of Sausage Gravy', 'A portion of sausage gravy', 3.89, 2.00, 'Sides'),
 (@sub_sides, 'Side of Grits', 'A portion of grits', 3.64, 1.75, 'Sides'),
 (@sub_sides, 'Side of Home Fries', 'A portion of home fries', 3.69, 1.80, 'Sides'),
 (@sub_sides, 'Side of Avocado', 'A portion of avocado', 3.99, 2.10, 'Sides'),
 (@sub_sides, 'Side of Tomato Slices', 'A portion of tomato slices', 3.39, 1.50, 'Sides'),
 (@sub_sides, 'Side of Applesauce', 'A portion of applesauce', 3.34, 1.45, 'Sides'),
 (@sub_sides, 'Side of Yogurt', 'A portion of yogurt', 3.69, 1.80, 'Sides'),
 (@sub_sides, 'Side of Bacon (Large)', 'A portion of bacon', 4.19, 2.00, 'Sides'),
 (@sub_sides, 'Side of Sausage (Large)', 'A portion of sausage', 4.19, 2.00, 'Sides'),
 (@sub_sides, 'Side of Fresh Fruit (Large)', 'A portion of fresh fruit', 4.29, 2.10, 'Sides'),
 (@sub_sides, 'Side of Turkey Bacon (Large)', 'A portion of turkey bacon', 4.24, 2.05, 'Sides'),
 (@sub_sides, 'Side of Ham (Large)', 'A portion of ham', 4.24, 2.05, 'Sides'),
 (@sub_sides, 'Side of Sausage Gravy (Large)', 'A portion of sausage gravy', 4.39, 2.20, 'Sides'),
 (@sub_sides, 'Side of Grits (Large)', 'A portion of grits', 4.14, 1.95, 'Sides'),
 (@sub_sides, 'Side of Home Fries (Large)', 'A portion of home fries', 4.19, 2.00, 'Sides'),
 (@sub_sides, 'Side of Avocado (Large)', 'A portion of avocado', 4.49, 2.30, 'Sides'),
 (@sub_sides, 'Side of Tomato Slices (Large)', 'A portion of tomato slices', 3.89, 1.70, 'Sides'),
 (@sub_sides, 'Side of Applesauce (Large)', 'A portion of applesauce', 3.84, 1.65, 'Sides'),
 (@sub_sides, 'Side of Yogurt (Large)', 'A portion of yogurt', 4.19, 2.00, 'Sides'),
 (@sub_sides, 'Side of Bacon (Extra Large)', 'A portion of bacon', 4.69, 2.20, 'Sides'),
 (@sub_sides, 'Side of Sausage (Extra Large)', 'A portion of sausage', 4.69, 2.20, 'Sides'),
 (@sub_sides, 'Side of Fresh Fruit (Extra Large)', 'A portion of fresh fruit', 4.79, 2.30, 'Sides'),
 (@sub_sides, 'Side of Turkey Bacon (Extra Large)', 'A portion of turkey bacon', 4.74, 2.25, 'Sides'),
 (@sub_sides, 'Small Classic Tater Tots', 'Small portion of classic seasoned crispy tater tots', 3.29, 0.90, 'Tater Tots'),
 (@sub_sides, 'Large Classic Tater Tots', 'Large portion of classic seasoned crispy tater tots', 4.24, 1.25, 'Tater Tots'),
 (@sub_sides, 'Small Loaded Tater Tots', 'Small portion of loaded seasoned crispy tater tots', 3.59, 1.00, 'Tater Tots'),
 (@sub_sides, 'Large Loaded Tater Tots', 'Large portion of loaded seasoned crispy tater tots', 4.54, 1.35, 'Tater Tots'),
 (@sub_sides, 'Small Cheesy Tater Tots', 'Small portion of cheesy seasoned crispy tater tots', 3.29, 0.90, 'Tater Tots'),
 (@sub_sides, 'Large Cheesy Tater Tots', 'Large portion of cheesy seasoned crispy tater tots', 4.24, 1.25, 'Tater Tots'),
 (@sub_sides, 'Small Spicy Tater Tots', 'Small portion of spicy seasoned crispy tater tots', 3.59, 1.00, 'Tater Tots'),
 (@sub_sides, 'Large Spicy Tater Tots', 'Large portion of spicy seasoned crispy tater tots', 4.54, 1.35, 'Tater Tots'),
 (@sub_sides, 'Small Bacon Tater Tots', 'Small portion of bacon seasoned crispy tater tots', 3.29, 0.90, 'Tater Tots'),
 (@sub_sides, 'Large Bacon Tater Tots', 'Large portion of bacon seasoned crispy tater tots', 4.24, 1.25, 'Tater Tots'),
 (@sub_sides, 'Small Ranch Tater Tots', 'Small portion of ranch seasoned crispy tater tots', 3.59, 1.00, 'Tater Tots'),
 (@sub_sides, 'Large Ranch Tater Tots', 'Large portion of ranch seasoned crispy tater tots', 4.54, 1.35, 'Tater Tots'),
 (@sub_sides, 'Ranch Dip', 'Individual portion of ranch dipping sauce', 0.79, 0.20, 'Dips'),
 (@sub_sides, 'Honey Mustard Dip', 'Individual portion of honey mustard dipping sauce', 0.79, 0.20, 'Dips'),
 (@sub_sides, 'BBQ Dip', 'Individual portion of bbq dipping sauce', 0.79, 0.20, 'Dips'),
 (@sub_sides, 'Cheese Sauce Dip', 'Individual portion of cheese sauce dipping sauce', 0.79, 0.20, 'Dips'),
 (@sub_sides, 'Marinara Dip', 'Individual portion of marinara dipping sauce', 0.79, 0.20, 'Dips'),
 (@sub_sides, 'Chipotle Mayo Dip', 'Individual portion of chipotle mayo dipping sauce', 0.79, 0.20, 'Dips'),
 (@sub_sides, 'Buffalo Dip', 'Individual portion of buffalo dipping sauce', 0.79, 0.20, 'Dips'),
 (@sub_sides, 'Ketchup Cup', 'Individual portion of ketchup cup dipping sauce', 0.79, 0.20, 'Dips'),
 (@sub_sides, 'Sriracha Mayo Dip', 'Individual portion of sriracha mayo dipping sauce', 0.79, 0.20, 'Dips'),
 (@sub_sides, 'Garlic Aioli Dip', 'Individual portion of garlic aioli dipping sauce', 0.79, 0.20, 'Dips');

-- ---- Snacking (+91) ----
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@sub_snacking, 'Spicy Mozzarella Sticks', 'Mozzarella Sticks tossed in spicy seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'BBQ Mozzarella Sticks', 'Mozzarella Sticks tossed in bbq seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan Mozzarella Sticks', 'Mozzarella Sticks tossed in garlic parmesan seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Buffalo Mozzarella Sticks', 'Mozzarella Sticks tossed in buffalo seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Honey Mustard Mozzarella Sticks', 'Mozzarella Sticks tossed in honey mustard seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Spicy Onion Rings', 'Onion Rings tossed in spicy seasoning', 5.49, 2.10, 'Snacks'),
 (@sub_snacking, 'BBQ Onion Rings', 'Onion Rings tossed in bbq seasoning', 5.49, 2.10, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan Onion Rings', 'Onion Rings tossed in garlic parmesan seasoning', 5.49, 2.10, 'Snacks'),
 (@sub_snacking, 'Buffalo Onion Rings', 'Onion Rings tossed in buffalo seasoning', 5.49, 2.10, 'Snacks'),
 (@sub_snacking, 'Honey Mustard Onion Rings', 'Onion Rings tossed in honey mustard seasoning', 5.49, 2.10, 'Snacks'),
 (@sub_snacking, 'Spicy French Fries', 'French Fries tossed in spicy seasoning', 5.09, 1.70, 'Snacks'),
 (@sub_snacking, 'BBQ French Fries', 'French Fries tossed in bbq seasoning', 5.09, 1.70, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan French Fries', 'French Fries tossed in garlic parmesan seasoning', 5.09, 1.70, 'Snacks'),
 (@sub_snacking, 'Buffalo French Fries', 'French Fries tossed in buffalo seasoning', 5.09, 1.70, 'Snacks'),
 (@sub_snacking, 'Honey Mustard French Fries', 'French Fries tossed in honey mustard seasoning', 5.09, 1.70, 'Snacks'),
 (@sub_snacking, 'Spicy Pretzel Poppers', 'Pretzel Poppers tossed in spicy seasoning', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'BBQ Pretzel Poppers', 'Pretzel Poppers tossed in bbq seasoning', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan Pretzel Poppers', 'Pretzel Poppers tossed in garlic parmesan seasoning', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'Buffalo Pretzel Poppers', 'Pretzel Poppers tossed in buffalo seasoning', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'Honey Mustard Pretzel Poppers', 'Pretzel Poppers tossed in honey mustard seasoning', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'Spicy Chicken Tenders', 'Chicken Tenders tossed in spicy seasoning', 6.39, 3.00, 'Snacks'),
 (@sub_snacking, 'BBQ Chicken Tenders', 'Chicken Tenders tossed in bbq seasoning', 6.39, 3.00, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan Chicken Tenders', 'Chicken Tenders tossed in garlic parmesan seasoning', 6.39, 3.00, 'Snacks'),
 (@sub_snacking, 'Buffalo Chicken Tenders', 'Chicken Tenders tossed in buffalo seasoning', 6.39, 3.00, 'Snacks'),
 (@sub_snacking, 'Honey Mustard Chicken Tenders', 'Chicken Tenders tossed in honey mustard seasoning', 6.39, 3.00, 'Snacks'),
 (@sub_snacking, 'Spicy Loaded Fries', 'Loaded Fries tossed in spicy seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'BBQ Loaded Fries', 'Loaded Fries tossed in bbq seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan Loaded Fries', 'Loaded Fries tossed in garlic parmesan seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Buffalo Loaded Fries', 'Loaded Fries tossed in buffalo seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Honey Mustard Loaded Fries', 'Loaded Fries tossed in honey mustard seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Jalapeno Poppers', 'Classic jalapeno poppers', 5.79, 2.40, 'Snacks'),
 (@sub_snacking, 'Spicy Jalapeno Poppers', 'Jalapeno Poppers tossed in spicy seasoning', 5.79, 2.40, 'Snacks'),
 (@sub_snacking, 'BBQ Jalapeno Poppers', 'Jalapeno Poppers tossed in bbq seasoning', 5.79, 2.40, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan Jalapeno Poppers', 'Jalapeno Poppers tossed in garlic parmesan seasoning', 5.79, 2.40, 'Snacks'),
 (@sub_snacking, 'Buffalo Jalapeno Poppers', 'Jalapeno Poppers tossed in buffalo seasoning', 5.79, 2.40, 'Snacks'),
 (@sub_snacking, 'Honey Mustard Jalapeno Poppers', 'Jalapeno Poppers tossed in honey mustard seasoning', 5.79, 2.40, 'Snacks'),
 (@sub_snacking, 'Fried Pickles', 'Classic fried pickles', 5.59, 2.20, 'Snacks'),
 (@sub_snacking, 'Spicy Fried Pickles', 'Fried Pickles tossed in spicy seasoning', 5.59, 2.20, 'Snacks'),
 (@sub_snacking, 'BBQ Fried Pickles', 'Fried Pickles tossed in bbq seasoning', 5.59, 2.20, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan Fried Pickles', 'Fried Pickles tossed in garlic parmesan seasoning', 5.59, 2.20, 'Snacks'),
 (@sub_snacking, 'Buffalo Fried Pickles', 'Fried Pickles tossed in buffalo seasoning', 5.59, 2.20, 'Snacks'),
 (@sub_snacking, 'Honey Mustard Fried Pickles', 'Fried Pickles tossed in honey mustard seasoning', 5.59, 2.20, 'Snacks'),
 (@sub_snacking, 'Zucchini Sticks', 'Classic zucchini sticks', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'Spicy Zucchini Sticks', 'Zucchini Sticks tossed in spicy seasoning', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'BBQ Zucchini Sticks', 'Zucchini Sticks tossed in bbq seasoning', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan Zucchini Sticks', 'Zucchini Sticks tossed in garlic parmesan seasoning', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'Buffalo Zucchini Sticks', 'Zucchini Sticks tossed in buffalo seasoning', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'Honey Mustard Zucchini Sticks', 'Zucchini Sticks tossed in honey mustard seasoning', 5.69, 2.30, 'Snacks'),
 (@sub_snacking, 'Fried Ravioli', 'Classic fried ravioli', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Spicy Fried Ravioli', 'Fried Ravioli tossed in spicy seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'BBQ Fried Ravioli', 'Fried Ravioli tossed in bbq seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan Fried Ravioli', 'Fried Ravioli tossed in garlic parmesan seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Buffalo Fried Ravioli', 'Fried Ravioli tossed in buffalo seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Honey Mustard Fried Ravioli', 'Fried Ravioli tossed in honey mustard seasoning', 5.89, 2.50, 'Snacks'),
 (@sub_snacking, 'Chicken Wings', 'Classic chicken wings', 6.59, 3.20, 'Snacks'),
 (@sub_snacking, 'Spicy Chicken Wings', 'Chicken Wings tossed in spicy seasoning', 6.59, 3.20, 'Snacks'),
 (@sub_snacking, 'BBQ Chicken Wings', 'Chicken Wings tossed in bbq seasoning', 6.59, 3.20, 'Snacks'),
 (@sub_snacking, 'Garlic Parmesan Chicken Wings', 'Chicken Wings tossed in garlic parmesan seasoning', 6.59, 3.20, 'Snacks'),
 (@sub_snacking, 'Buffalo Chicken Wings', 'Chicken Wings tossed in buffalo seasoning', 6.59, 3.20, 'Snacks'),
 (@sub_snacking, 'Honey Mustard Chicken Wings', 'Chicken Wings tossed in honey mustard seasoning', 6.59, 3.20, 'Snacks'),
 (@sub_snacking, 'Small Soft Pretzel', 'Small portion of soft pretzel', 3.99, 1.40, 'Sweet & Savory'),
 (@sub_snacking, 'Large Soft Pretzel', 'Large portion of soft pretzel', 5.19, 1.80, 'Sweet & Savory'),
 (@sub_snacking, 'Small Cheese Curds', 'Small portion of cheese curds', 4.84, 2.25, 'Sweet & Savory'),
 (@sub_snacking, 'Large Cheese Curds', 'Large portion of cheese curds', 6.04, 2.65, 'Sweet & Savory'),
 (@sub_snacking, 'Small Popcorn Chicken', 'Small portion of popcorn chicken', 5.09, 2.50, 'Sweet & Savory'),
 (@sub_snacking, 'Large Popcorn Chicken', 'Large portion of popcorn chicken', 6.29, 2.90, 'Sweet & Savory'),
 (@sub_snacking, 'Small Chicken Nuggets', 'Small portion of chicken nuggets', 4.99, 2.40, 'Sweet & Savory'),
 (@sub_snacking, 'Chicken Nuggets', 'Regular portion of chicken nuggets', 5.49, 2.55, 'Sweet & Savory'),
 (@sub_snacking, 'Large Chicken Nuggets', 'Large portion of chicken nuggets', 6.19, 2.80, 'Sweet & Savory'),
 (@sub_snacking, 'Small Waffle Fries', 'Small portion of waffle fries', 4.29, 1.70, 'Sweet & Savory'),
 (@sub_snacking, 'Waffle Fries', 'Regular portion of waffle fries', 4.79, 1.85, 'Sweet & Savory'),
 (@sub_snacking, 'Large Waffle Fries', 'Large portion of waffle fries', 5.49, 2.10, 'Sweet & Savory'),
 (@sub_snacking, 'Small Curly Fries', 'Small portion of curly fries', 4.29, 1.70, 'Sweet & Savory'),
 (@sub_snacking, 'Curly Fries', 'Regular portion of curly fries', 4.79, 1.85, 'Sweet & Savory'),
 (@sub_snacking, 'Large Curly Fries', 'Large portion of curly fries', 5.49, 2.10, 'Sweet & Savory'),
 (@sub_snacking, 'Small Sweet Potato Fries', 'Small portion of sweet potato fries', 4.39, 1.80, 'Sweet & Savory'),
 (@sub_snacking, 'Sweet Potato Fries', 'Regular portion of sweet potato fries', 4.89, 1.95, 'Sweet & Savory'),
 (@sub_snacking, 'Large Sweet Potato Fries', 'Large portion of sweet potato fries', 5.59, 2.20, 'Sweet & Savory'),
 (@sub_snacking, 'Small Loaded Tots', 'Small portion of loaded tots', 4.59, 2.00, 'Sweet & Savory'),
 (@sub_snacking, 'Loaded Tots', 'Regular portion of loaded tots', 5.09, 2.15, 'Sweet & Savory'),
 (@sub_snacking, 'Large Loaded Tots', 'Large portion of loaded tots', 5.79, 2.40, 'Sweet & Savory'),
 (@sub_snacking, 'Small Fried Cheese Bites', 'Small portion of fried cheese bites', 4.69, 2.10, 'Sweet & Savory'),
 (@sub_snacking, 'Fried Cheese Bites', 'Regular portion of fried cheese bites', 5.19, 2.25, 'Sweet & Savory'),
 (@sub_snacking, 'Large Fried Cheese Bites', 'Large portion of fried cheese bites', 5.89, 2.50, 'Sweet & Savory'),
 (@sub_snacking, 'Small Breaded Shrimp', 'Small portion of breaded shrimp', 5.49, 2.90, 'Sweet & Savory'),
 (@sub_snacking, 'Breaded Shrimp', 'Regular portion of breaded shrimp', 5.99, 3.05, 'Sweet & Savory'),
 (@sub_snacking, 'Large Breaded Shrimp', 'Large portion of breaded shrimp', 6.69, 3.30, 'Sweet & Savory'),
 (@sub_snacking, 'Small Cauliflower Bites', 'Small portion of cauliflower bites', 4.49, 1.90, 'Sweet & Savory'),
 (@sub_snacking, 'Cauliflower Bites', 'Regular portion of cauliflower bites', 4.99, 2.05, 'Sweet & Savory'),
 (@sub_snacking, 'Large Cauliflower Bites', 'Large portion of cauliflower bites', 5.69, 2.30, 'Sweet & Savory'),
 (@sub_snacking, 'Small Veggie Fritters', 'Small portion of veggie fritters', 4.39, 1.80, 'Sweet & Savory');
