-- Expands each of the 4 Featured sub-tabs (New Arrivals, Fan Favorites, Limited Time
-- Offers, Value Bundles) to 50+ items, matching the "50+ per category" pattern already
-- applied to the 6 Beverages subcategories. All item names are original to this shop.
USE pos_system;

SET @sub_new = (SELECT id FROM categories WHERE name = 'New Arrivals');
SET @sub_fan = (SELECT id FROM categories WHERE name = 'Fan Favorites');
SET @sub_lto = (SELECT id FROM categories WHERE name = 'Limited Time Offers');
SET @sub_bundles = (SELECT id FROM categories WHERE name = 'Value Bundles');

-- ==================== NEW ARRIVALS (38 new -> 50 total) ====================
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@sub_new, 'Peach Mango Refresher', 'Fruit-flavored refresher with peach and mango', 3.95, 0.95, 'Refreshers'),
 (@sub_new, 'Watermelon Basil Refresher', 'Fruit-flavored refresher with watermelon and basil', 3.95, 0.95, 'Refreshers'),
 (@sub_new, 'Blueberry Lavender Refresher', 'Fruit-flavored refresher with blueberry and lavender', 4.05, 1.00, 'Refreshers'),
 (@sub_new, 'Pineapple Coconut Refresher', 'Fruit-flavored refresher with pineapple and coconut', 4.05, 1.00, 'Refreshers'),
 (@sub_new, 'Raspberry Rose Refresher', 'Fruit-flavored refresher with raspberry and rose', 4.05, 1.00, 'Refreshers'),
 (@sub_new, 'Kiwi Melon Refresher', 'Fruit-flavored refresher with kiwi and melon', 3.95, 0.95, 'Refreshers'),
 (@sub_new, 'Passionfruit Guava Refresher', 'Fruit-flavored refresher with passionfruit and guava', 4.05, 1.00, 'Refreshers'),
 (@sub_new, 'Salted Caramel Cloud Latte', 'Latte with salted caramel and cream', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_new, 'Pistachio Cloud Latte', 'Latte with pistachio and cream', 4.99, 1.45, 'Lattes & Espresso'),
 (@sub_new, 'Honey Cinnamon Latte', 'Latte with honey and cinnamon', 4.65, 1.30, 'Lattes & Espresso'),
 (@sub_new, 'Brown Butter Cloud Latte', 'Latte with brown butter and cream', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_new, 'Espresso Con Panna', 'Espresso topped with whipped cream', 3.95, 1.05, 'Lattes & Espresso'),
 (@sub_new, 'Vanilla Bean Shakin'' Espresso', 'Shaken espresso with vanilla bean', 4.65, 1.30, 'Lattes & Espresso'),
 (@sub_new, 'Iced Cascara Latte', 'Iced latte with cascara sweetener', 4.75, 1.35, 'Lattes & Espresso'),
 (@sub_new, 'Maple Walnut Cloud Latte', 'Latte with maple walnut and cream', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_new, 'Vanilla Bean Matcha', 'Whisked matcha with vanilla bean', 4.75, 1.50, 'Matcha'),
 (@sub_new, 'Strawberry Matcha Cloud', 'Matcha with strawberry cream', 4.85, 1.50, 'Matcha'),
 (@sub_new, 'Honey Matcha Latte', 'Matcha latte sweetened with honey', 4.75, 1.50, 'Matcha'),
 (@sub_new, 'Blackberry Matcha Limeade', 'Matcha limeade with blackberry', 4.65, 1.35, 'Matcha'),
 (@sub_new, 'Coconut Cream Matcha', 'Matcha with coconut cream', 4.85, 1.50, 'Matcha'),
 (@sub_new, 'Peach Matcha Fizz', 'Sparkling matcha with peach', 4.65, 1.35, 'Matcha'),
 (@sub_new, 'Raspberry Mint Lemonade', 'Fresh-squeezed lemonade with raspberry and mint', 3.65, 0.85, 'Lemonade'),
 (@sub_new, 'Blueberry Basil Lemonade', 'Fresh-squeezed lemonade with blueberry and basil', 3.65, 0.85, 'Lemonade'),
 (@sub_new, 'Peach Ginger Lemonade', 'Fresh-squeezed lemonade with peach and ginger', 3.65, 0.85, 'Lemonade'),
 (@sub_new, 'Watermelon Lemonade', 'Fresh-squeezed lemonade with watermelon', 3.55, 0.80, 'Lemonade'),
 (@sub_new, 'Cucumber Lime Limeade', 'Limeade with cucumber and lime', 3.65, 0.85, 'Lemonade'),
 (@sub_new, 'Strawberry Kiwi Limeade', 'Limeade with strawberry and kiwi', 3.75, 0.90, 'Lemonade'),
 (@sub_new, 'Dawn Peach Zero', 'Zero-sugar sparkling water with peach', 2.95, 0.60, 'Zero Sugar'),
 (@sub_new, 'Horizon Mint Zero', 'Zero-sugar sparkling water with mint', 2.95, 0.60, 'Zero Sugar'),
 (@sub_new, 'Ocean Breeze Zero', 'Zero-sugar sparkling water with sea salt citrus', 2.95, 0.60, 'Zero Sugar'),
 (@sub_new, 'Sunset Grape Zero', 'Zero-sugar sparkling water with grape', 2.95, 0.60, 'Zero Sugar'),
 (@sub_new, 'Meadow Lime Zero', 'Zero-sugar sparkling water with lime', 2.95, 0.60, 'Zero Sugar'),
 (@sub_new, 'Frost Melon Zero', 'Zero-sugar sparkling water with melon', 2.95, 0.60, 'Zero Sugar'),
 (@sub_new, 'Vanilla Bean Chiller', 'Blended frozen vanilla bean drink', 4.75, 1.30, 'Chillers'),
 (@sub_new, 'Caramel Pecan Chiller', 'Blended frozen coffee with caramel pecan', 4.95, 1.40, 'Chillers'),
 (@sub_new, 'White Chocolate Chiller', 'Blended frozen white chocolate drink', 4.95, 1.40, 'Chillers'),
 (@sub_new, 'Toasted Coconut Chiller', 'Blended frozen coffee with toasted coconut', 4.95, 1.40, 'Chillers'),
 (@sub_new, 'Cinnamon Dolce Chiller', 'Blended frozen coffee with cinnamon dolce', 4.95, 1.40, 'Chillers');

-- ==================== FAN FAVORITES (38 new -> 50 total) ====================
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@sub_fan, 'Georgia Peach Refresher', 'Peach-flavored refresher', 3.85, 0.95, 'Refreshers'),
 (@sub_fan, 'Wild Berry Refresher', 'Mixed wild berry refresher', 3.85, 0.95, 'Refreshers'),
 (@sub_fan, 'Citrus Sunburst Refresher', 'Citrus-flavored refresher', 3.85, 0.95, 'Refreshers'),
 (@sub_fan, 'Coconut Lime Refresher', 'Coconut lime refresher', 3.95, 1.00, 'Refreshers'),
 (@sub_fan, 'Pomegranate Refresher', 'Pomegranate-flavored refresher', 3.95, 1.00, 'Refreshers'),
 (@sub_fan, 'Dragonfruit Refresher', 'Dragonfruit-flavored refresher', 4.05, 1.05, 'Refreshers'),
 (@sub_fan, 'Blood Orange Refresher', 'Blood orange-flavored refresher', 3.95, 1.00, 'Refreshers'),
 (@sub_fan, 'Classic Caramel Cloud Latte', 'Latte with classic caramel and cream', 4.65, 1.30, 'Lattes & Espresso'),
 (@sub_fan, 'Hazelnut Cloud Latte', 'Latte with hazelnut and cream', 4.65, 1.30, 'Lattes & Espresso'),
 (@sub_fan, 'Mocha Cloud Latte', 'Latte with chocolate mocha and cream', 4.75, 1.35, 'Lattes & Espresso'),
 (@sub_fan, 'Cinnamon Cloud Latte', 'Latte with cinnamon and cream', 4.65, 1.30, 'Lattes & Espresso'),
 (@sub_fan, 'Double Shot Espresso', 'Double shot of espresso', 3.25, 0.85, 'Lattes & Espresso'),
 (@sub_fan, 'Oat Milk Cloud Latte', 'Latte made with oat milk and cream', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_fan, 'White Mocha Cloud Latte', 'Latte with white mocha and cream', 4.85, 1.35, 'Lattes & Espresso'),
 (@sub_fan, 'Classic Matcha Latte', 'Traditional matcha latte', 4.65, 1.45, 'Matcha'),
 (@sub_fan, 'Brown Sugar Matcha', 'Matcha with brown sugar', 4.75, 1.50, 'Matcha'),
 (@sub_fan, 'Coconut Matcha Cloud', 'Matcha with coconut cream', 4.85, 1.50, 'Matcha'),
 (@sub_fan, 'Rose Matcha Latte', 'Matcha latte with rose', 4.85, 1.50, 'Matcha'),
 (@sub_fan, 'Honeydew Matcha', 'Matcha with honeydew', 4.75, 1.50, 'Matcha'),
 (@sub_fan, 'Mango Matcha Fizz', 'Sparkling matcha with mango', 4.65, 1.35, 'Matcha'),
 (@sub_fan, 'Classic Pink Lemonade', 'Classic pink lemonade', 3.45, 0.75, 'Lemonade'),
 (@sub_fan, 'Mint Lemonade', 'Lemonade with fresh mint', 3.55, 0.80, 'Lemonade'),
 (@sub_fan, 'Blackberry Limeade', 'Limeade with blackberry', 3.85, 0.90, 'Lemonade'),
 (@sub_fan, 'Peach Lemonade', 'Lemonade with peach', 3.65, 0.85, 'Lemonade'),
 (@sub_fan, 'Cherry Limeade', 'Limeade with cherry', 3.75, 0.90, 'Lemonade'),
 (@sub_fan, 'Ginger Lemonade', 'Lemonade with ginger', 3.65, 0.85, 'Lemonade'),
 (@sub_fan, 'Classic Splash Zero', 'Zero-sugar sparkling water, classic', 2.95, 0.60, 'Zero Sugar'),
 (@sub_fan, 'Citrus Wave Zero', 'Zero-sugar sparkling water with citrus', 2.95, 0.60, 'Zero Sugar'),
 (@sub_fan, 'Berry Bliss Zero', 'Zero-sugar sparkling water with berry', 2.95, 0.60, 'Zero Sugar'),
 (@sub_fan, 'Tropical Tide Zero', 'Zero-sugar sparkling water with tropical fruit', 2.95, 0.60, 'Zero Sugar'),
 (@sub_fan, 'Cool Mint Zero', 'Zero-sugar sparkling water with mint', 2.95, 0.60, 'Zero Sugar'),
 (@sub_fan, 'Apple Crisp Zero', 'Zero-sugar sparkling water with apple', 2.95, 0.60, 'Zero Sugar'),
 (@sub_fan, 'Grapefruit Glow Zero', 'Zero-sugar sparkling water with grapefruit', 2.95, 0.60, 'Zero Sugar'),
 (@sub_fan, 'Classic Coffee Chiller', 'Blended frozen classic coffee', 4.65, 1.30, 'Chillers'),
 (@sub_fan, 'Java Chip Chiller', 'Blended frozen coffee with chocolate chips', 4.95, 1.40, 'Chillers'),
 (@sub_fan, 'Hazelnut Chiller', 'Blended frozen coffee with hazelnut', 4.85, 1.35, 'Chillers'),
 (@sub_fan, 'Caramel Macchiato Chiller', 'Blended frozen caramel macchiato', 4.95, 1.40, 'Chillers'),
 (@sub_fan, 'Double Mocha Chiller', 'Blended frozen coffee with double mocha', 4.99, 1.45, 'Chillers');

-- ==================== LIMITED TIME OFFERS (40 new -> 50 total) ====================
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@sub_lto, 'Grapefruit Rosemary Spritz', 'Sparkling grapefruit rosemary refresher', 4.25, 1.05, 'Spritz'),
 (@sub_lto, 'Strawberry Basil Spritz', 'Sparkling strawberry basil refresher', 4.25, 1.05, 'Spritz'),
 (@sub_lto, 'Mango Chili Spritz', 'Sparkling mango chili refresher', 4.35, 1.10, 'Spritz'),
 (@sub_lto, 'Watermelon Mint Spritz', 'Sparkling watermelon mint refresher', 4.25, 1.05, 'Spritz'),
 (@sub_lto, 'Blood Orange Ginger Spritz', 'Sparkling blood orange ginger refresher', 4.35, 1.10, 'Spritz'),
 (@sub_lto, 'Raspberry Lime Spritz', 'Sparkling raspberry lime refresher', 4.25, 1.05, 'Spritz'),
 (@sub_lto, 'Pineapple Jalapeno Spritz', 'Sparkling pineapple jalapeno refresher', 4.45, 1.15, 'Spritz'),
 (@sub_lto, 'Pomegranate Sage Spritz', 'Sparkling pomegranate sage refresher', 4.35, 1.10, 'Spritz'),
 (@sub_lto, 'Passionfruit Citrus Spritz', 'Sparkling passionfruit citrus refresher', 4.35, 1.10, 'Spritz'),
 (@sub_lto, 'Cranberry Orange Spritz', 'Sparkling cranberry orange refresher', 4.25, 1.05, 'Spritz'),
 (@sub_lto, 'Gingerbread Cloud Latte', 'Seasonal gingerbread latte', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_lto, 'Peppermint Mocha Cloud Latte', 'Seasonal peppermint mocha latte', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_lto, 'Eggnog Cloud Latte', 'Seasonal eggnog latte', 4.99, 1.45, 'Lattes & Espresso'),
 (@sub_lto, 'Toasted Marshmallow Latte', 'Latte with toasted marshmallow', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_lto, 'Apple Pie Cloud Latte', 'Seasonal apple pie latte', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_lto, 'Cinnamon Roll Cloud Latte', 'Latte with cinnamon roll flavor', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_lto, 'Butter Pecan Cloud Latte', 'Latte with butter pecan flavor', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_lto, 'Chestnut Praline Latte', 'Seasonal chestnut praline latte', 4.99, 1.45, 'Lattes & Espresso'),
 (@sub_lto, 'Caramel Apple Cloud Latte', 'Seasonal caramel apple latte', 4.95, 1.40, 'Lattes & Espresso'),
 (@sub_lto, 'Spiced Chai Cloud Latte', 'Latte with spiced chai and cream', 4.85, 1.35, 'Lattes & Espresso'),
 (@sub_lto, 'Cranberry Spice Zero', 'Zero-sugar sparkling water with cranberry spice', 2.95, 0.60, 'Zero Sugar'),
 (@sub_lto, 'Winter Mint Zero', 'Zero-sugar sparkling water with winter mint', 2.95, 0.60, 'Zero Sugar'),
 (@sub_lto, 'Autumn Apple Zero', 'Zero-sugar sparkling water with apple', 2.95, 0.60, 'Zero Sugar'),
 (@sub_lto, 'Spiced Pear Zero', 'Zero-sugar sparkling water with spiced pear', 2.95, 0.60, 'Zero Sugar'),
 (@sub_lto, 'Frosted Berry Zero', 'Zero-sugar sparkling water with frosted berry', 2.95, 0.60, 'Zero Sugar'),
 (@sub_lto, 'Citrus Chill Zero', 'Zero-sugar sparkling water with citrus chill', 2.95, 0.60, 'Zero Sugar'),
 (@sub_lto, 'Peppermint Zero', 'Zero-sugar sparkling water with peppermint', 2.95, 0.60, 'Zero Sugar'),
 (@sub_lto, 'Ginger Zero', 'Zero-sugar sparkling water with ginger', 2.95, 0.60, 'Zero Sugar'),
 (@sub_lto, 'Pomegranate Zero', 'Zero-sugar sparkling water with pomegranate', 2.95, 0.60, 'Zero Sugar'),
 (@sub_lto, 'Maple Zero', 'Zero-sugar sparkling water with maple', 2.95, 0.60, 'Zero Sugar'),
 (@sub_lto, 'Peppermint Mocha Chiller', 'Blended frozen peppermint mocha', 4.99, 1.45, 'Chillers'),
 (@sub_lto, 'Pumpkin Spice Chiller', 'Blended frozen pumpkin spice', 4.99, 1.45, 'Chillers'),
 (@sub_lto, 'Gingerbread Chiller', 'Blended frozen gingerbread', 4.99, 1.45, 'Chillers'),
 (@sub_lto, 'Eggnog Chiller', 'Blended frozen eggnog', 4.99, 1.45, 'Chillers'),
 (@sub_lto, 'Caramel Apple Chiller', 'Blended frozen caramel apple', 4.99, 1.45, 'Chillers'),
 (@sub_lto, 'Toffee Nut Chiller', 'Blended frozen toffee nut', 4.99, 1.45, 'Chillers'),
 (@sub_lto, 'Butterscotch Chiller', 'Blended frozen butterscotch', 4.99, 1.45, 'Chillers'),
 (@sub_lto, 'Spiced Cinnamon Chiller', 'Blended frozen spiced cinnamon', 4.99, 1.45, 'Chillers'),
 (@sub_lto, 'Maple Pecan Chiller', 'Blended frozen maple pecan', 4.99, 1.45, 'Chillers'),
 (@sub_lto, 'Hot Cocoa Chiller', 'Blended frozen hot cocoa', 4.99, 1.45, 'Chillers');

-- ==================== VALUE BUNDLES (44 new -> 50 total) ====================
INSERT INTO menu_items (category_id, name, description, price, cost, section) VALUES
 (@sub_bundles, 'Hot Coffee Bundle (5-pack)', 'Five hot coffees to go', 13.99, 4.20, 'Bundles'),
 (@sub_bundles, 'Cold Brew Bundle (5-pack)', 'Five cold brews to go', 16.99, 5.10, 'Bundles'),
 (@sub_bundles, 'Nitro Cold Brew Bundle (4-pack)', 'Four nitro cold brews to go', 17.99, 5.40, 'Bundles'),
 (@sub_bundles, 'Vanilla Latte Bundle (4-pack)', 'Four vanilla lattes to go', 17.99, 5.40, 'Bundles'),
 (@sub_bundles, 'Caramel Latte Bundle (4-pack)', 'Four caramel lattes to go', 17.99, 5.40, 'Bundles'),
 (@sub_bundles, 'Mocha Latte Bundle (4-pack)', 'Four mocha lattes to go', 17.99, 5.40, 'Bundles'),
 (@sub_bundles, 'Espresso Shot Bundle (6-pack)', 'Six espresso shots to go', 12.99, 3.90, 'Bundles'),
 (@sub_bundles, 'Chai Latte Bundle (4-pack)', 'Four chai lattes to go', 16.99, 5.10, 'Bundles'),
 (@sub_bundles, 'Green Tea Matcha Bundle (3-pack)', 'Three matcha drinks to go', 13.99, 5.00, 'Bundles'),
 (@sub_bundles, 'Strawberry Refresher Bundle (4-pack)', 'Four strawberry refreshers to go', 15.99, 4.80, 'Bundles'),
 (@sub_bundles, 'Mango Refresher Bundle (4-pack)', 'Four mango refreshers to go', 15.99, 4.80, 'Bundles'),
 (@sub_bundles, 'Black Cherry Refresher Bundle (4-pack)', 'Four black cherry refreshers to go', 15.99, 4.80, 'Bundles'),
 (@sub_bundles, 'Citrus Refresher Bundle (4-pack)', 'Four citrus refreshers to go', 15.99, 4.80, 'Bundles'),
 (@sub_bundles, 'Pink Lemonade Bundle (4-pack)', 'Four pink lemonades to go', 14.99, 4.50, 'Bundles'),
 (@sub_bundles, 'Classic Lemonade Bundle (4-pack)', 'Four classic lemonades to go', 13.99, 4.20, 'Bundles'),
 (@sub_bundles, 'Coconut Limeade Bundle (4-pack)', 'Four coconut limeades to go', 15.99, 4.80, 'Bundles'),
 (@sub_bundles, 'Zero Sugar Variety Bundle (4-pack)', 'Four assorted zero-sugar sparkling waters', 11.99, 3.60, 'Bundles'),
 (@sub_bundles, 'Berry Zero Bundle (4-pack)', 'Four berry zero-sugar sparkling waters', 11.99, 3.60, 'Bundles'),
 (@sub_bundles, 'Citrus Zero Bundle (4-pack)', 'Four citrus zero-sugar sparkling waters', 11.99, 3.60, 'Bundles'),
 (@sub_bundles, 'Mocha Chiller Bundle (4-pack)', 'Four mocha chillers to go', 19.99, 6.00, 'Bundles'),
 (@sub_bundles, 'Caramel Chiller Bundle (4-pack)', 'Four caramel chillers to go', 19.99, 6.00, 'Bundles'),
 (@sub_bundles, 'Vanilla Chiller Bundle (4-pack)', 'Four vanilla chillers to go', 19.99, 6.00, 'Bundles'),
 (@sub_bundles, 'Spritz Sampler Bundle (4-pack)', 'Four assorted spritz refreshers', 16.99, 5.10, 'Bundles'),
 (@sub_bundles, 'Family Coffee Box (12-cup)', 'Coffee box for family gatherings', 24.99, 9.50, 'Bundles'),
 (@sub_bundles, 'Party Refresher Box (10-pack)', 'Ten assorted refreshers for parties', 32.99, 12.50, 'Bundles'),
 (@sub_bundles, 'Office Coffee Box (20-cup)', 'Large coffee box for the office', 39.99, 15.00, 'Bundles'),
 (@sub_bundles, 'Kids Juice Bundle (4-pack)', 'Four kids juices to go', 6.99, 2.10, 'Bundles'),
 (@sub_bundles, 'Kids Chocolate Milk Bundle (4-pack)', 'Four kids chocolate milks to go', 6.99, 2.10, 'Bundles'),
 (@sub_bundles, 'Kids Lemonade Bundle (4-pack)', 'Four kids lemonades to go', 6.99, 2.10, 'Bundles'),
 (@sub_bundles, 'Weekend Warrior Bundle (6-pack)', 'Six assorted drinks for the weekend', 22.99, 8.70, 'Bundles'),
 (@sub_bundles, 'Morning Starter Bundle (6-pack)', 'Six coffee and espresso drinks to start the day', 21.99, 8.30, 'Bundles'),
 (@sub_bundles, 'Afternoon Pick-Me-Up Bundle (4-pack)', 'Four assorted afternoon drinks', 17.99, 5.40, 'Bundles'),
 (@sub_bundles, 'Iced Tea Bundle (5-pack)', 'Five iced teas to go', 13.99, 4.20, 'Bundles'),
 (@sub_bundles, 'Sweet Tea Bundle (5-pack)', 'Five sweet teas to go', 13.99, 4.20, 'Bundles'),
 (@sub_bundles, 'Unsweetened Tea Bundle (5-pack)', 'Five unsweetened teas to go', 13.99, 4.20, 'Bundles'),
 (@sub_bundles, 'Hazelnut Latte Bundle (4-pack)', 'Four hazelnut lattes to go', 17.99, 5.40, 'Bundles'),
 (@sub_bundles, 'Oat Milk Latte Bundle (4-pack)', 'Four oat milk lattes to go', 18.99, 5.70, 'Bundles'),
 (@sub_bundles, 'Almond Milk Latte Bundle (4-pack)', 'Four almond milk lattes to go', 18.99, 5.70, 'Bundles'),
 (@sub_bundles, 'Decaf Latte Bundle (4-pack)', 'Four decaf lattes to go', 17.99, 5.40, 'Bundles'),
 (@sub_bundles, 'Cold Brew Concentrate Bundle (2-pack)', 'Two cold brew concentrates, makes 8 drinks', 19.99, 6.00, 'Bundles'),
 (@sub_bundles, 'Matcha Latte Bundle (4-pack)', 'Four matcha lattes to go', 18.99, 5.70, 'Bundles'),
 (@sub_bundles, 'Tropical Refresher Bundle (4-pack)', 'Four tropical refreshers to go', 15.99, 4.80, 'Bundles'),
 (@sub_bundles, 'Grab & Go Variety Bundle (6-pack)', 'Six assorted drinks, grab and go', 23.99, 9.10, 'Bundles'),
 (@sub_bundles, 'Ultimate Sampler Bundle (10-pack)', 'Ten assorted drinks, the ultimate sampler', 34.99, 13.30, 'Bundles');
